Repository elastic/fleet-server, pull requests merged in 2020-11, with the labels that each got.

#9 [jjbb] use usertoken
  .ci/jobs/fleet-server.yml
Labels: automation

#4 Add initial automation rules based on the rules from the beats
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/flaky-test.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/comment.yml
  .github/labels.yml
  .github/paths-labeller.yml
  .github/relabel.yml
  .github/stale.yml
Labels: Team:Ingest Management, review

#8 [CI] Add Jenkinsfile
  .ci/Jenkinsfile
  Makefile
Labels: automation

#10 [CI] Add CI build status
  README.md
Labels: automation

#11 Move build/ to dev-tools/
  .gitignore
  Makefile
  dev-tools/package/Dockerfile
  dev-tools/package/docker-compose.yml
  dev-tools/rpm/nfpm.yaml
Labels: cleanup

#7 Add to the schema for coordinator
  internal/pkg/model/schema.go
  main.go
  model/schema.json
Labels: Team:Ingest Management
