Repository elastic/fleet-server, pull requests merged in 2020-12, with the labels that each got.

#14 More work on the configuration and wire in ES connection and server binding
  cmd/fleet/auth.go
  cmd/fleet/bulkCheckin.go
  cmd/fleet/es.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/main.go
  cmd/fleet/server.go
  go.mod
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/config/elasticsearch.go
  internal/pkg/config/fleet.go
  internal/pkg/config/input.go
  internal/pkg/config/output.go
  internal/pkg/config/server.go
  internal/pkg/config/testdata/bad-input-many.yml
  internal/pkg/config/testdata/bad-input.yml
  internal/pkg/config/testdata/bad-logging.yml
  internal/pkg/config/testdata/bad-output.yml
  internal/pkg/config/testdata/basic.yml
  internal/pkg/config/testdata/empty.yml
  internal/pkg/config/testdata/fleet-logging.yml
  internal/pkg/config/testdata/input-config.yml
  internal/pkg/config/testdata/input.yml
  internal/pkg/env/env.go
  internal/pkg/logger/logger.go
Labels: Team:Ingest Management

#15 Hook up ES mapping generator
  Makefile
  go.mod
  go.sum
  main.go
Labels: enhancement

#17 Fix default configuration file
  fleet-server.yml
Labels: Team:Ingest Management

#19 Updated schema generator to support json.RawMessage. Added flag to not generate marshalling code.
  internal/pkg/esboot/mapping.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: enhancement

#21 Agent actions support
  Makefile
  cmd/fleet/auth.go
  cmd/fleet/bulkActions.go
  cmd/fleet/bulkCheckin.go
  cmd/fleet/handleAck.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/main.go
  cmd/fleet/router.go
  cmd/fleet/schema.go
  cmd/fleet/server_test.go
  fleet-server.yml
  go.mod
  go.sum
  internal/pkg/action/dispatcher.go
  internal/pkg/action/monitor.go
  internal/pkg/action/token_resolver.go
  internal/pkg/bulk/bulk.go
  internal/pkg/bulk/schema.go
  internal/pkg/config/config.go
  internal/pkg/config/feature.go
  internal/pkg/dl/actions.go
  internal/pkg/dl/agent.go
  internal/pkg/dl/constants.go
  internal/pkg/dl/global_checkpoint.go
  internal/pkg/dl/search.go
  internal/pkg/dl/seqno.go
  internal/pkg/dsl/aggs.go
  internal/pkg/dsl/field.go
  internal/pkg/dsl/filter.go
  internal/pkg/dsl/keyword.go
  internal/pkg/dsl/param.go
  internal/pkg/dsl/range.go
  internal/pkg/dsl/source.go
  internal/pkg/dsl/tmpl.go
  internal/pkg/esboot/mapping.go
  internal/pkg/model/schema.go
  internal/pkg/saved/crud.go
  internal/pkg/testing/bulk.go
  model/schema.json
Labels: Feature:fleet-server, enhancement

#23 Add ability to reload configuration
  cmd/fleet/main.go
  cmd/fleet/router.go
  cmd/fleet/server.go
  cmd/fleet/server_test.go
  dev-tools/integration/main.go
  internal/pkg/dl/actions_integration_test.go
  internal/pkg/es/client.go
  internal/pkg/es/es.go
  internal/pkg/esboot/bootstrap.go
  internal/pkg/esboot/datastream.go
  internal/pkg/esboot/ilm.go
  internal/pkg/esboot/index.go
  internal/pkg/esboot/template.go
  internal/pkg/logger/logger.go
  internal/pkg/reload/reload.go
Labels: Team:Ingest Management

#28 Wired the enrollment against .fleet-enrollment-api-keys index
  Makefile
  cmd/fleet/cache.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/main.go
  cmd/fleet/router.go
  cmd/fleet/server_test.go
  internal/pkg/dl/actions_integration_test.go
  internal/pkg/dl/enrollment_api_key.go
  internal/pkg/dl/enrollment_api_key_integration_test.go
  internal/pkg/dl/enrollment_api_key_test.go
  internal/pkg/es/mapping.go
  internal/pkg/esboot/bootstrap.go
  internal/pkg/migrate/migrate.go
  main.go
Labels: Feature:fleet-server, enhancement

#32 [CI] Enable integration tests
  .ci/Jenkinsfile
  .ci/scripts/install-docker-compose.sh
  Makefile
Labels: automation

#41 Add new policy.Monitor for use with checkin
  cmd/fleet/bulkPolicy.go
  cmd/fleet/handleAck.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/main.go
  cmd/fleet/schema.go
  cmd/fleet/server_test.go
  internal/pkg/action/dispatcher.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/coordinator/monitor_integration_test.go
  internal/pkg/coordinator/v0.go
  internal/pkg/coordinator/v0_test.go
  internal/pkg/dl/constants.go
  internal/pkg/dl/policies_integration_test.go
  internal/pkg/es/mapping.go
  internal/pkg/es/result_test.go
  internal/pkg/model/schema.go
  internal/pkg/monitor/mock/monitor.go
  internal/pkg/monitor/monitor.go
  internal/pkg/monitor/monitor_integration_test.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/policy/monitor_test.go
  internal/pkg/policy/revision.go
  model/schema.json
Labels: Feature:fleet-server, Team:Ingest Management

#42 Ack new action results and remove old actions
  cmd/fleet/bulkActions.go
  cmd/fleet/cache.go
  cmd/fleet/handleAck.go
  cmd/fleet/handleActionResult.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/main.go
  cmd/fleet/router.go
  cmd/fleet/schema.go
  cmd/fleet/server_test.go
  go.mod
  go.sum
Labels: Feature:fleet-server, Team:Ingest Management

#44 Handle ack of UNENROLL.
  cmd/fleet/auth.go
  cmd/fleet/handleAck.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/main.go
  cmd/fleet/schema.go
  cmd/fleet/server_integration_test.go
  cmd/fleet/server_test.go
  internal/pkg/cache/cache.go
  internal/pkg/dl/actions.go
  internal/pkg/dl/constants.go
Labels: Feature:fleet-server, Team:Ingest Management
