Repository elastic/fleet-server, pull requests merged in 2021-03, with the labels that each got.

#110 Remove saved objects code
  NOTICE.txt
  cmd/fleet/bulkCheckin.go
  cmd/fleet/dsl.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/main.go
  go.mod
  go.sum
  internal/pkg/migrate/migrate.go
  internal/pkg/saved/crud.go
  internal/pkg/saved/crypto.go
  internal/pkg/saved/encode.go
  internal/pkg/saved/errors.go
  internal/pkg/saved/fields.go
  internal/pkg/saved/id.go
  internal/pkg/saved/nonce.go
  internal/pkg/saved/opts.go
  internal/pkg/saved/query.go
Labels: cleanup

#116 Fix global checkpoint based monitoring
  internal/pkg/monitor/global_checkpoint.go
Labels: bug

#118 Set agent active to false on unenroll
  cmd/fleet/handleAck.go
  internal/pkg/dl/constants.go
Labels: Team:Fleet

#120 Cherry-pick #118 to 7.x: Set agent active to false on unenroll
  cmd/fleet/handleAck.go
  internal/pkg/dl/constants.go
Labels: Team:Fleet, [zube]: In Review, backport

#113 Basic metrics framework leveraging beats logic.
  NOTICE.txt
  cmd/fleet/main.go
  cmd/fleet/metrics.go
  cmd/fleet/server.go
  go.mod
  go.sum
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/config/http.go
  internal/pkg/logger/zapStub.go
Labels: enhancement

#124 Add API key invalidation on unenroll ACK.
  cmd/fleet/handleAck.go
  cmd/fleet/server_integration_test.go
  internal/pkg/apikey/auth.go
  internal/pkg/apikey/create.go
  internal/pkg/apikey/invalidate.go
Labels: Team:Agent

#125 Cherry-pick #124 to 7.x: Add API key invalidation on unenroll ACK.
  cmd/fleet/handleAck.go
  cmd/fleet/server_integration_test.go
  internal/pkg/apikey/auth.go
  internal/pkg/apikey/create.go
  internal/pkg/apikey/invalidate.go
Labels: Team:Agent, [zube]: In Review, backport

#122 Add optional hard connection limit to the server. No more than N con…
  NOTICE.txt
  cmd/fleet/server.go
  go.mod
  internal/pkg/config/input.go
Labels: enhancement

#112 Enable trace level logging
  internal/pkg/config/config_test.go
  internal/pkg/config/fleet.go
  internal/pkg/config/testdata/bad-logging.yml
Labels: enhancement

#127 Cherry-pick #112 to 7.x: Enable trace level logging (#112)
  internal/pkg/config/config_test.go
  internal/pkg/config/fleet.go
  internal/pkg/config/testdata/bad-logging.yml
Labels: backport

#128 Update Event payload type.
  cmd/fleet/schema.go
Labels: bug

#131 Add API status endpoint
  cmd/fleet/handleStatus.go
  cmd/fleet/main.go
  cmd/fleet/router.go
  cmd/fleet/schema.go
  cmd/fleet/server_integration_test.go
  cmd/fleet/server_test.go
  internal/pkg/policy/self.go
Labels: Team:Agent

#138 Cherry-pick #131 to 7.x: Add API status endpoint
  cmd/fleet/handleStatus.go
  cmd/fleet/main.go
  cmd/fleet/router.go
  cmd/fleet/schema.go
  cmd/fleet/server_integration_test.go
  cmd/fleet/server_test.go
  internal/pkg/policy/self.go
Labels: Team:Agent, [zube]: In Review, backport

#139 Cherry-pick #133 to 7.x: Cleanup and refactoring
  cmd/fleet/handleChecking_test.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/main.go
  cmd/fleet/missing.txt
  fleet-server.yml
  go.sum
  internal/pkg/apikey/apikey_test.go
  internal/pkg/apikey/invalidate.go
  internal/pkg/coordinator/v0_test.go
  internal/pkg/dsl/readme.txt
  internal/pkg/env/env.go
Labels: backport, review

#141 Add cache configuration option.
  cmd/fleet/main.go
  cmd/fleet/server_integration_test.go
  cmd/fleet/server_test.go
  internal/pkg/cache/cache.go
  internal/pkg/config/cache.go
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/throttle/throttle_test.go
Labels: enhancement

#148 Add cache configuration option.
  cmd/fleet/main.go
  cmd/fleet/server_integration_test.go
  cmd/fleet/server_test.go
  internal/pkg/cache/cache.go
  internal/pkg/config/cache.go
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/throttle/throttle_test.go
Labels: backport

#149 Support buildmode=pie on 64 bit platforms.
  Makefile
Labels: backport

#146 Move from camelCase to snake_case to reflect change in Kibana.
  internal/pkg/dl/constants.go
  internal/pkg/es/mapping.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: bug

#150 Move from camelCase to snake_case to reflect change in Kibana.
  internal/pkg/dl/constants.go
  internal/pkg/es/mapping.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: backport

#152 Update Event payload type. (#128)
  cmd/fleet/schema.go
Labels: backport

#143 Enable backport automation with mergify
  .mergify.yml
Labels: automation

#154 mergify: quote the branches
  .mergify.yml
Labels: automation

#156 Remove darwin/arm64 support. Remove ASLR support for darwin.
  Makefile
Labels: bug

#159 Upgrade go compiler to 1.16.2 to support darwin/arm64 and buildmode=p…
  .go-version
  Makefile
Labels: enhancement, v7.13.0

#158 Bump to 7.12.1
  main.go
Labels: Team:Agent, review

#161 Fix incorrect buildmode for arm64/darwin
  Makefile
Labels: bug, v7.13.0

#162 Fix configuration for cache and server profiler off by default
  cmd/fleet/main.go
  fleet-server.yml
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/config/input.go
Labels: Team:Agent, v7.13.0

#168 [mergify] auto-merge backports
  .mergify.yml
Labels: automation

#171 Increase the monitor throughput: increase the default fetch size, make it configurable.
  cmd/fleet/main.go
  internal/pkg/config/config_test.go
  internal/pkg/config/input.go
  internal/pkg/config/monitor.go
  internal/pkg/monitor/monitor.go
Labels: enhancement

#174 Change the agent.action_seq_no storage format from number to an array
  NOTICE.txt
  cmd/fleet/bulkCheckin.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  go.mod
  go.sum
  internal/pkg/action/dispatcher.go
  internal/pkg/dl/constants.go
  internal/pkg/model/schema.go
  internal/pkg/sqn/sqn.go
  model/schema.json
Labels: breaking change

#169 Indexing permissions as part of the Elastic Agent policy
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/schema.go
  internal/pkg/dl/policies.go
  internal/pkg/es/mapping.go
  internal/pkg/model/schema.go
  internal/pkg/policy/output_permissions.go
  internal/pkg/policy/output_permissions_test.go
  internal/pkg/smap/smap.go
  model/schema.json
Labels: enhancement

#177 Fix the handling of the upgrade ack.
  cmd/fleet/handleAck.go
  cmd/fleet/schema.go
  internal/pkg/dl/constants.go
Labels: Team:Agent, v7.13.0

#170 Remove the left over systemd and rpm build items
  dev-tools/rpm/nfpm.yaml
  systemd/fleet.service
Labels: Team:Agent, v7.13.0

#180 Fix issue with rolling out policies from the coordinator.
  internal/pkg/coordinator/v0.go
  internal/pkg/dl/policies.go
  internal/pkg/dsl/term.go
Labels: Team:Agent, v7.13.0

#187 Indexing permissions as part of the Elastic Agent policy
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/schema.go
  fleet-server.yml
  internal/pkg/dl/policies.go
  internal/pkg/es/mapping.go
  internal/pkg/model/schema.go
  internal/pkg/policy/output_permissions.go
  internal/pkg/policy/output_permissions_test.go
  internal/pkg/smap/smap.go
  model/schema.json
Labels: enhancement

#190 Cherry-pick #174 to 7.x: Change the agent.action_seq_no storage format from number to an array
  NOTICE.txt
  cmd/fleet/bulkCheckin.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  go.mod
  go.sum
  internal/pkg/action/dispatcher.go
  internal/pkg/dl/constants.go
  internal/pkg/model/schema.go
  internal/pkg/sqn/sqn.go
  model/schema.json
Labels: backport, review
