Repository elastic/fleet-server, pull requests merged in 2021-12, with the labels that each got.

#939 [automation] update elastic stack version for testing 7.15.3-ac0a2edb
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#941 [automation] update elastic stack version for testing 7.16.0-046aeba5
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#938 [automation] update elastic stack version for testing 8.0.0-df873dde
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#940 [automation] update elastic stack version for testing 8.1.0-274c36a2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#943 Mergify: replace merge action for the queue action
  .mergify.yml
Labels: automation, backport-skip

#944 [automation] update elastic stack version for testing 7.15.3-1d3806ef
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#947 [automation] update elastic stack version for testing 7.16.0-80ab1dd0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#946 [automation] update elastic stack version for testing 8.1.0-376424f6
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#945 [automation] update elastic stack version for testing 8.0.0-aab6301c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#950 [automation] update elastic stack version for testing 7.16.0-f17274e7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#953 [automation] update elastic stack version for testing 7.15.3-2191b0f7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#951 [automation] update elastic stack version for testing 8.0.0-eda77a0f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#952 [automation] update elastic stack version for testing 8.1.0-58719e16
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#956 [automation] update elastic stack version for testing 7.16.0-ef210289
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#957 [automation] update elastic stack version for testing 7.15.3-70c2e21f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#959 [automation] update elastic stack version for testing 8.0.0-1e314182
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#958 [automation] update elastic stack version for testing 8.1.0-30a394f1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#961 [automation] update elastic stack version for testing 7.16.0-f2941f42
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#963 [automation] update elastic stack version for testing 7.15.3-9e171938
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#962 [automation] update elastic stack version for testing 8.1.0-52507339
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#960 instrumentation: Add "tls" configuration options
  cmd/fleet/main.go
  internal/pkg/config/instrumentation.go
Labels: enhancement, v8.0.0, backport-v8.0.0

#954 Bump version to 7.16.1
  main.go
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#955 [automation] Update go release version 1.17.4
  .go-version
Labels: automation, dependency, backport-skip, backport-v8.0.0

#975 [automation] update elastic stack version for testing 7.16.0-eaf40d57
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#972 [automation] update elastic stack version for testing 7.15.3-984b6e42
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#973 [automation] update elastic stack version for testing 8.0.0-4535d287
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#974 [automation] update elastic stack version for testing 8.1.0-bc1630d1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#981 [automation] update elastic stack version for testing 7.16.1-53c0de77
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#980 [automation] update elastic stack version for testing 7.15.3-67d7b6ce
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#982 [automation] update elastic stack version for testing 8.0.0-fa37006f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#970 update go mod elatic/beats reference with newer commit
  NOTICE.txt
  cmd/fleet/main_integration_test.go
  cmd/fleet/server.go
  dev-tools/notice/overrides.json
  go.mod
  go.sum
Labels: enhancement, backport-v8.0.0, Team:Elastic-Agent-Control-Plane

#985 [automation] update elastic stack version for testing 7.16.1-1d21f78b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#986 [automation] update elastic stack version for testing 8.0.0-a8855495
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#987 [automation] update elastic stack version for testing 8.1.0-3cacb07d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#991 [automation] update elastic stack version for testing 7.16.1-2ceb4af4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#989 [automation] update elastic stack version for testing 8.1.0-b6e7e1f3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#990 [automation] update elastic stack version for testing 8.0.0-3c6e08ba
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#993 Bump version to 7.16.2
  main.go
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#994 [automation] update elastic stack version for testing 7.16.2-926bc45c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#997 [automation] update elastic stack version for testing 7.16.2-5ee0e439
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#998 [automation] update elastic stack version for testing 8.0.0-6b5f794c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#996 [automation] update elastic stack version for testing 8.1.0-f02e597e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#999 [automation] update elastic stack version for testing 7.16.2-e7a873d4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1001 [automation] update elastic stack version for testing 8.1.0-d8a3a806
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1000 [automation] update elastic stack version for testing 8.0.0-9fb1bbae
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#988 [automation] Update go release version 1.17.5
  .go-version
Labels: automation, dependency, backport-v8.0.0

#1008 [automation] update elastic stack version for testing 7.16.2-682993ae
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1007 [automation] update elastic stack version for testing 8.1.0-60bffc32
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1005 Add backport rule for 7.17 branch
  .mergify.yml
Labels: Team:Automation, backport-skip

#1009 Version bump to 7.16.3
  main.go
Labels: Team:Automation, backport-skip

#1012 [automation] update elastic stack version for testing 7.17.0-872523de
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1013 [automation] update elastic stack version for testing 8.0.0-002bf944
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1010 [automation] update elastic stack version for testing 8.1.0-befff95a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1017 [automation] update elastic stack version for testing 8.0.0-7b79b556
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1019 [automation] update elastic stack version for testing 7.17.0-aa797a6c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1021 [automation] update elastic stack version for testing 8.1.0-76902d39
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1024 [automation] update elastic stack version for testing 8.0.0-52f8db06
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#995 Deprecate username/password when connecting to es
  cmd/fleet/main.go
  internal/pkg/es/client.go
Labels: v7.16.0, backport-v7.16.0, Team:Elastic-Agent-Control-Plane

#1023 [automation] update elastic stack version for testing 7.17.0-e76712ab
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1006 Remove username/password
  Makefile
  cmd/fleet/main.go
  cmd/fleet/main_integration_test.go
  dev-tools/integration/get-elasticsearch-servicetoken.sh
  example/fleet-server-100.yml
  fleet-server.yml
  internal/pkg/bulk/bulk_integration_test.go
  internal/pkg/bulk/setup_test.go
  internal/pkg/config/config_test.go
  internal/pkg/config/output.go
  internal/pkg/config/output_test.go
  internal/pkg/config/testdata/bad-input-many.yml
  internal/pkg/config/testdata/bad-input.yml
  internal/pkg/config/testdata/bad-logging.yml
  internal/pkg/config/testdata/bad-output.yml
  internal/pkg/config/testdata/basic.yml
  internal/pkg/config/testdata/fleet-logging.yml
  internal/pkg/config/testdata/input-config.yml
  internal/pkg/config/testdata/input.yml
  internal/pkg/coordinator/monitor_integration_test.go
  internal/pkg/dl/action_results_integration_test.go
  internal/pkg/dl/actions_integration_test.go
  internal/pkg/dl/agent_integration_test.go
  internal/pkg/dl/enrollment_api_key_integration_test.go
  internal/pkg/dl/policies_integration_test.go
  internal/pkg/dl/policies_leader_integration_test.go
  internal/pkg/dl/servers_integration_test.go
  internal/pkg/es/client.go
  internal/pkg/gc/actions_integration_test.go
  internal/pkg/monitor/monitor_integration_test.go
  internal/pkg/monitor/subscription_monitor_integration_test.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/testing/setup.go
Labels: cleanup, backport-v8.0.0, Team:Elastic-Agent-Control-Plane

#1026 [7.16] (backport #995) Deprecate username/password when connecting to es
  cmd/fleet/main.go
  internal/pkg/es/client.go
Labels: backport

#1027 [automation] update elastic stack version for testing 8.1.0-dbc834fd
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1031 [automation] update elastic stack version for testing 7.17.0-6e4bbd35
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1032 [automation] update elastic stack version for testing 8.0.0-fde13a9d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1033 [automation] update elastic stack version for testing 8.1.0-614211a3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1035 [automation] update elastic stack version for testing 7.17.0-09b71949
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1036 [automation] update elastic stack version for testing 8.1.0-b989cb5c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#992 added more detailed logs around ES communication failure
  cmd/fleet/error.go
  internal/pkg/coordinator/monitor.go
Labels: cleanup, Team:Elastic-Agent-Control-Plane, backport-v8.1.0

#1041 [automation] update elastic stack version for testing 7.17.0-c02e8773
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1040 [automation] update elastic stack version for testing 8.0.0-b0d1c470
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1042 [automation] update elastic stack version for testing 8.1.0-c1a942c7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1044 [automation] update elastic stack version for testing 7.17.0-a34e30fc
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1046 [automation] update elastic stack version for testing 8.1.0-3cd1b136
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1047 [automation] update elastic stack version for testing 8.0.0-d1bb7d2c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1050 [automation] update elastic stack version for testing 7.17.0-53d9a9d2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1051 [automation] update elastic stack version for testing 8.1.0-544a92d3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1052 [automation] update elastic stack version for testing 8.0.0-d3289c33
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
