Repository elastic/fleet-server, pull requests merged in 2021-10, with the labels that each got.

#754 [automation] update elastic stack version for testing 7.16.0-806be5a9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#753 [automation] update elastic stack version for testing 7.15.1-a28dd8b0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#757 [automation] update elastic stack version for testing 7.16.0-76e5f71e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#758 [automation] update elastic stack version for testing 7.15.1-3517e2e9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#761 [automation] update elastic stack version for testing 7.15.1-c5b3409f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#764 [automation] update elastic stack version for testing 7.15.1-3e6b9a63
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#767 [automation] update elastic stack version for testing 7.15.1-3ad93496
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#776 [automation] update elastic stack version for testing 7.15.1-92709ecc
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#777 [automation] update elastic stack version for testing 8.0.0-cf8e5c68
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#782 [automation] update elastic stack version for testing 7.15.1-62be82d0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#780 [automation] update elastic stack version for testing 8.0.0-0da7fd6d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#771 Bump version to 7.15.2
  main.go
Labels: Team:Elastic-Agent-Control-Plane

#793 [automation] update elastic stack version for testing 7.16.0-738085ba
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#794 [automation] update elastic stack version for testing 7.15.2-a7c8de5f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#797 [automation] update elastic stack version for testing 8.0.0-2f347a19
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#799 Change agentId field to a value that elastic will map.
  cmd/fleet/handleAck.go
  cmd/fleet/handleArtifacts.go
  cmd/fleet/handleCheckin.go
Labels: bug, backport

#796 Add action_response field into .fleet-actions-results
  cmd/fleet/handleAck.go
  cmd/fleet/schema.go
  internal/pkg/es/mapping.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: enhancement, Team:Elastic-Agent, backport-skip, backport-v7.16.0

#814 Switch to the new _fleet/_fleet_search and _fleet/_fleet_msearch Elasticsearch Fleet APIs, remove holes detection and refreshes
  internal/pkg/bulk/block.go
  internal/pkg/bulk/engine.go
  internal/pkg/bulk/opSearch.go
  internal/pkg/bulk/opt.go
  internal/pkg/bulk/queue.go
  internal/pkg/dl/actions.go
  internal/pkg/dl/actions_integration_test.go
  internal/pkg/dl/search.go
  internal/pkg/es/fleet_msearch.go
  internal/pkg/es/fleet_search.go
  internal/pkg/es/holes.go
  internal/pkg/es/holes_test.go
  internal/pkg/es/refresh.go
  internal/pkg/monitor/monitor.go
  internal/pkg/sqn/sqn.go
Labels: enhancement, Team:Elastic-Agent, Team:Fleet, backport-skip
