Repository elastic/fleet-server, pull requests merged in 2021-02, with the labels that each got.

#78 Add .exe extension to fleet-server windows artifacts.
  Makefile
Labels: Team:Agent

#79 Cherry-pick #78 to 7.x: Add .exe extension to fleet-server windows artifacts.
  Makefile
Labels: Team:Agent, [zube]: In Review, backport

#81 Cherry-pick #80 to 7.x: Fix permissions on dependencies-report script
  dev-tools/dependencies-report
Labels: backport, review

#85 [Backport 7.x]: Reduce actions fetching interval if the full page of action documents was fetched
  internal/pkg/dl/actions.go
  internal/pkg/model/schema.go
  internal/pkg/monitor/monitor.go
  model/schema.json
Labels: backport

#88 [Fleet] Update how to run with Kibana instructions
  README.md
Labels: documentation

#87 Flatten .fleet-actions-results schema
  cmd/fleet/handleAck.go
  cmd/fleet/schema.go
  internal/pkg/es/mapping.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: enhancement

#89 [Backport 7.x] Flatten .fleet-actions-results schema
  cmd/fleet/handleAck.go
  cmd/fleet/schema.go
  internal/pkg/es/mapping.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: backport

#92 Change default bind port from 8000 to 8220
  internal/pkg/config/config_test.go
  internal/pkg/config/input.go
Labels: breaking change

#97 Bump version to 7.13.
  main.go
Labels: Team:Agent

#98 Add ssl configuration to fleet server http.
  cmd/fleet/server.go
  cmd/fleet/server_integration_test.go
  internal/pkg/config/input.go
Labels: Team:Agent

#100 Cherry-pick #98 to 7.x: Add ssl configuration to fleet server http.
  cmd/fleet/server.go
  cmd/fleet/server_integration_test.go
  internal/pkg/config/input.go
Labels: Team:Agent, [zube]: In Review, backport

#103 Align output key permissions with 7.12 Kibana
  cmd/fleet/schema.go
Labels: bug

#106 Upgrade to Go 1.15
  .go-version
  go.mod
Labels: backport

#107 [Backport 7.x] Align permission keys with Kibana 7.12
  cmd/fleet/schema.go
Labels: backport
