Repository elastic/fleet-server, pull requests merged in 2021-07, with the labels that each got.

#507 [automation] update elastic stack version for testing 8.0.0-abbf7c2f
  dev-tools/integration/.env
Labels: automation, dependency

#508 [automation] update elastic stack version for testing 7.14.0-45f71c2c
  dev-tools/integration/.env
Labels: automation, dependency

#511 Enable http2 in Fleet Server.
  cmd/fleet/server.go
Labels: enhancement, v7.14.0, v7.15.0

#513 Update mergify for 7.15
  .mergify.yml
Labels: Team:Agent

#514 Cherry-pick #491 to 7.14: Streamline proxy settings with Beats/Agent
  internal/pkg/config/output.go
  internal/pkg/config/output_test.go
Labels: backport, review

#515 Cherry-pick #511 to 7.14: Enable http2 in Fleet Server.
  cmd/fleet/server.go
Labels: backport, review

#516 [automation] update elastic stack version for testing 8.0.0-f06d44d4
  dev-tools/integration/.env
Labels: automation, dependency

#518 [automation] update elastic stack version for testing 7.14.0-e1afed34
  dev-tools/integration/.env
Labels: automation, dependency

#517 [automation] update elastic stack version for testing 8.0.0-08d745df
  dev-tools/integration/.env
Labels: automation, dependency

#520 Bump version to 7.13.4
  main.go
Labels: Team:Agent

#523 Policy changes can be dropped during policy rollouts to large number …
  cmd/fleet/server.go
  internal/pkg/monitor/subscription_monitor.go
  internal/pkg/policy/monitor.go
Labels: bug, v7.14.0, v7.15.0

#527 Modify hard connection limiter to Close connection on max instead of block.
  NOTICE.txt
  cmd/fleet/server.go
  go.mod
  internal/pkg/limit/listener.go
  internal/pkg/logger/ecs.go
Labels: bug, v7.14.0, v7.15.0

#530 Bump to 7.13.5.
  main.go
Labels: Team:Agent

#538 Revert "Bump to 7.13.5. (#530)"
  main.go
Labels: Team:Agent

#509 [automation] update elastic stack version for testing 7.13.3-dbdefa2a
  dev-tools/integration/.env
Labels: automation, dependency

#541 [automation] update elastic stack version for testing 8.0.0-c2dc4be4
  dev-tools/integration/.env
Labels: automation, dependency

#540 [automation] update elastic stack version for testing 7.14.0-6fb865c2
  dev-tools/integration/.env
Labels: automation, dependency

#553 [automation] update elastic stack version for testing 8.0.0-2f008f4a
  dev-tools/integration/.env
Labels: automation, dependency

#554 [automation] update elastic stack version for testing 7.14.0-c78a4632
  dev-tools/integration/.env
Labels: automation, dependency

#557 [automation] update elastic stack version for testing 7.15.0-588e7872
  dev-tools/integration/.env
Labels: automation, dependency

#556 [automation] update elastic stack version for testing 8.0.0-52a5431f
  dev-tools/integration/.env
Labels: automation, dependency

#558 [automation] update elastic stack version for testing 7.14.0-11e92b49
  dev-tools/integration/.env
Labels: automation, dependency

#560 [automation] update elastic stack version for testing 8.0.0-8ecdc116
  dev-tools/integration/.env
Labels: automation, dependency

#561 [automation] update elastic stack version for testing 7.15.0-f74484b5
  dev-tools/integration/.env
Labels: automation, dependency

#562 [automation] update elastic stack version for testing 7.14.0-02415b60
  dev-tools/integration/.env
Labels: automation, dependency

#559 Accept version qualifier
  Makefile
Labels: bug

#555 refactor rollout to be more deterministic
  internal/pkg/policy/monitor.go
  internal/pkg/policy/sub.go
  internal/pkg/policy/sub_test.go
Labels: enhancement, v7.15.0

#565 [automation] update elastic stack version for testing 8.0.0-61e18b20
  dev-tools/integration/.env
Labels: automation, dependency

#566 [automation] update elastic stack version for testing 7.14.0-de591ade
  dev-tools/integration/.env
Labels: automation, dependency

#567 [automation] update elastic stack version for testing 7.15.0-876ab971
  dev-tools/integration/.env
Labels: automation, dependency

#289 Update README.md
  README.md
Labels: Team:Agent, backport, v7.13.0, v7.14.0, v8.0.0

#572 [automation] update elastic stack version for testing 8.0.0-3e3da54e
  dev-tools/integration/.env
Labels: automation, dependency

#573 [automation] update elastic stack version for testing 7.15.0-af619a87
  dev-tools/integration/.env
Labels: automation, dependency

#539 Bump 7.13.5
  main.go
Labels: Team:Agent

#578 [automation] update elastic stack version for testing 7.15.0-c23a5439
  dev-tools/integration/.env
Labels: automation, dependency

#577 [automation] update elastic stack version for testing 7.14.0-cff72e71
  dev-tools/integration/.env
Labels: automation, dependency

#576 [automation] update elastic stack version for testing 8.0.0-1e9bea0f
  dev-tools/integration/.env
Labels: automation, dependency

#575 Add action timeout
  cmd/fleet/handleCheckin.go
  cmd/fleet/schema.go
  internal/pkg/es/mapping.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: 7.15-candidate, enhancement, v7.15.0

#580 [automation] update elastic stack version for testing 7.15.0-192e1003
  dev-tools/integration/.env
Labels: automation, dependency

#581 [automation] update elastic stack version for testing 8.0.0-a6334483
  dev-tools/integration/.env
Labels: automation, dependency

#582 [automation] update elastic stack version for testing 7.14.0-803ff817
  dev-tools/integration/.env
Labels: automation, dependency

#583 [automation] update elastic stack version for testing 8.0.0-1aed0c4f
  dev-tools/integration/.env
Labels: automation, dependency

#584 [automation] update elastic stack version for testing 7.15.0-5e783247
  dev-tools/integration/.env
Labels: automation, dependency

#587 [automation] update elastic stack version for testing 7.15.0-514bcfaf
  dev-tools/integration/.env
Labels: automation, dependency

#585 [automation] update elastic stack version for testing 8.0.0-cdc598b1
  dev-tools/integration/.env
Labels: automation, dependency

#586 [automation] update elastic stack version for testing 7.14.0-0ce5c542
  dev-tools/integration/.env
Labels: automation, dependency

#589 [automation] update elastic stack version for testing 7.15.0-6e66e5d1
  dev-tools/integration/.env
Labels: automation, dependency

#590 [automation] update elastic stack version for testing 7.14.0-de25a427
  dev-tools/integration/.env
Labels: automation, dependency

#592 Updates elastic agent client dependency
  NOTICE.txt
  go.mod
  go.sum
Labels: bug, v7.14.0, v7.15.0

#596 [automation] update elastic stack version for testing 8.0.0-571dad33
  dev-tools/integration/.env
Labels: automation, dependency

#597 [automation] update elastic stack version for testing 7.15.0-bd471fd6
  dev-tools/integration/.env
Labels: automation, dependency

#598 [automation] update elastic stack version for testing 7.14.0-cd696777
  dev-tools/integration/.env
Labels: automation, dependency

#599 [automation] update elastic stack version for testing 8.0.0-ae1e1c3b
  dev-tools/integration/.env
Labels: automation, dependency

#600 [automation] update elastic stack version for testing 7.15.0-2cefb6a4
  dev-tools/integration/.env
Labels: automation, dependency

#601 [automation] update elastic stack version for testing 7.14.0-9fdd79d4
  dev-tools/integration/.env
Labels: automation, dependency

#603 [automation] update elastic stack version for testing 8.0.0-cf3e6139
  dev-tools/integration/.env
Labels: automation, dependency

#604 [automation] update elastic stack version for testing 7.14.0-56a8365b
  dev-tools/integration/.env
Labels: automation, dependency
