Repository elastic/fleet-server, pull requests merged in 2021-05, with the labels that each got.

#316 [automation] update elastic stack version for testing 7.14.0-83b532ee
  dev-tools/integration/.env
Labels: automation, dependency

#318 [automation] update elastic stack version for testing 8.0.0-6babd951
  dev-tools/integration/.env
Labels: automation, dependency

#317 [automation] update elastic stack version for testing 7.13.0-b1b3acd6
  dev-tools/integration/.env
Labels: automation, dependency

#320 [automation] update elastic stack version for testing 8.0.0-def4e64e
  dev-tools/integration/.env
Labels: automation, dependency

#322 [automation] update elastic stack version for testing 7.13.0-809d7988
  dev-tools/integration/.env
Labels: automation, dependency

#321 [automation] update elastic stack version for testing 7.14.0-90e98b59
  dev-tools/integration/.env
Labels: automation, dependency

#324 Add error response to be JSON
  cmd/fleet/error.go
  cmd/fleet/handleAck.go
  cmd/fleet/handleArtifacts.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/metrics.go
  cmd/fleet/server_integration_test.go
Labels: Team:Agent, v7.13.0, v7.14.0

#328 [automation] update elastic stack version for testing 7.13.0-e9675cbf
  dev-tools/integration/.env
Labels: automation, dependency

#327 [automation] update elastic stack version for testing 8.0.0-3194f3ba
  dev-tools/integration/.env
Labels: automation, dependency

#330 [automation] update elastic stack version for testing 7.14.0-5b4d7537
  dev-tools/integration/.env
Labels: automation, dependency

#332 [automation] update elastic stack version for testing 8.0.0-cbe7788c
  dev-tools/integration/.env
Labels: automation, dependency

#331 [automation] update elastic stack version for testing 7.13.0-683cb8f3
  dev-tools/integration/.env
Labels: automation, dependency

#334 [automation] update elastic stack version for testing 7.14.0-8ba10577
  dev-tools/integration/.env
Labels: automation, dependency

#333 [automation] update elastic stack version for testing 8.0.0-ee8c8ba6
  dev-tools/integration/.env
Labels: automation, dependency

#335 [automation] update elastic stack version for testing 7.13.0-299fd1b5
  dev-tools/integration/.env
Labels: automation, dependency

#337 [automation] update elastic stack version for testing 7.14.0-7d5ea6dc
  dev-tools/integration/.env
Labels: automation, dependency

#338 [automation] update elastic stack version for testing 7.13.0-4c96d7bf
  dev-tools/integration/.env
Labels: automation, dependency

#339 [automation] update elastic stack version for testing 7.14.0-e8048b9e
  dev-tools/integration/.env
Labels: automation, dependency

#346 fix: use the right Go version in the CI
  .ci/Jenkinsfile
  Makefile
  dev-tools/common.bash
Labels: Team:Automation

#350 [automation] update elastic stack version for testing 7.13.0-6647b45b
  dev-tools/integration/.env
Labels: automation, dependency

#348 Fix the comparison between a MaxUint32 and the len of the slice
  internal/pkg/bulk/opMulti.go
Labels: Team:Agent, backport, v7.13.0, v7.14.0

#354 [automation] update elastic stack version for testing 7.13.0-4317ae2c
  dev-tools/integration/.env
Labels: automation, dependency

#355 [automation] update elastic stack version for testing 7.14.0-c3a960d1
  dev-tools/integration/.env
Labels: automation, dependency

#360 Remove the remnants of fleet indices bootstrapping for the integration tests
  Makefile
  dev-tools/integration/main.go
  internal/pkg/testing/esutil/bootstrap.go
Labels: Team:Agent, candidate-7.14, cleanup, v7.14.0

#361 Conform error and hash fields to ECS.
  cmd/fleet/handleCheckin.go
  internal/pkg/logger/logger.go
Labels: bug, v7.13.0, v7.14.0

#365 Fix issue with config reloading
  cmd/fleet/main.go
  fleet-server.yml
Labels: Team:Agent, v7.13.0, v7.14.0

#369 [automation] update elastic stack version for testing 7.14.0-c4ef352d
  dev-tools/integration/.env
Labels: automation, dependency

#368 [automation] update elastic stack version for testing 8.0.0-bd957996
  dev-tools/integration/.env
Labels: automation, dependency

#370 [automation] update elastic stack version for testing 7.13.0-6a007525
  dev-tools/integration/.env
Labels: automation, dependency

#373 [automation] update elastic stack version for testing 8.0.0-cd20b01b
  dev-tools/integration/.env
Labels: automation, dependency

#372 [automation] update elastic stack version for testing 7.14.0-406b0128
  dev-tools/integration/.env
Labels: automation, dependency

#374 [automation] update elastic stack version for testing 7.13.0-a26c8524
  dev-tools/integration/.env
Labels: automation, dependency

#375 Log version and commit at boot
  Makefile
  cmd/fleet/main.go
  internal/pkg/logger/logger.go
  main.go
Labels: enhancement, v7.13.0, v7.14.0

#377 [automation] update elastic stack version for testing 7.14.0-b278d172
  dev-tools/integration/.env
Labels: automation, dependency

#378 [automation] update elastic stack version for testing 8.0.0-b5a373f0
  dev-tools/integration/.env
Labels: automation, dependency

#379 [automation] update elastic stack version for testing 7.13.0-bdae1adb
  dev-tools/integration/.env
Labels: automation, dependency

#381 Send owner: true on API call to invalid API keys.
  internal/pkg/apikey/invalidate.go
Labels: Team:Agent, v7.13.0, v7.14.0

#384 [automation] update elastic stack version for testing 7.14.0-a9c3399b
  dev-tools/integration/.env
Labels: automation, dependency

#385 [automation] update elastic stack version for testing 7.13.0-878a5a45
  dev-tools/integration/.env
Labels: automation, dependency

#386 [automation] update elastic stack version for testing 8.0.0-753d8b9f
  dev-tools/integration/.env
Labels: automation, dependency

#388 [automation] update elastic stack version for testing 8.0.0-8c8922fb
  dev-tools/integration/.env
Labels: automation, dependency

#389 [automation] update elastic stack version for testing 7.14.0-113d5d66
  dev-tools/integration/.env
Labels: automation, dependency

#390 [automation] update elastic stack version for testing 7.13.0-d325823f
  dev-tools/integration/.env
Labels: automation, dependency

#392 [automation] update elastic stack version for testing 7.13.0-b10ff4f4
  dev-tools/integration/.env
Labels: automation, dependency

#393 [automation] update elastic stack version for testing 8.0.0-394043ad
  dev-tools/integration/.env
Labels: automation, dependency

#387 Backport commit logging at boot time
  Makefile
  cmd/fleet/main.go
  internal/pkg/logger/logger.go
  main.go
Labels: backport

#394 Bump to 7.13.1
  main.go
Labels: Team:Agent

#395 [automation] update elastic stack version for testing 7.14.0-9eca24b7
  dev-tools/integration/.env
Labels: automation, dependency

#396 [automation] update elastic stack version for testing 8.0.0-5197c308
  dev-tools/integration/.env
Labels: automation, dependency

#398 [automation] update elastic stack version for testing 7.14.0-f385fee6
  dev-tools/integration/.env
Labels: automation, dependency

#399 [automation] update elastic stack version for testing 7.13.1-66aca119
  dev-tools/integration/.env
Labels: automation, dependency

#402 Add context to errors for better visibility in logs. Add http access …
  cmd/fleet/auth.go
  cmd/fleet/error.go
  cmd/fleet/handleAck.go
  cmd/fleet/handleArtifacts.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/handleStatus.go
  cmd/fleet/metrics.go
  cmd/fleet/router.go
  cmd/fleet/schema.go
  internal/pkg/action/dispatcher.go
  internal/pkg/apikey/auth.go
  internal/pkg/apikey/invalidate.go
  internal/pkg/logger/ecs.go
  internal/pkg/logger/http.go
Labels: enhancement, v7.14.0

#404 [automation] update elastic stack version for testing 8.0.0-3dd1a25d
  dev-tools/integration/.env
Labels: automation, dependency

#406 [automation] update elastic stack version for testing 7.14.0-d593413f
  dev-tools/integration/.env
Labels: automation, dependency

#405 [automation] update elastic stack version for testing 7.13.1-b3918c55
  dev-tools/integration/.env
Labels: automation, dependency

#409 [automation] update elastic stack version for testing 7.14.0-62d7f45e
  dev-tools/integration/.env
Labels: automation, dependency

#410 [automation] update elastic stack version for testing 7.13.1-1ba26435
  dev-tools/integration/.env
Labels: automation, dependency

#407 Add log message to diag auth latency. Replace with metrics on auth ro…
  cmd/fleet/auth.go
Labels: enhancement, v7.14.0
