Repository elastic/fleet-server, pull requests merged in 2021-08, with the labels that each got.

#606 [automation] update elastic stack version for testing 8.0.0-4631fb1e
  dev-tools/integration/.env
Labels: automation, dependency

#607 [automation] update elastic stack version for testing 7.14.0-8d3ee29d
  dev-tools/integration/.env
Labels: automation, dependency

#610 Improve version checking for 8.0.0-alpha1
  cmd/fleet/userAgent.go
  cmd/fleet/userAgent_test.go
  internal/pkg/ver/check.go
  internal/pkg/ver/check_test.go
Labels: Team:Agent, v7.15.0

#612 [automation] update elastic stack version for testing 8.0.0-93ecf1d0
  dev-tools/integration/.env
Labels: automation, dependency

#613 [automation] update elastic stack version for testing 7.14.0-28f3035b
  dev-tools/integration/.env
Labels: automation, dependency

#605 Bump version to 7.14.1
  main.go
Labels: Team:Agent

#609 Populate agent.id field in .fleet-agents index
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/userAgent.go
  cmd/fleet/userAgent_test.go
  internal/pkg/checkin/bulk.go
  internal/pkg/checkin/bulk_test.go
  internal/pkg/dl/constants.go
Labels: Team:Agent, Team:Fleet, enhancement, v7.15.0, v7.16.0

#615 [automation] update elastic stack version for testing 8.0.0-0c340354
  dev-tools/integration/.env
Labels: automation, dependency

#616 [automation] update elastic stack version for testing 7.14.0-1738ccc6
  dev-tools/integration/.env
Labels: automation, dependency

#618 [automation] update elastic stack version for testing 8.0.0-4c35f443
  dev-tools/integration/.env
Labels: automation, dependency

#620 Add additional diagnostic logging to trace policy assignment issues.
  cmd/fleet/handleCheckin.go
  cmd/fleet/main.go
  internal/pkg/coordinator/monitor.go
Labels: enhancement, v7.15.0

#622 [automation] update elastic stack version for testing 8.0.0-e8455215
  dev-tools/integration/.env
Labels: automation, dependency

#623 [automation] update elastic stack version for testing 7.14.1-22366df8
  dev-tools/integration/.env
Labels: automation, dependency

#624 Additional logs to track policy change.
  cmd/fleet/handleAck.go
  cmd/fleet/handleCheckin.go
Labels: enhancement, v7.15.0

#627 [automation] update elastic stack version for testing 7.14.1-8dd23e93
  dev-tools/integration/.env
Labels: automation, dependency

#628 [automation] update elastic stack version for testing 7.14.1-899a999b
  dev-tools/integration/.env
Labels: automation, dependency

#630 [automation] update elastic stack version for testing 7.15.0-83f2fe8a
  dev-tools/integration/.env
Labels: automation, dependency

#629 [automation] update elastic stack version for testing 7.14.1-a5e22cba
  dev-tools/integration/.env
Labels: automation, dependency

#631 [automation] update elastic stack version for testing 7.15.0-af472020
  dev-tools/integration/.env
Labels: automation, dependency

#632 [automation] update elastic stack version for testing 7.14.1-5a4d121c
  dev-tools/integration/.env
Labels: automation, dependency

#635 [automation] update elastic stack version for testing 7.15.0-ba42231a
  dev-tools/integration/.env
Labels: automation, dependency

#634 [automation] update elastic stack version for testing 7.14.1-3af02427
  dev-tools/integration/.env
Labels: automation, dependency

#637 [automation] update elastic stack version for testing 8.0.0-2e89a578
  dev-tools/integration/.env
Labels: automation, dependency

#639 [automation] update elastic stack version for testing 8.0.0-7e122dd9
  dev-tools/integration/.env
Labels: automation, dependency

#641 [automation] update elastic stack version for testing 7.15.0-4b8a78a4
  dev-tools/integration/.env
Labels: automation, dependency

#640 [automation] update elastic stack version for testing 7.14.1-904a8260
  dev-tools/integration/.env
Labels: automation, dependency

#642 Bump to 7.16.
  main.go
Labels: Team:Agent

#643 Update mergify for 7.15 release.
  .mergify.yml
Labels: Team:Agent

#645 [automation] update elastic stack version for testing 8.0.0-fa246295
  dev-tools/integration/.env
Labels: automation, dependency

#646 [automation] update elastic stack version for testing 7.14.1-a6cb01c7
  dev-tools/integration/.env
Labels: automation, dependency

#647 [automation] update elastic stack version for testing 7.16.0-ab6de48d
  dev-tools/integration/.env
Labels: automation, dependency

#649 [automation] update elastic stack version for testing 7.15.0-e06b4078
  dev-tools/integration/.env
Labels: automation, dependency

#648 [automation] update elastic stack version for testing 8.0.0-8ac8c039
  dev-tools/integration/.env
Labels: automation, dependency

#651 [automation] update elastic stack version for testing 8.0.0-56a61c29
  dev-tools/integration/.env
Labels: automation, dependency

#652 [automation] update elastic stack version for testing 7.15.0-a7c04a10
  dev-tools/integration/.env
Labels: automation, dependency

#653 [automation] update elastic stack version for testing 7.16.0-2d73c7e8
  dev-tools/integration/.env
Labels: automation, dependency

#656 [automation] update elastic stack version for testing 7.16.0-c3b80e7b
  dev-tools/integration/.env
Labels: automation, dependency

#655 [automation] update elastic stack version for testing 7.15.0-ab91276c
  dev-tools/integration/.env
Labels: automation, dependency

#659 [automation] update elastic stack version for testing 7.15.0-b20b12b2
  dev-tools/integration/.env
Labels: automation, dependency

#657 [automation] update elastic stack version for testing 8.0.0-126d5980
  dev-tools/integration/.env
Labels: automation, dependency

#658 [automation] update elastic stack version for testing 7.16.0-13c65289
  dev-tools/integration/.env
Labels: automation, dependency

#669 [automation] update elastic stack version for testing 7.16.0-d17acf1e
  dev-tools/integration/.env
Labels: automation, dependency

#670 [automation] update elastic stack version for testing 8.0.0-1efff7fc
  dev-tools/integration/.env
Labels: automation, dependency

#671 [automation] update elastic stack version for testing 7.15.0-0211404a
  dev-tools/integration/.env
Labels: automation, dependency

#676 [automation] update elastic stack version for testing 7.16.0-978c8c33
  dev-tools/integration/.env
Labels: automation, dependency

#675 [automation] update elastic stack version for testing 8.0.0-78724554
  dev-tools/integration/.env
Labels: automation, dependency

#677 [automation] update elastic stack version for testing 7.15.0-1649f9c1
  dev-tools/integration/.env
Labels: automation, dependency

#665 Add index refresh call after fetch if the list of hits has holes
  internal/pkg/monitor/monitor.go
  internal/pkg/monitor/monitor_test.go
Labels: enhancement, Team:Agent, v7.16.0, v7.15.0

#683 Fix panic caused by Agent check-in when Fleet Server is upgraded from 7.14.0 previous
  cmd/fleet/handleCheckin.go
Labels: v7.16.0, v7.15.0
