Repository elastic/fleet-server, pull requests merged in 2021-01, with the labels that each got.

#62 [Fleet] Fix api key format for agent policy
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  internal/pkg/apikey/apikey.go
Labels: Team:Ingest Management

#61 Fix new agent sequence number
  cmd/fleet/handleEnroll.go
Labels: bug

#63 Add notice.txt generation.
  .gitignore
  Makefile
  NOTICE.txt
  dev-tools/notice/NOTICE.txt.tmpl
  dev-tools/notice/overrides.json
  dev-tools/notice/rules.json
  go.sum
Labels: Team:Ingest Management

#64 Add release/snapshot building
  .go-version
  Makefile
  cmd/fleet/main.go
  dev-tools/common.bash
  dev-tools/dependencies-report
  dev-tools/integration/.env
  dev-tools/integration/docker-compose.yml
  dev-tools/notice/dependencies.csv.tmpl
  dev-tools/package/Dockerfile
  dev-tools/package/docker-compose.yml
  dev-tools/run_with_go_ver
  go.sum
  main.go
Labels: Team:Ingest Management

#66 Add cherrypick_pr dev-tools helper.
  dev-tools/cherrypick_pr
Labels: Team:Ingest Management

#67 Cherry-pick #66 to 7.x: Add cherrypick_pr dev-tools helper.
  dev-tools/cherrypick_pr
Labels: Team:Ingest Management, [zube]: In Review, backport

#69 Set version to 7.12.0.
  main.go
Labels: Team:Ingest Management

#68 Make Fleet Server components resilient if the indices do not exist
  cmd/fleet/main.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/esboot/bootstrap.go
  internal/pkg/migrate/migrate.go
  internal/pkg/monitor/monitor.go
  internal/pkg/policy/monitor.go
Labels: enhancement

#70 Hide old bootstrap logic behind FLEET_ES_BOOT environment variable
  cmd/fleet/main.go
  internal/pkg/esboot/bootstrap.go
Labels: enhancement

#73 Rename action input_id to input_type
  cmd/fleet/handleCheckin.go
  cmd/fleet/schema.go
  internal/pkg/es/mapping.go
  internal/pkg/model/schema.go
  internal/pkg/testing/actions.go
  model/schema.json
Labels: breaking change

#71 Add communication to Elastic Agent
  .gitignore
  NOTICE.txt
  cmd/fleet/main.go
  cmd/fleet/server.go
  cmd/fleet/server_integration_test.go
  dev-tools/integration/wait-for-elasticsearch.sh
  fleet-server.yml
  go.mod
  go.sum
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/config/fleet.go
  internal/pkg/config/input.go
  internal/pkg/config/logging.go
  internal/pkg/config/output.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/logger/logger.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/self.go
  internal/pkg/policy/self_test.go
  internal/pkg/status/reporter.go
  internal/pkg/testing/retry.go
Labels: Team:Ingest Management

#75 Cherry-pick #71 to 7.x: Add communication to Elastic Agent
  .gitignore
  NOTICE.txt
  cmd/fleet/main.go
  cmd/fleet/server.go
  cmd/fleet/server_integration_test.go
  dev-tools/integration/wait-for-elasticsearch.sh
  fleet-server.yml
  go.mod
  go.sum
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/config/fleet.go
  internal/pkg/config/input.go
  internal/pkg/config/logging.go
  internal/pkg/config/output.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/logger/logger.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/self.go
  internal/pkg/policy/self_test.go
  internal/pkg/status/reporter.go
  internal/pkg/testing/retry.go
Labels: Team:Ingest Management, [zube]: In Review, backport

#76 Cherry pick/master to 7.x
  cmd/fleet/handleCheckin.go
  cmd/fleet/main.go
  cmd/fleet/schema.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/es/mapping.go
  internal/pkg/esboot/bootstrap.go
  internal/pkg/migrate/migrate.go
  internal/pkg/model/schema.go
  internal/pkg/monitor/monitor.go
  internal/pkg/policy/monitor.go
  internal/pkg/testing/actions.go
  model/schema.json
Labels: backport
