Repository elastic/fleet-server, pull requests merged in 2021-04, with the labels that each got.

#195 Implement support for API Key metadata
  cmd/fleet/handleEnroll.go
  internal/pkg/apikey/apikey.go
  internal/pkg/apikey/apikey_integration_test.go
  internal/pkg/apikey/apikey_test.go
  internal/pkg/apikey/create.go
  internal/pkg/apikey/get.go
  internal/pkg/apikey/metadata.go
Labels: enhancement

#198 Add user_id to .fleet-actions schema
  internal/pkg/es/mapping.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: enhancement, v7.13.0

#197 Move to less aggressive bulk queue preallocation size by default.
  internal/pkg/bulk/bulk.go
  internal/pkg/bulk/opt.go
Labels: backport, enhancement

#202 Add pretty print logger output under stderr
  internal/pkg/config/logging.go
  internal/pkg/logger/logger.go
Labels: backport, enhancement

#201 Add optional gzip compression support on check-in response.
  cmd/fleet/handleCheckin.go
  internal/pkg/config/config_test.go
  internal/pkg/config/input.go
Labels: backport, enhancement

#203 Bport2
  cmd/fleet/handleCheckin.go
  internal/pkg/bulk/bulk.go
  internal/pkg/bulk/opt.go
  internal/pkg/config/config_test.go
  internal/pkg/config/input.go
  internal/pkg/config/logging.go
  internal/pkg/logger/logger.go
Labels: backport

#204 normalize limits
  cmd/fleet/handleAck.go
  cmd/fleet/handleArtifacts.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/handleStatus.go
  cmd/fleet/main.go
  cmd/fleet/router.go
  cmd/fleet/server.go
  cmd/fleet/server_integration_test.go
  cmd/fleet/server_test.go
  fleet-server.yml
  internal/pkg/cache/cache.go
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/config/input.go
  internal/pkg/config/limits.go
  internal/pkg/config/runtime.go
  internal/pkg/dl/policies.go
  internal/pkg/limit/limiter.go
  internal/pkg/rate/rate.go
Labels: enhancement, v7.13.0

#207 Propagate enrollment_token to agent during bootstrap.
  cmd/fleet/handleEnroll.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/dl/enrollment_api_key.go
  internal/pkg/dl/enrollment_api_key_integration_test.go
  internal/pkg/policy/self.go
  internal/pkg/policy/self_test.go
  internal/pkg/status/reporter.go
Labels: Team:Agent, v7.13.0

#209 Support basic ECS logging fields
  internal/pkg/logger/logger.go
Labels: enhancement, v7.13.0

#213 Structured logger outputs RFC3339 at millisecond resolution in zulu t…
  fleet-server.yml
  internal/pkg/logger/logger.go
Labels: enhancement, v7.13.0

#215 Preprocess policy on new revision to pre-calculate hashes and minimize memory allocations.
  cmd/fleet/bulkCheckin.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleChecking_test.go
  cmd/fleet/schema.go
  internal/pkg/dl/agent.go
  internal/pkg/dl/constants.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/policy/monitor_test.go
  internal/pkg/policy/output_permissions.go
  internal/pkg/policy/parsed_policy.go
  internal/pkg/policy/parsed_policy_test.go
Labels: enhancement, v7.13.0

#219 Add route metrics.
  NOTICE.txt
  cmd/fleet/handleAck.go
  cmd/fleet/handleArtifacts.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/handleStatus.go
  cmd/fleet/metrics.go
  cmd/fleet/server.go
  go.mod
  go.sum
  internal/pkg/policy/monitor.go
Labels: enhancement, v7.13.0

#224 Fix issue with not sending the agents default api_key.
  cmd/fleet/handleCheckin.go
Labels: Team:Agent, bug, v7.13.0

#229 Fix coordinator goroutine tight loop on cancelled context
  internal/pkg/coordinator/monitor.go
Labels: bug, v7.13.0

#233 Bring 7.x readme up to date with master.
  README.md
Labels: backport

#226 Add ability to communicate with elasticsearch using a service token
  NOTICE.txt
  fleet-server.yml
  go.mod
  go.sum
  internal/pkg/config/output.go
Labels: Team:Agent, v7.13.0

#240 Example configuration for minimal RAM.
  example/fleet-server-100.yml
Labels: docs, v7.13.0

#239 Ensure that the connecting Elastic Agent is a supported version.
  NOTICE.txt
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/main.go
  cmd/fleet/metrics.go
  cmd/fleet/server_test.go
  cmd/fleet/userAgent.go
  cmd/fleet/userAgent_test.go
  go.mod
  go.sum
Labels: Team:Agent, v7.13.0

#200 Utilize new ES fleet polling API for global checkpoint monitoring
  cmd/fleet/handleCheckin.go
  cmd/fleet/main.go
  dev-tools/integration/main.go
  internal/pkg/bulk/bulk.go
  internal/pkg/config/config_test.go
  internal/pkg/config/monitor.go
  internal/pkg/config/output.go
  internal/pkg/config/output_test.go
  internal/pkg/coordinator/monitor_integration_test.go
  internal/pkg/es/client.go
  internal/pkg/es/error.go
  internal/pkg/es/fleet_global_checkpoints.go
  internal/pkg/monitor/global_checkpoint.go
  internal/pkg/monitor/mock/monitor.go
  internal/pkg/monitor/monitor.go
  internal/pkg/monitor/monitor_integration_test.go
  internal/pkg/monitor/subscription_monitor.go
  internal/pkg/monitor/subscription_monitor_integration_test.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/policy/monitor_test.go
  internal/pkg/sqn/sqn.go
  internal/pkg/testing/esutil/bootstrap.go
Labels: enhancement, v7.13.0

#247 Update fleet server monitor logging
  internal/pkg/monitor/monitor.go
Labels: enhancement, v7.13.0

#249 Validate Elasticsearch version for compatibility
  cmd/fleet/main.go
  internal/pkg/es/info.go
  internal/pkg/ver/check.go
  internal/pkg/ver/check_test.go
Labels: enhancement, v7.13.0

#255 Add script to avoid race condition on updating policy metadata in age…
  cmd/fleet/handleAck.go
  cmd/fleet/handleAck_test.go
  internal/pkg/bulk/bulk.go
  internal/pkg/bulk/multi.go
  internal/pkg/bulk/opt.go
Labels: bug, v7.13.0

#256 Move runtime configuration so that can be configured via agent.
  cmd/fleet/main.go
  example/fleet-server-100.yml
  fleet-server.yml
  internal/pkg/config/config.go
  internal/pkg/config/input.go
Labels: bug, v7.13.0

#254 Wait on index when polling global checkpoints
  internal/pkg/es/fleet_global_checkpoints.go
  internal/pkg/monitor/global_checkpoint.go
Labels: enhancement, v7.13.0

#262 Bump to 7.14.0
  main.go
Labels: Team:Agent, review

#252 Bump elastic stack version automation
  .ci/bump-stack-version.sh
  .gitignore
  .mergify.yml
Labels: v7.12.0, v7.13.0, v7.14.0

#268 Improve log message about degraded being okay during bootstrap.
  internal/pkg/policy/self.go
  internal/pkg/policy/self_test.go
Labels: Team:Agent, v7.13.0, v7.14.0

#275 bump-stack-version 8.0.0-5ef2ff8e
  dev-tools/integration/.env
Labels: automation, dependency

#276 [mergify]: delete branch related to automation after it gets merged and commit messages
  .ci/bump-stack-version.sh
  .ci/jobs/fleet-server.yml
  .mergify.yml
Labels: Team:Automation, v7.12.0, v7.13.0, v7.14.0

#286 Remove the UUID checks.
  internal/pkg/policy/monitor.go
  internal/pkg/policy/revision.go
Labels: Team:Agent, v7.13.0, v7.14.0

#291 Bump to 7.12.2 from 7.12.1
  main.go
Labels: Team:Agent

#290 Report failure running under Elastic Agent
  cmd/fleet/main.go
  cmd/fleet/metrics.go
Labels: Team:Agent, v7.13.0, v7.14.0

#295 [automation] update elastic stack version for testing 7.13.0-a55594ff
  dev-tools/integration/.env
Labels: automation, dependency

#294 [automation] update elastic stack version for testing 8.0.0-3c585d96
  dev-tools/integration/.env
Labels: automation, dependency

#302 [automation] update elastic stack version for testing 7.13.0-598c2261
  dev-tools/integration/.env
Labels: automation, dependency

#300 [automation] update elastic stack version for testing 8.0.0-4fa04b7f
  dev-tools/integration/.env
Labels: automation, dependency

#301 [automation] update elastic stack version for testing 7.14.0-76235d63
  dev-tools/integration/.env
Labels: automation, dependency

#298 [mergify] change title for the backports
  .mergify.yml
Labels: Team:Automation

#306 Reduce the monitor long poll timeout to 4 minutes by default
  internal/pkg/config/monitor.go
  internal/pkg/monitor/monitor.go
Labels: Team:Agent, candidate-7.14, enhancement, v7.13.0, v7.14.0

#309 [automation] update elastic stack version for testing 8.0.0-dec8157c
  dev-tools/integration/.env
Labels: automation, dependency

#311 [automation] update elastic stack version for testing 7.13.0-8931f4de
  dev-tools/integration/.env
Labels: automation, dependency

#310 [automation] update elastic stack version for testing 7.14.0-c9bfc196
  dev-tools/integration/.env
Labels: automation, dependency

#312 mergify: fix delete_head_branch condition
  .mergify.yml
Labels: Team:Automation, v7.12.0, v7.13.0, v7.14.0
