Repository elastic/fleet-server, pull requests merged in 2021-11, with the labels that each got.

#820 [automation] update elastic stack version for testing 7.16.0-66ccea1a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#822 [automation] update elastic stack version for testing 7.15.2-fecae5f4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#821 [automation] update elastic stack version for testing 8.1.0-43c60a2a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#805 Normalize logging
  cmd/fleet/auth.go
  cmd/fleet/error.go
  cmd/fleet/handleAck.go
  cmd/fleet/handleArtifacts.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/server.go
  cmd/fleet/userAgent.go
  cmd/fleet/userAgent_test.go
  internal/pkg/action/dispatcher.go
  internal/pkg/apikey/get.go
  internal/pkg/config/input.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/coordinator/v0.go
  internal/pkg/es/client.go
  internal/pkg/logger/ecs.go
  internal/pkg/logger/http.go
  internal/pkg/policy/monitor.go
Labels: enhancement, cleanup, backport-skip

#825 [automation] update elastic stack version for testing 7.15.2-5325c15b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#824 [automation] update elastic stack version for testing 8.1.0-2fdb91c4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#830 [automation] update elastic stack version for testing 7.16.0-c5c99751
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#831 [automation] update elastic stack version for testing 7.15.2-54cb1d1b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#829 [automation] update elastic stack version for testing 8.0.0-6b50534b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#835 [automation] update elastic stack version for testing 7.16.0-c51d3b71
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#836 [automation] update elastic stack version for testing 7.15.2-87e1eeab
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#834 [automation] update elastic stack version for testing 8.1.0-96ac1eb1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#833 [automation] update elastic stack version for testing 8.0.0-decb3f1d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#843 [automation] update elastic stack version for testing 7.15.2-e203d324
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#840 [automation] update elastic stack version for testing 7.16.0-68781827
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#842 [automation] update elastic stack version for testing 8.0.0-fc3570a9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#841 [automation] update elastic stack version for testing 8.1.0-f479a40a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#846 [automation] update elastic stack version for testing 7.15.2-616feb9e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#848 [automation] update elastic stack version for testing 7.15.2-dab700a8
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#849 [automation] update elastic stack version for testing 8.0.0-be754c25
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#851 [automation] update elastic stack version for testing 7.16.0-df026734
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#853 [automation] update elastic stack version for testing 7.15.2-f9b0a84b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#852 [automation] update elastic stack version for testing 8.0.0-995d02ee
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#837 Bump version to 7.15.3
  main.go
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#844 Improve some of the log message
  cmd/fleet/handleAck.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/main.go
  cmd/fleet/router.go
  internal/pkg/bulk/helpers.go
  internal/pkg/bulk/opRead.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/monitor/monitor.go
  internal/pkg/policy/monitor.go
  internal/pkg/ver/check.go
Labels: v8.0.0, v7.16.0, backport-v7.16.0, backport-v8.0.0, Team:Elastic-Agent-Control-Plane

#869 [automation] update elastic stack version for testing 7.15.3-dd0b1576
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#866 [automation] update elastic stack version for testing 7.16.0-20fe9209
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#868 [automation] update elastic stack version for testing 8.1.0-49c447b0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#867 [automation] update elastic stack version for testing 8.0.0-683a0b7d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#871 [automation] update elastic stack version for testing 7.16.0-27f0a6d6
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#873 [automation] update elastic stack version for testing 7.15.3-b30acc1a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#872 [automation] update elastic stack version for testing 8.1.0-e547d04a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#870 [automation] update elastic stack version for testing 8.0.0-31084d02
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#854 [mergify] use backport- labels
  .mergify.yml
Labels: backport-skip

#855 Periodic expired actions cleanup
  cmd/fleet/main.go
  cmd/fleet/userAgent_test.go
  internal/pkg/config/config_test.go
  internal/pkg/config/gc.go
  internal/pkg/config/input.go
  internal/pkg/dl/actions.go
  internal/pkg/dsl/size.go
  internal/pkg/es/error.go
  internal/pkg/gc/actions.go
  internal/pkg/gc/actions_integration_test.go
  internal/pkg/gc/schedules.go
  internal/pkg/scheduler/scheduler.go
  internal/pkg/scheduler/scheduler_test.go
  internal/pkg/testing/actions.go
  internal/pkg/wait/wait.go
Labels: enhancement, Team:Elastic-Agent, v8.0.0, backport-v8.0.0

#879 [automation] update elastic stack version for testing 7.15.3-781c0f9a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#877 [automation] update elastic stack version for testing 8.1.0-14029b3d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#878 [automation] update elastic stack version for testing 8.0.0-0357b4f0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#876 Fix: Fleet Server crashes on expired actions search
  internal/pkg/dl/actions.go
Labels: bug, v8.0.0, backport-v8.0.0

#885 [automation] update elastic stack version for testing 7.16.0-1af90c36
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#886 [automation] update elastic stack version for testing 7.15.3-a6aad1c6
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#887 [automation] update elastic stack version for testing 8.1.0-a31f3b73
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#806 Ensure ECS log compliance
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/logger/logger.go
Labels: bug, Feature:fleet-server, v8.0.0, backport-v8.0.0, Team:Elastic-Agent-Control-Plane

#882 Add integration test coverage for actions cleanup with non-existing index
  internal/pkg/gc/actions_integration_test.go
Labels: cleanup, v8.0.0, backport-v8.0.0

#892 [automation] update elastic stack version for testing 7.16.0-705b02ff
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#893 [automation] update elastic stack version for testing 7.15.3-a2dc0d3c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#894 [automation] update elastic stack version for testing 8.1.0-11229697
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#891 [automation] update elastic stack version for testing 8.0.0-83e38099
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#832 Update go-elasticsearch to the latest 7.15.1 version
  NOTICE.txt
  go.mod
  go.sum
Labels: cleanup, backport-v8.0.0

#884 API keys cleanup
  Makefile
  cmd/fleet/handleAck.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleChecking_test.go
  internal/pkg/cache/cache.go
  internal/pkg/dl/constants.go
  internal/pkg/es/mapping.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: enhancement, v8.0.0, backport-v8.0.0

#890 Improve the cleanup code on enrollment handling error
  cmd/fleet/handleEnroll.go
  cmd/fleet/main.go
  cmd/fleet/router.go
  cmd/fleet/server_test.go
  internal/pkg/rollback/rollback.go
Labels: enhancement, cleanup, v8.0.0, backport-v8.0.0

#899 [automation] update elastic stack version for testing 8.1.0-875ad7e2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#900 [automation] update elastic stack version for testing 7.16.0-3a1031bc
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#901 [automation] update elastic stack version for testing 7.15.3-d16f4bc8
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#902 [automation] update elastic stack version for testing 8.0.0-1160a953
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#874 [mergify] report open backported PRs once a week
  .mergify.yml
Labels: backport-skip

#904 [automation] update elastic stack version for testing 7.15.3-2ab3d0ac
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#898 instrumentation: Add initial APM tracing
  NOTICE.txt
  cmd/fleet/main.go
  cmd/fleet/router.go
  cmd/fleet/server.go
  cmd/fleet/server_integration_test.go
  cmd/fleet/server_test.go
  fleet-server.yml
  go.mod
  go.sum
  internal/pkg/config/input.go
  internal/pkg/config/instrumentation.go
  internal/pkg/es/client.go
Labels: v8.0.0, backport-v8.0.0

#909 [automation] update elastic stack version for testing 7.15.3-4c145d2b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#908 [automation] update elastic stack version for testing 8.1.0-14a0128f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#880 Multiple endpoints
  cmd/fleet/server.go
  internal/pkg/config/config_test.go
  internal/pkg/config/input.go
Labels: bug, backport-v7.16.0, backport-v8.0.0

#906 Improve expired actions cleanup, use _delete_by_query instead
  cmd/fleet/main.go
  internal/pkg/config/gc.go
  internal/pkg/dl/actions.go
  internal/pkg/es/result.go
  internal/pkg/gc/actions.go
  internal/pkg/gc/actions_integration_test.go
  internal/pkg/gc/actions_test.go
  internal/pkg/gc/schedules.go
Labels: enhancement, cleanup, 8.0-candidate, backport-v8.0.0

#912 [automation] update elastic stack version for testing 7.16.0-8c304116
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#911 [automation] update elastic stack version for testing 7.15.3-c1618cb4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#914 [automation] update elastic stack version for testing 8.0.0-28ef013c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#913 [automation] update elastic stack version for testing 8.1.0-d173e6ad
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#917 [automation] update elastic stack version for testing 7.16.0-5227689d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#915 [automation] update elastic stack version for testing 7.15.3-ba00df8f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#916 [automation] update elastic stack version for testing 8.1.0-1c3bdf27
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#918 [automation] update elastic stack version for testing 8.0.0-ca68b68a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#922 [automation] update elastic stack version for testing 7.16.0-58c0cae7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#923 [automation] update elastic stack version for testing 7.15.3-57b973bf
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#921 [automation] update elastic stack version for testing 8.0.0-89da64e1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#920 [automation] update elastic stack version for testing 8.1.0-a48471bd
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#927 [automation] update elastic stack version for testing 7.15.3-e51e78d3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#928 [automation] update elastic stack version for testing 7.16.0-19916e4d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#925 [automation] update elastic stack version for testing 8.0.0-94dc1348
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#926 [automation] update elastic stack version for testing 8.1.0-3307da9c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#932 [automation] update elastic stack version for testing 7.16.0-4a83af8d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#934 [automation] update elastic stack version for testing 7.15.3-c7a19acd
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#931 [automation] update elastic stack version for testing 8.1.0-3e9afa2a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#933 [automation] update elastic stack version for testing 8.0.0-5dc82a0c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#883 Retry reads when ES unavailable
  internal/pkg/coordinator/monitor.go
Labels: bug, v8.0.0, v7.16.0, v7.15.0, backport-v7.16.0, backport-v8.0.0, Team:Elastic-Agent-Control-Plane
