Repository elastic/fleet-server, pull requests merged in 2021-09, with the labels that each got.

#686 [automation] update elastic stack version for testing 7.15.0-caca3588
  dev-tools/integration/.env
Labels: automation, dependency

#687 [automation] update elastic stack version for testing 7.16.0-8a18fe34
  dev-tools/integration/.env
Labels: automation, dependency

#688 Encapsulate the agent new version safe check, full unit test coverage
  cmd/fleet/handleCheckin.go
  internal/pkg/model/ext.go
  internal/pkg/model/ext_test.go
Labels: Team:Agent, cleanup, v7.16.0

#654 Set User-Agent in HTTP requests
  .gitignore
  Makefile
  NOTICE.txt
  cmd/fleet/main.go
  cmd/fleet/metrics.go
  cmd/fleet/server_integration_test.go
  go.mod
  go.sum
  internal/pkg/build/build.go
  internal/pkg/es/client.go
  main.go
Labels: enhancement, Team:Agent, v7.16.0

#692 Fix issues with config reloading
  cmd/fleet/main.go
  cmd/fleet/main_integration_test.go
  internal/pkg/cache/cache.go
  internal/pkg/cache/impl.go
  internal/pkg/cache/impl_integration.go
  internal/pkg/cache/impl_ristretto.go
  internal/pkg/dl/enrollment_api_key.go
  internal/pkg/testing/esutil/index.go
  internal/pkg/testing/suite/suite.go
Labels: Team:Agent, v7.16.0, v7.15.0

#695 [automation] update elastic stack version for testing 8.0.0-467e0885
  dev-tools/integration/.env
Labels: automation, dependency

#696 [automation] update elastic stack version for testing 7.15.0-b8b8307a
  dev-tools/integration/.env
Labels: automation, dependency

#697 [automation] update elastic stack version for testing 7.16.0-a96d8aa5
  dev-tools/integration/.env
Labels: automation, dependency

#681 Add "hole" detection and refresh for the agent actions fetch upon initial check in
  cmd/fleet/handleCheckin.go
  internal/pkg/dl/actions.go
  internal/pkg/es/holes.go
  internal/pkg/es/holes_test.go
  internal/pkg/es/refresh.go
  internal/pkg/monitor/monitor.go
Labels: enhancement, v7.16.0, v7.15.0

#701 [automation] update elastic stack version for testing 7.16.0-468522bc
  dev-tools/integration/.env
Labels: automation, dependency

#700 [automation] update elastic stack version for testing 8.0.0-c0c740b6
  dev-tools/integration/.env
Labels: automation, dependency

#702 [automation] update elastic stack version for testing 7.15.0-f15c4154
  dev-tools/integration/.env
Labels: automation, dependency

#703 [automation] update elastic stack version for testing 7.15.0-4efca5cc
  dev-tools/integration/.env
Labels: automation, dependency

#706 [automation] update elastic stack version for testing 7.16.0-fbd5fab2
  dev-tools/integration/.env
Labels: automation, dependency

#705 [automation] update elastic stack version for testing 8.0.0-6b488890
  dev-tools/integration/.env
Labels: automation, dependency

#707 [automation] update elastic stack version for testing 7.15.0-a59055d8
  dev-tools/integration/.env
Labels: automation, dependency

#709 [automation] update elastic stack version for testing 8.0.0-64718381
  dev-tools/integration/.env
Labels: automation, dependency

#710 [automation] update elastic stack version for testing 7.15.0-d48cd6f3
  dev-tools/integration/.env
Labels: automation, dependency

#708 [automation] update elastic stack version for testing 7.16.0-f4fa0a64
  dev-tools/integration/.env
Labels: automation, dependency

#711 [automation] update elastic stack version for testing 7.16.0-b40a7e80
  dev-tools/integration/.env
Labels: automation, dependency

#712 [automation] update elastic stack version for testing 7.15.0-4d52e36a
  dev-tools/integration/.env
Labels: automation, dependency

#716 [automation] update elastic stack version for testing 7.16.0-63cdb007
  dev-tools/integration/.env
Labels: automation, dependency

#715 [automation] update elastic stack version for testing 7.15.0-1bab4292
  dev-tools/integration/.env
Labels: automation, dependency

#714 [automation] update elastic stack version for testing 8.0.0-da75ec54
  dev-tools/integration/.env
Labels: automation, dependency

#717 [automation] update elastic stack version for testing 7.15.0-353cd7d4
  dev-tools/integration/.env
Labels: automation, dependency

#718 [automation] update elastic stack version for testing 7.16.0-8df9bb12
  dev-tools/integration/.env
Labels: automation, dependency

#719 [automation] update elastic stack version for testing 7.15.0-bc82566e
  dev-tools/integration/.env
Labels: automation, dependency

#720 [automation] update elastic stack version for testing 8.0.0-c8bb0791
  dev-tools/integration/.env
Labels: automation, dependency

#721 [automation] update elastic stack version for testing 7.16.0-3f2f8446
  dev-tools/integration/.env
Labels: automation, dependency

#722 [automation] update elastic stack version for testing 7.15.0-5ab1fe99
  dev-tools/integration/.env
Labels: automation, dependency

#726 [automation] update elastic stack version for testing 7.16.0-e2daa6e3
  dev-tools/integration/.env
Labels: automation, dependency

#725 [automation] update elastic stack version for testing 8.0.0-3188f766
  dev-tools/integration/.env
Labels: automation, dependency

#727 [automation] update elastic stack version for testing 7.15.0-28b0107a
  dev-tools/integration/.env
Labels: automation, dependency

#728 [CI] use obltGitHubComments
  .ci/Jenkinsfile
Labels: automation, v7.16.0, v7.15.0

#723 [mergify] notify if no backport labels on the PRs targeting the master branch
  .mergify.yml
Labels: automation

#732 [automation] update elastic stack version for testing 7.16.0-51a7a70c
  dev-tools/integration/.env
Labels: automation, dependency

#731 [automation] update elastic stack version for testing 8.0.0-aa012679
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#733 [automation] update elastic stack version for testing 7.15.1-f9f656c4
  dev-tools/integration/.env
Labels: automation, dependency

#713 Do not require that the default output use the default key in the outputs of policy
  cmd/fleet/handleCheckin.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/policy/monitor_test.go
  internal/pkg/policy/output_permissions.go
  internal/pkg/policy/output_permissions_test.go
  internal/pkg/policy/parsed_policy.go
  internal/pkg/policy/parsed_policy_test.go
Labels: Team:Agent, v7.16.0

#738 [automation] update elastic stack version for testing 7.15.1-de1fe33e
  dev-tools/integration/.env
Labels: automation, dependency

#736 [automation] update elastic stack version for testing 7.16.0-70330f11
  dev-tools/integration/.env
Labels: automation, dependency

#737 [automation] update elastic stack version for testing 8.0.0-61c5a306
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#740 [automation] update elastic stack version for testing 7.16.0-4cbd636a
  dev-tools/integration/.env
Labels: automation, dependency

#739 [automation] update elastic stack version for testing 7.15.1-5f9d0364
  dev-tools/integration/.env
Labels: automation, dependency

#743 [automation] update elastic stack version for testing 8.0.0-9d408327
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#747 [automation] update elastic stack version for testing 7.15.1-56129787
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#748 [automation] update elastic stack version for testing 8.0.0-aef26e82
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#752 [automation] update elastic stack version for testing 7.16.0-f67263fd
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#751 [automation] update elastic stack version for testing 7.15.1-f3d0455b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#750 [automation] update elastic stack version for testing 8.0.0-2f7ca428
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
