Repository elastic/fleet-server, pull requests merged in 2021-06, with the labels that each got.

#413 [automation] update elastic stack version for testing 8.0.0-68ee0bbd
  dev-tools/integration/.env
Labels: automation, dependency

#414 [automation] update elastic stack version for testing 7.14.0-631ae8b8
  dev-tools/integration/.env
Labels: automation, dependency

#415 [automation] update elastic stack version for testing 7.13.1-e4c670b7
  dev-tools/integration/.env
Labels: automation, dependency

#417 [automation] update elastic stack version for testing 7.14.0-bdd01eb6
  dev-tools/integration/.env
Labels: automation, dependency

#418 [automation] update elastic stack version for testing 7.13.1-b438d0e4
  dev-tools/integration/.env
Labels: automation, dependency

#412 Bump version to 7.13.2
  main.go
Labels: Team:Agent

#424 [automation] update elastic stack version for testing 7.13.2-e54b50ef
  dev-tools/integration/.env
Labels: automation, dependency

#423 [automation] update elastic stack version for testing 7.14.0-8590217b
  dev-tools/integration/.env
Labels: automation, dependency

#422 Revert elastic search client to the 7.x series.
  NOTICE.txt
  cmd/fleet/auth.go
  cmd/fleet/handleEnroll.go
  go.mod
  go.sum
  internal/pkg/apikey/auth.go
  internal/pkg/apikey/create.go
  internal/pkg/apikey/get.go
  internal/pkg/apikey/invalidate.go
  internal/pkg/bulk/engine.go
  internal/pkg/bulk/helpers.go
  internal/pkg/bulk/opBulk.go
  internal/pkg/bulk/opRead.go
  internal/pkg/bulk/opSearch.go
  internal/pkg/config/output.go
  internal/pkg/config/output_test.go
  internal/pkg/es/client.go
  internal/pkg/es/delete.go
  internal/pkg/es/fleet_global_checkpoints.go
  internal/pkg/es/info.go
  internal/pkg/monitor/global_checkpoint.go
  internal/pkg/monitor/monitor.go
  internal/pkg/monitor/subscription_monitor.go
  internal/pkg/testing/bulk.go
  internal/pkg/testing/esutil/bootstrap.go
  internal/pkg/testing/esutil/datastream.go
  internal/pkg/testing/esutil/esutil.go
  internal/pkg/testing/esutil/ilm.go
  internal/pkg/testing/esutil/index.go
  internal/pkg/testing/esutil/template.go
  internal/pkg/ver/check.go
Labels: enhancement, v7.14.0

#420 Propagate checkin status to agent record
  cmd/fleet/handleCheckin.go
  cmd/fleet/schema.go
  internal/pkg/checkin/bulk.go
  internal/pkg/checkin/bulk_test.go
  internal/pkg/dl/constants.go
Labels: enhancement, v7.14.0

#428 [automation] update elastic stack version for testing 7.14.0-983e13ea
  dev-tools/integration/.env
Labels: automation, dependency

#429 [automation] update elastic stack version for testing 7.13.2-56fcd1bc
  dev-tools/integration/.env
Labels: automation, dependency

#430 [automation] update elastic stack version for testing 7.14.0-bb1ffc77
  dev-tools/integration/.env
Labels: automation, dependency

#431 [automation] update elastic stack version for testing 7.13.2-f9522f62
  dev-tools/integration/.env
Labels: automation, dependency

#421 Remove zap stub logger bleed through.
  internal/pkg/logger/ecs.go
  internal/pkg/logger/logger.go
  internal/pkg/logger/zapStub.go
Labels: enhancement, v7.14.0

#438 [automation] update elastic stack version for testing 7.13.2-ce511058
  dev-tools/integration/.env
Labels: automation, dependency

#435 Better enroll logging
  cmd/fleet/handleEnroll.go
Labels: enhancement, v7.14.0

#434 Tweak server timeouts. Limit body size to defend malicious agent
  cmd/fleet/error.go
  cmd/fleet/handleAck.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/server.go
  internal/pkg/config/config_test.go
  internal/pkg/config/input.go
  internal/pkg/config/limits.go
Labels: enhancement, v7.14.0

#444 [automation] update elastic stack version for testing 7.13.2-a3fd10d8
  dev-tools/integration/.env
Labels: automation, dependency

#436 Update go-version
  .go-version
  Makefile
  README.md
Labels: Team:Agent, enhancement, v7.14.0

#448 [automation] update elastic stack version for testing 7.14.0-28665d9b
  dev-tools/integration/.env
Labels: automation, dependency

#449 [automation] update elastic stack version for testing 7.13.2-e9f2bb70
  dev-tools/integration/.env
Labels: automation, dependency

#443 Configure cache
  NOTICE.txt
  cmd/fleet/auth.go
  cmd/fleet/handleAck.go
  cmd/fleet/handleArtifacts.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/main.go
  cmd/fleet/server_integration_test.go
  go.mod
  go.sum
  internal/pkg/apikey/apikey_integration_test.go
  internal/pkg/apikey/create.go
  internal/pkg/bulk/opApiKey.go
  internal/pkg/cache/cache.go
  internal/pkg/config/cache.go
  internal/pkg/config/config_test.go
Labels: enhancement, v7.14.0

#452 [automation] update elastic stack version for testing 7.13.2-66efaded
  dev-tools/integration/.env
Labels: automation, dependency

#455 [automation] update elastic stack version for testing 7.13.2-34e8ddd9
  dev-tools/integration/.env
Labels: automation, dependency

#457 Remove indirect build dependency on go-license-detector.
  Makefile
  NOTICE.txt
  dev-tools/dependencies-report
  go.mod
  go.sum
  main.go
Labels: bug, v7.14.0

#461 [automation] update elastic stack version for testing 7.13.2-f55bee50
  dev-tools/integration/.env
Labels: automation, dependency

#463 Policy tests occasionally fail in jenkins. Force init to be determin…
  internal/pkg/policy/monitor.go
  internal/pkg/policy/monitor_test.go
  internal/pkg/policy/self.go
  internal/pkg/policy/self_test.go
Labels: bug, v7.14.0

#467 [automation] update elastic stack version for testing 8.0.0-943ef2c0
  dev-tools/integration/.env
Labels: automation, dependency

#471 [automation] update elastic stack version for testing 7.14.0-52b7d996
  dev-tools/integration/.env
Labels: automation, dependency

#470 [automation] update elastic stack version for testing 8.0.0-49df2653
  dev-tools/integration/.env
Labels: automation, dependency

#475 [automation] update elastic stack version for testing 7.14.0-08bc11a0
  dev-tools/integration/.env
Labels: automation, dependency

#476 [automation] update elastic stack version for testing 7.13.3-6b02e37f
  dev-tools/integration/.env
Labels: automation, dependency

#474 [automation] update elastic stack version for testing 8.0.0-9509d7bd
  dev-tools/integration/.env
Labels: automation, dependency

#477 Move Fleet Server specific config from elastic search section to server section.
  example/fleet-server-100.yml
  internal/pkg/bulk/opt.go
  internal/pkg/config/config_test.go
  internal/pkg/config/input.go
  internal/pkg/config/output.go
  internal/pkg/config/output_test.go
Labels: cleanup, v7.14.0

#479 [automation] update elastic stack version for testing 8.0.0-7640093f
  dev-tools/integration/.env
Labels: automation, dependency

#481 [automation] update elastic stack version for testing 7.13.3-87af5e25
  dev-tools/integration/.env
Labels: automation, dependency

#480 [automation] update elastic stack version for testing 7.14.0-df0371f0
  dev-tools/integration/.env
Labels: automation, dependency

#465 Automate the go version update
  .ci/bump-go-release-version.sh
  .ci/jobs/fleet-server.yml
  .mergify.yml
Labels: Team:Automation, automation, v7.14.0

#472 Add unenroller based on unenroll_timeout from policy
  Makefile
  internal/pkg/coordinator/monitor.go
  internal/pkg/coordinator/monitor_integration_test.go
  internal/pkg/dl/agent.go
  internal/pkg/dl/agent_integration_test.go
  internal/pkg/dl/constants.go
  internal/pkg/es/mapping.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: enhancement, review, v7.14.0

#484 [automation] update elastic stack version for testing 7.14.0-8f9888e1
  dev-tools/integration/.env
Labels: automation, dependency

#485 [automation] update elastic stack version for testing 7.13.3-280f3dca
  dev-tools/integration/.env
Labels: automation, dependency

#488 [automation] update elastic stack version for testing 7.14.0-25663e85
  dev-tools/integration/.env
Labels: automation, dependency

#489 [automation] update elastic stack version for testing 7.13.3-9167705c
  dev-tools/integration/.env
Labels: automation, dependency

#487 [automation] update elastic stack version for testing 8.0.0-49bc2dec
  dev-tools/integration/.env
Labels: automation, dependency

#492 [automation] update elastic stack version for testing 8.0.0-5902d457
  dev-tools/integration/.env
Labels: automation, dependency

#494 [automation] update elastic stack version for testing 7.13.3-ce6a5891
  dev-tools/integration/.env
Labels: automation, dependency

#493 [automation] update elastic stack version for testing 7.14.0-15b00b37
  dev-tools/integration/.env
Labels: automation, dependency

#500 [automation] update elastic stack version for testing 7.13.3-6b302f39
  dev-tools/integration/.env
Labels: automation, dependency

#498 [automation] update elastic stack version for testing 7.14.0-b3f1839d
  dev-tools/integration/.env
Labels: automation, dependency

#499 [automation] update elastic stack version for testing 8.0.0-e1177df4
  dev-tools/integration/.env
Labels: automation, dependency

#501 [automation] update elastic stack version for testing 7.14.0-c5e16e4e
  dev-tools/integration/.env
Labels: automation, dependency

#502 [automation] update elastic stack version for testing 7.13.3-db555786
  dev-tools/integration/.env
Labels: automation, dependency

#504 [automation] update elastic stack version for testing 8.0.0-6a0cf37e
  dev-tools/integration/.env
Labels: automation, dependency

#505 [automation] update elastic stack version for testing 7.13.3-421443ae
  dev-tools/integration/.env
Labels: automation, dependency

#506 Bump 7.x to 7.15.
  main.go
Labels: Team:Agent
