Repository elastic/fleet-server, pull requests merged in 2022-01, with the labels that each got.

#1039 Adjust integration tests to make them work with fleet service token.
  .gitignore
  Makefile
  NOTICE.txt
  dev-tools/integration/get-elasticsearch-servicetoken.sh
  internal/pkg/bulk/bulk_integration_test.go
  internal/pkg/bulk/setup_test.go
  internal/pkg/coordinator/monitor_integration_test.go
  internal/pkg/dl/action_results_integration_test.go
  internal/pkg/dl/actions_integration_test.go
  internal/pkg/dl/agent_integration_test.go
  internal/pkg/dl/enrollment_api_key_integration_test.go
  internal/pkg/dl/policies_integration_test.go
  internal/pkg/dl/policies_leader.go
  internal/pkg/dl/policies_leader_integration_test.go
  internal/pkg/dl/servers_integration_test.go
  internal/pkg/es/client.go
  internal/pkg/es/mapping.go
  internal/pkg/gc/actions_integration_test.go
  internal/pkg/gcheckpt/checkpoint.go
  internal/pkg/monitor/monitor.go
  internal/pkg/monitor/monitor_integration_test.go
  internal/pkg/monitor/subscription_monitor_integration_test.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/testing/actions.go
  internal/pkg/testing/setup.go
  internal/pkg/testing/suite/suite.go
  internal/pkg/testutil/env.go
  main.go
Labels: cleanup, backport-v8.0.0, backport-v8.1.0

#1059 Fix 8.0 branch NOTICE.txt
  NOTICE.txt
Labels: cleanup

#1057 [automation] update elastic stack version for testing 8.0.0-94cbe218
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1056 [automation] update elastic stack version for testing 8.1.0-690c7a63
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1060 [automation] update elastic stack version for testing 8.0.0-f6fa8fcc
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1061 [automation] update elastic stack version for testing 8.1.0-1f83f9c5
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1064 [automation] update elastic stack version for testing 8.0.0-37ccb579
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1065 [automation] update elastic stack version for testing 8.1.0-af114d16
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1066 mergify: close automated prs if they are obsoleted
  .mergify.yml
Labels: automation, backport-skip

#1067 chore: update year 2022
  NOTICE.txt
Labels: dependency

#1063 [automation] update elastic stack version for testing 7.17.0-32e424af
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1070 [automation] update elastic stack version for testing 7.17.0-fe65ce80
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1069 [automation] update elastic stack version for testing 8.1.0-5e490954
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1071 [automation] update elastic stack version for testing 8.0.0-fd4587f2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1075 [automation] update elastic stack version for testing 8.0.0-989003f7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1073 chore: update year 2022 (#1067)
  NOTICE.txt
Labels: Team:Elastic-Agent-Control-Plane

#1079 [automation] update elastic stack version for testing 7.17.0-9b8314f9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1078 [automation] update elastic stack version for testing 8.0.0-ed041828
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1080 [automation] update elastic stack version for testing 7.17.0-2435c356
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1084 [automation] update elastic stack version for testing 7.17.0-049bcf23
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1086 [automation] update elastic stack version for testing 7.17.0-560490e9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1087 [automation] update elastic stack version for testing 7.17.0-079761a0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1088 [automation] update elastic stack version for testing 8.0.0-b44c2e43
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1091 Fix application name in API key
  cmd/fleet/schema.go
  internal/pkg/apikey/apikey_integration_test.go
Labels: bug, backport-v8.0.0, Team:Elastic-Agent-Control-Plane, backport-v8.1.0

#1093 [automation] update elastic stack version for testing 8.1.0-677b9ef0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1068 Seperate unenrollment canceller from policy
  internal/pkg/coordinator/monitor.go
  internal/pkg/coordinator/monitor_integration_test.go
Labels: bug, backport-v8.0.0, Team:Elastic-Agent-Control-Plane, backport-v7.17.0

#1097 [automation] update elastic stack version for testing 8.1.0-f5a18001
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1096 [automation] update elastic stack version for testing 8.0.0-129ef708
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1098 [automation] update elastic stack version for testing 7.17.0-68da5d12
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1099 [automation] update elastic stack version for testing 8.0.0-f196e060
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1100 [automation] update elastic stack version for testing 7.17.0-e1efbe3a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1103 [automation] update elastic stack version for testing 7.17.0-1bd58b32
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1104 [automation] update elastic stack version for testing 8.0.0-6ce456eb
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1105 [automation] update elastic stack version for testing 7.17.0-ab4975a2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1107 [automation] update elastic stack version for testing 7.16.4-206b88b5
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1106 [automation] update elastic stack version for testing 8.1.0-aa69d697
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1109 [automation] update elastic stack version for testing 7.17.0-b9de125e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1110 [automation] update elastic stack version for testing 8.0.0-e2e78bad
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1111 [automation] update elastic stack version for testing 7.16.4-1b320a84
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1115 [automation] update elastic stack version for testing 7.16.4-42a1f428
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1101 Remove `HTTP Done` from the log on every request.
  internal/pkg/logger/http.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-v7.17.0

#1114 Extend the existing status API with build info
  cmd/fleet/handleStatus.go
  cmd/fleet/handleStatus_test.go
  cmd/fleet/main.go
  cmd/fleet/router.go
  cmd/fleet/schema.go
  cmd/fleet/server_test.go
  dev-tools/buildlimits/buildlimits.go
  internal/pkg/config/env_defaults.go
  internal/pkg/config/limits.go
Labels: enhancement, backport-skip

#1117 [automation] update elastic stack version for testing 7.17.0-fd761817
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1118 [automation] update elastic stack version for testing 7.16.4-047be5da
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1119 Add @elastic/elastic-agent-control-plane to the CODEOWNERS file
  .github/CODEOWNERS
Labels: Team:Elastic-Agent-Control-Plane, backport-v7.17.0
