Repository elastic/fleet-server, pull requests merged in 2022-09, with the labels that each got.

#1796 [automation] update elastic stack version for testing 8.4.2-30e0a703
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1795 [automation] update elastic stack version for testing 8.5.0-b5001a6d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1797 [automation] update elastic stack version for testing 7.17.7-cf1ac8b8
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1199 ci: move to fleet-ci
  .ci/Jenkinsfile
  .ci/jobs/defaults.yml
  .ci/jobs/fleet-server-package-mbp.yml
  .ci/jobs/fleet-server.yml
  .ci/jobs/folders.yml
  README.md
Labels: backport-skip

#1806 Fix path to the packaging
  .ci/Jenkinsfile
Labels: backport-v8.3.0, backport-v7.17.0, backport-v8.4.0, backport-v8.5.0

#1807 Fix gcs credentials for packaging
  .ci/packaging.groovy
Labels: backport-v8.3.0, backport-v7.17.0, backport-v8.4.0, backport-v8.5.0

#1823 [automation] update elastic stack version for testing 7.17.7-b0c2ed0e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1821 [automation] update elastic stack version for testing 8.4.2-48cedf17
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1822 [automation] update elastic stack version for testing 8.5.0-de69302b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1827 [automation] update elastic stack version for testing 7.17.7-d187f943
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1826 [automation] update elastic stack version for testing 8.5.0-1bd77fc1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1828 [automation] update elastic stack version for testing 8.4.2-c37a1f37
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1831 [automation] update elastic stack version for testing 8.5.0-167dfc80
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1832 [automation] update elastic stack version for testing 7.17.7-9bf11b3d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1835 [automation] update elastic stack version for testing 8.5.0-6b7dda2d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1834 [automation] update elastic stack version for testing 8.4.2-b244ddfa
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1684 Allow multiple ES outputs as long as they are the same ES
  cmd/fleet/main.go
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleAck_test.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleEnroll.go
  internal/pkg/apikey/apikey.go
  internal/pkg/apikey/apikey_integration_test.go
  internal/pkg/apikey/create.go
  internal/pkg/apikey/get.go
  internal/pkg/apikey/invalidate.go
  internal/pkg/apikey/metadata.go
  internal/pkg/bulk/opBulk.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/coordinator/monitor_integration_test.go
  internal/pkg/dl/agent.go
  internal/pkg/dl/agent_integration_test.go
  internal/pkg/dl/constants.go
  internal/pkg/dl/migration.go
  internal/pkg/dl/migration_integration_test.go
  internal/pkg/es/error.go
  internal/pkg/model/ext.go
  internal/pkg/model/ext_test.go
  internal/pkg/model/schema.go
  internal/pkg/policy/parsed_policy.go
  internal/pkg/policy/parsed_policy_test.go
  internal/pkg/policy/policy_output.go
  internal/pkg/policy/policy_output_integration_test.go
  internal/pkg/policy/policy_output_test.go
  internal/pkg/testing/esutil/bootstrap.go
  internal/pkg/testing/setup.go
  model/schema.json
Labels: bug, Team:Elastic-Agent-Control-Plane, v8.4.0, QA:Needs Validation

#1837 [automation] update elastic stack version for testing 8.5.0-4140365c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1838 [automation] update elastic stack version for testing 7.17.7-2f72b236
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1839 Fix v8.5.0 migration painless script
  internal/pkg/dl/migration.go
  internal/pkg/dl/migration_integration_test.go
Labels: bug, v8.5.0

#1844 [automation] update elastic stack version for testing 7.17.7-e363ab2a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1845 [automation] update elastic stack version for testing 8.4.2-7c2154f4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1843 [automation] update elastic stack version for testing 8.5.0-8e906f9f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1840 ci: rename dra staging for release dra release staging
  .ci/packaging.groovy
Labels: backport-v7.17.0, backport-v8.4.0

#1842 Remove events from agent checkin body.
  CHANGELOG.next.asciidoc
  internal/pkg/api/schema.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.4.0

#1853 [automation] update elastic stack version for testing 8.4.2-879a435a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1852 [automation] update elastic stack version for testing 8.5.0-589a4a10
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1856 [automation] update elastic stack version for testing 8.4.2-fda47f6e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1855 [automation] update elastic stack version for testing 8.5.0-37418cf3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1861 [automation] update elastic stack version for testing 8.4.2-4457f478
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1862 [automation] update elastic stack version for testing 8.5.0-fcf3d4c2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1867 [automation] update elastic stack version for testing 8.4.2-36096067
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1868 [automation] update elastic stack version for testing 8.5.0-c7913db3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1854 Add error detail to catch-all HTTP response
  CHANGELOG.next.asciidoc
  internal/pkg/api/error.go
Labels: enhancement, backport-v8.4.0

#1870 Make authc log debug and add cache hit field
  CHANGELOG.next.asciidoc
  internal/pkg/api/auth.go
Labels: backport-v8.4.0

#1875 [automation] update elastic stack version for testing 8.4.2-b98b12f1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1876 [automation] update elastic stack version for testing 7.17.7-377031d2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1871 Add Go 1.18 upgrade to breaking changes section
  CHANGELOG.next.asciidoc
Labels: v8.5.0

#1881 [automation] update elastic stack version for testing 7.17.7-73e6ed48
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1880 [automation] update elastic stack version for testing 8.5.0-56d2c52d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1779 Bulk API Keys update
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleEnroll.go
  internal/pkg/apikey/apikey_integration_test.go
  internal/pkg/apikey/get.go
  internal/pkg/bulk/block.go
  internal/pkg/bulk/engine.go
  internal/pkg/bulk/opApiKey.go
  internal/pkg/bulk/opt.go
  internal/pkg/bulk/queue.go
  internal/pkg/config/config_test.go
  internal/pkg/config/output.go
  internal/pkg/es/bulk_update_api_key.go
  internal/pkg/policy/policy_output.go
  internal/pkg/policy/policy_output_test.go
  internal/pkg/testing/bulk.go
Labels: enhancement, Feature:fleet-server, Team:Elastic-Agent-Control-Plane, v8.5.0, backport-v8.5.0

#1864 [Release] Update version to 8.4.3
  version/version.go
Labels: Team:Automation, release

#1890 [automation] update elastic stack version for testing 7.17.7-a2d4ea28
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1888 [automation] update elastic stack version for testing 8.5.0-7dc445a0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1889 [automation] update elastic stack version for testing 8.4.3-c8bcc0ff
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1892 backport: Add 8.5 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, release

#1896 Catch error in waitBulkAction. Add bulk.WithRetryOnConflict(3) in multiple places.
  CHANGELOG.next.asciidoc
  internal/pkg/api/handleAck.go
  internal/pkg/bulk/opBulk.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/dl/servers.go
  internal/pkg/policy/policy_output.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.5.0

#1898 [automation] update elastic stack version for testing 7.17.7-86b6ff03
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1899 [automation] update elastic stack version for testing 8.4.3-72a0900d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1900 Update apikey.cache_hit log field name to match convention
  CHANGELOG.next.asciidoc
  internal/pkg/api/auth.go
Labels: cleanup, backport-v8.4.0

#1906 [automation] update elastic stack version for testing 7.17.7-f08d978f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1905 [automation] update elastic stack version for testing 8.4.3-24191b6e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1909 [automation] update elastic stack version for testing 7.17.7-a7e2fef6
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1911 [automation] update elastic stack version for testing 8.4.3-f2e1ac46
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1908 [automation] update elastic stack version for testing 8.6.0-21651da3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1910 [automation] update elastic stack version for testing 8.5.0-d04a8a8e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1912 LoadLimits does not override existing values
  CHANGELOG.next.asciidoc
  internal/pkg/config/cache.go
  internal/pkg/config/config_test.go
  internal/pkg/config/limits.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.4.0, backport-v8.5.0

#1917 [automation] update elastic stack version for testing 7.17.7-3d172834
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1918 [automation] update elastic stack version for testing 8.4.3-3f1f47b9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1915 [automation] update elastic stack version for testing 8.5.0-d6bc1fd7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1916 [automation] update elastic stack version for testing 8.6.0-326f84b0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1924 [automation] update elastic stack version for testing 8.4.3-e8645b30
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1925 [automation] update elastic stack version for testing 8.6.0-df00693f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1923 [automation] update elastic stack version for testing 8.5.0-a415b54b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1930 [automation] update elastic stack version for testing 8.4.3-d0e42d08
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1928 [automation] update elastic stack version for testing 8.6.0-a2f4f140
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1929 [automation] update elastic stack version for testing 8.5.0-dbc138b6
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1920 Revert "updating upgrade_status: completed (#1833)"
  internal/pkg/api/handleAck.go
Labels: v8.6.0, v8.5.0, backport-v8.5.0

#1932 Storing checkin message in last_checkin_message
  CHANGELOG.next.asciidoc
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/schema.go
  internal/pkg/checkin/bulk.go
  internal/pkg/checkin/bulk_test.go
  internal/pkg/dl/constants.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: enhancement, v8.6.0

#1904 Unique limiters for each API listener
  CHANGELOG.next.asciidoc
  cmd/fleet/main.go
  internal/pkg/api/error.go
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleArtifacts.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleEnroll.go
  internal/pkg/api/handleStatus.go
  internal/pkg/api/router.go
  internal/pkg/api/router_test.go
  internal/pkg/api/server.go
  internal/pkg/limit/error.go
  internal/pkg/limit/error_test.go
  internal/pkg/limit/httpwrapper.go
  internal/pkg/limit/limiter.go
  internal/pkg/limit/limiter_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.5.0

#1886 Cleanup cmd/fleet/main.go
  cmd/fleet/main.go
  cmd/fleet/main_integration_test.go
  cmd/fleet/server_integration_test.go
  internal/pkg/api/handleAck_test.go
  internal/pkg/api/handleStatus_test.go
  internal/pkg/api/router_test.go
  internal/pkg/bulk/bulk_integration_test.go
  internal/pkg/cache/cache.go
  internal/pkg/cache/impl_integration.go
  internal/pkg/cache/impl_ristretto.go
  internal/pkg/config/cache.go
  internal/pkg/config/config.go
  internal/pkg/policy/parsed_policy_test.go
  internal/pkg/server/agent.go
  internal/pkg/server/fleet.go
  internal/pkg/server/server.go
Labels: cleanup, Team:Fleet

#1935 Improve migration logs on 8.5 branch
  cmd/fleet/main.go
  internal/pkg/dl/migration.go
Labels: enhancement

#1938 [automation] update elastic stack version for testing 8.6.0-158a13db
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1937 [automation] update elastic stack version for testing 8.4.3-0900b129
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1939 [automation] update elastic stack version for testing 8.5.0-b22c068f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1926 [8.6](forwardport) Add extra protection against accessing null fields to 8.5 migration (#1921)
  cmd/fleet/main.go
  internal/pkg/dl/migration.go
Labels: bug, v8.6.0
