Repository elastic/fleet-server, pull requests merged in 2022-11, with the labels that each got.

#2046 [automation] update elastic stack version for testing 8.4.4-55734bd7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2045 [automation] update elastic stack version for testing 8.6.0-26dc1164
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1893 [Release] Update version to 8.5.1
  version/version.go
Labels: Team:Automation, release

#2044 Add active filter for enrollment key queries.
  CHANGELOG.next.asciidoc
  internal/pkg/dl/enrollment_api_key.go
  internal/pkg/dl/enrollment_api_key_integration_test.go
  internal/pkg/policy/self.go
  internal/pkg/policy/self_test.go
Labels: bug, backport-v8.5.0

#2048 [automation] update elastic stack version for testing 8.6.0-4765d2b0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2049 [automation] update elastic stack version for testing 8.4.4-dcd4a95f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2050 [automation] update elastic stack version for testing 8.6.0-8a615646
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2053 [automation] update elastic stack version for testing 7.17.8-1d146f89
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2052 [automation] update elastic stack version for testing 8.5.1-7fd6ffae
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2051 [automation] update elastic stack version for testing 8.6.0-3f5f98b7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2058 [automation] update elastic stack version for testing 7.17.8-a281a566
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2057 [automation] update elastic stack version for testing 8.5.1-2ceb7fad
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2056 [automation] update elastic stack version for testing 8.6.0-f20b7179
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2061 Update the elastic-agent-client to latest version.
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Control-Plane

#2055 [automation] Update go release version 1.18.8
  .go-version
Labels: automation, dependency, backport-skip

#2065 [automation] update elastic stack version for testing 8.6.0-da453972
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2066 [automation] update elastic stack version for testing 8.5.1-2041424b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2071 [automation] update elastic stack version for testing 7.17.8-e6d29314
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2069 [automation] update elastic stack version for testing 8.6.0-c9d1a5e9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2070 [automation] update elastic stack version for testing 8.5.1-6bdef2c7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2074 [automation] update elastic stack version for testing 8.5.1-1f91140d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2078 [automation] update elastic stack version for testing 7.17.8-8be7042c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2077 [automation] update elastic stack version for testing 8.5.1-d7343c55
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2072 Add fleet-server design checklist to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Team:Elastic-Agent, Team:Fleet

#2082 [automation] update elastic stack version for testing 7.17.8-581ea684
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2081 [automation] update elastic stack version for testing 8.5.1-49e04c16
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2080 [automation] update elastic stack version for testing 8.6.0-0c44a3fc
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2067 [Release] Update version to 8.5.2
  version/version.go
Labels: Team:Automation, release

#2085 [automation] update elastic stack version for testing 7.17.8-e4279e1a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2084 [automation] update elastic stack version for testing 8.6.0-9a0f87a9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2087 backport: Add 8.6 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, release

#2086 Bump the version on main to 8.7.0
  version/version.go
Labels: backport-skip

#2090 [automation] update elastic stack version for testing 8.6.0-41eabcfc
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2094 [automation] update elastic stack version for testing 7.17.8-ca244ec8
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2095 [automation] update elastic stack version for testing 8.5.2-733d317b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2093 [automation] update elastic stack version for testing 8.7.0-eb092238
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2099 [automation] update elastic stack version for testing 7.17.8-c416a4cb
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2097 [automation] update elastic stack version for testing 8.7.0-84b6e00d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2098 [automation] update elastic stack version for testing 8.6.0-afa9010f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2100 [automation] update elastic stack version for testing 8.5.2-13a22054
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2103 [automation] update elastic stack version for testing 8.5.2-c2e5a3f4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2104 [automation] update elastic stack version for testing 8.7.0-4188bdf4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2102 [automation] update elastic stack version for testing 8.6.0-e72cd235
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2089 [Release] Update version to 8.5.3
  version/version.go
Labels: Team:Automation, release

#2108 [automation] update elastic stack version for testing 8.5.2-98bdbc90
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2106 [automation] update elastic stack version for testing 8.7.0-c5c709bf
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2107 [automation] update elastic stack version for testing 8.6.0-3747fc18
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2092 fix unenroll offline agents
  CHANGELOG.next.asciidoc
  internal/pkg/coordinator/monitor.go
  internal/pkg/model/ext.go
  internal/pkg/model/ext_test.go
Labels: bug, v8.7.0, backport-v8.5.0, backport-v8.6.0

#2114 [automation] update elastic stack version for testing 8.7.0-11ac5926
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2116 [automation] update elastic stack version for testing 8.6.0-742fd135
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2115 [automation] update elastic stack version for testing 8.5.3-760caed9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2123 [automation] update elastic stack version for testing 8.5.3-c0681f01
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2124 [automation] update elastic stack version for testing 8.5.3-a0b682b9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2126 Update module dependencies
  NOTICE.txt
  go.mod
  go.sum
Labels: cleanup, Team:Fleet

#2120 Fix check-go linter version
  .github/workflows/golangci-lint.yml
  Makefile
Labels: Team:Fleet, tech debt

#2128 [automation] update elastic stack version for testing 8.5.3-770e9287
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2118 Respect cli overrrides
  internal/pkg/server/agent.go
  internal/pkg/server/agent_test.go
Labels: bug, Team:Elastic-Agent, backport-skip, Team:Elastic-Agent-Control-Plane

#2117 Added back agent team as codeowners
  .github/CODEOWNERS
Labels: backport-v7.17.0, backport-v8.4.0, backport-v8.5.0, backport-v8.6.0

#2136 Updated elastic-agent-client to v7.0.2-0.20221129150247-15881a8e64ef
  NOTICE.txt
  go.mod
  go.sum
Labels: bug, Team:Elastic-Agent, Team:Elastic-Agent-Control-Plane, backport-v8.6.0

#2101 [7.17] Update to go v1.18.8 Update deps to latest patch
  .github/workflows/golangci-lint.yml
  .go-version
  Dockerfile.build
  Makefile
  NOTICE.txt
  dev-tools/notice/overrides.json
  dev-tools/notice/rules.json
  go.mod
  go.sum
Labels: cleanup, backport

#2139 [automation] update elastic stack version for testing 8.5.3-a46b25ec
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2142 actions: use go-version-file: .go-version
  .github/workflows/golangci-lint.yml
Labels: backport-v7.17.0, backport-v8.5.0, backport-v8.6.0
