Repository elastic/fleet-server, pull requests merged in 2022-12, with the labels that each got.

#2146 [automation] update elastic stack version for testing 8.6.0-87c26073
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2147 [automation] update elastic stack version for testing 8.5.3-268167d7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2151 [automation] update elastic stack version for testing 8.5.3-1625ae9f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2152 [automation] update elastic stack version for testing 8.7.0-1b0dc867
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2150 [automation] update elastic stack version for testing 8.6.0-f96862e0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2148 Fix linter issues
  internal/pkg/dl/migration.go
  internal/pkg/policy/self.go
  internal/pkg/profile/profile.go
  internal/pkg/server/agent_integration_test.go
  internal/pkg/server/fleet.go
Labels: cleanup, Team:Fleet

#2156 [automation] update elastic stack version for testing 8.5.3-0a7c209d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2157 [automation] update elastic stack version for testing 8.6.0-368aeeae
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2158 Update client dependency to latest 7.0.2"
  NOTICE.txt
  go.mod
  go.sum
Labels: bug, Team:Elastic-Agent, Team:Elastic-Agent-Control-Plane, backport-v8.6.0

#2153 Remove direct pkg/errors dependency
  NOTICE.txt
  dev-tools/buildlimits/buildlimits.go
  go.mod
  internal/pkg/api/error.go
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleArtifacts.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleEnroll.go
  internal/pkg/api/metrics.go
  internal/pkg/apikey/apikey.go
  internal/pkg/config/env_defaults.go
  internal/pkg/dl/migration.go
Labels: cleanup, Team:Fleet

#2161 [automation] update elastic stack version for testing 8.5.3-55d94167
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2162 [automation] update elastic stack version for testing 8.7.0-7fe23b13
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2166 [automation] update elastic stack version for testing 8.7.0-2c7c2bad
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2165 [automation] update elastic stack version for testing 8.6.0-57f16700
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2167 [automation] update elastic stack version for testing 8.5.3-e63a0e72
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2119 [Fleet] Update .fleet-agent on policy change ack even without ES output
  internal/pkg/api/handleAck.go
Labels: v8.6.0, v8.7.0

#2171 [automation] update elastic stack version for testing 8.5.3-ec242734
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2172 [automation] update elastic stack version for testing 8.7.0-188e6a3a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2170 [automation] update elastic stack version for testing 8.6.0-7c9fd7a8
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2175 [automation] update elastic stack version for testing 8.7.0-59d5589a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2176 [automation] update elastic stack version for testing 8.5.3-91bdfab4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2174 [automation] update elastic stack version for testing 8.6.0-3bb8e729
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2178 [automation] update elastic stack version for testing 8.7.0-e9833f49
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2179 [automation] update elastic stack version for testing 8.6.0-febebae1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2177 [automation] Update go release version 1.18.9
  .go-version
Labels: automation, dependency, backport-skip

#2181 [automation] update elastic stack version for testing 8.7.0-08cd8ac3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2182 [automation] update elastic stack version for testing 8.6.0-6538107d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2183 [Release] Update version to 7.17.9
  main.go
Labels: Team:Automation, release

#2185 [automation] update elastic stack version for testing 8.7.0-04d5f080
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2173 Update all modules
  .golangci.yml
  NOTICE.txt
  dev-tools/dependencies-report
  go.mod
  go.sum
  internal/pkg/action/token_resolver.go
  internal/pkg/apikey/apikey.go
  internal/pkg/apikey/apikey_integration_test.go
  internal/pkg/apikey/auth.go
  internal/pkg/apikey/create.go
  internal/pkg/apikey/invalidate.go
  internal/pkg/bulk/engine.go
  internal/pkg/bulk/helpers.go
  internal/pkg/bulk/opBulk.go
  internal/pkg/bulk/opRead.go
  internal/pkg/bulk/opSearch.go
  internal/pkg/config/output.go
  internal/pkg/config/output_test.go
  internal/pkg/dl/migration.go
  internal/pkg/es/bulk_update_api_key.go
  internal/pkg/es/client.go
  internal/pkg/es/delete.go
  internal/pkg/es/fleet_global_checkpoints.go
  internal/pkg/es/fleet_msearch.go
  internal/pkg/es/fleet_search.go
  internal/pkg/es/info.go
  internal/pkg/gcheckpt/checkpoint.go
  internal/pkg/monitor/monitor.go
  internal/pkg/monitor/subscription_monitor.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/testing/bulk.go
  internal/pkg/testing/esutil/bootstrap.go
  internal/pkg/testing/esutil/datastream.go
  internal/pkg/testing/esutil/esutil.go
  internal/pkg/testing/esutil/ilm.go
  internal/pkg/testing/esutil/index.go
  internal/pkg/testing/esutil/template.go
  internal/pkg/testing/setup.go
  internal/pkg/ver/check.go
Labels: cleanup, Team:Fleet

#2189 [automation] update elastic stack version for testing 8.6.0-919399a0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2188 [automation] update elastic stack version for testing 8.7.0-4441fcfd
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2191 [automation] update elastic stack version for testing 7.17.9-90a80afe
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2190 [automation] update elastic stack version for testing 8.7.0-319a9bee
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2193 [automation] update elastic stack version for testing 8.6.0-d5c0a6be
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2195 [automation] update elastic stack version for testing 8.5.4-9a613070
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2197 [automation] update elastic stack version for testing 8.6.0-a85d8f17
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2200 filtering out UPDATE_TAGS and FORCE_UNENROLL
  CHANGELOG.next.asciidoc
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/schema.go
Labels: v8.7.0

#2203 [automation] update elastic stack version for testing 8.6.0-734df845
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2202 [automation] update elastic stack version for testing 8.7.0-19f30181
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2204 [automation] update elastic stack version for testing 7.17.9-ab98c430
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2207 [automation] update elastic stack version for testing 7.17.9-dea3eaf3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2208 [automation] update elastic stack version for testing 8.5.4-880022a5
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2209 [automation] update elastic stack version for testing 8.6.0-55d181cf
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2213 [automation] update elastic stack version for testing 7.17.9-89f6cb7d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2215 [automation] update elastic stack version for testing 8.5.4-9612e66a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2214 [automation] update elastic stack version for testing 8.6.0-33529ee6
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2180 Add OpenAPI spec for fleet-server endpoints.
  model/openapi.yml
Labels: Team:Fleet, Team:Elastic-Agent-Control-Plane, tech debt

#2192 Remove custom elasticsearch api methods.
  internal/pkg/bulk/opApiKey.go
  internal/pkg/bulk/opSearch.go
  internal/pkg/es/bulk_update_api_key.go
  internal/pkg/es/doc.go
  internal/pkg/es/fleet_global_checkpoints.go
  internal/pkg/es/fleet_msearch.go
  internal/pkg/es/fleet_search.go
  internal/pkg/gcheckpt/checkpoint.go
  internal/pkg/monitor/monitor.go
Labels: Team:Fleet, tech debt

#2219 [automation] update elastic stack version for testing 7.17.9-917139ef
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2218 [automation] update elastic stack version for testing 8.6.0-f6d7d537
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2217 [automation] update elastic stack version for testing 8.5.4-09ced402
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2216 [automation] update elastic stack version for testing 8.7.0-0f74a2e9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2222 [automation] update elastic stack version for testing 7.17.9-0c41c515
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2223 [automation] update elastic stack version for testing 8.5.4-53cae6e0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2221 [automation] update elastic stack version for testing 8.6.0-a026c2fe
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2227 [automation] update elastic stack version for testing 7.17.9-590749d6
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2226 [automation] update elastic stack version for testing 8.5.4-b44284e8
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2224 [automation] update elastic stack version for testing 8.6.0-7e55dcb1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2225 [automation] update elastic stack version for testing 8.7.0-b3da67ae
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2230 [automation] update elastic stack version for testing 7.17.9-fb6ed84b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2229 [automation] update elastic stack version for testing 8.5.4-63dd32c9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2228 [automation] update elastic stack version for testing 8.6.0-08909b84
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2232 [automation] update elastic stack version for testing 7.17.9-9b93f6c8
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2233 [automation] update elastic stack version for testing 8.5.4-2ce7df52
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2235 [automation] update elastic stack version for testing 8.6.0-2d1af9b1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2234 [automation] update elastic stack version for testing 8.7.0-d6e7f5ec
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
