Repository elastic/fleet-server, pull requests merged in 2022-10, with the labels that each got.

#1943 [automation] update elastic stack version for testing 8.4.3-5e0dd488
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1944 [automation] update elastic stack version for testing 8.5.0-49b2dce3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1942 [automation] update elastic stack version for testing 8.6.0-aea1c645
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1949 [automation] update elastic stack version for testing 7.17.7-70d4ef7d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1948 [automation] update elastic stack version for testing 8.6.0-0fca2953
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1947 [automation] update elastic stack version for testing 8.4.3-ff95b7c5
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1953 [automation] update elastic stack version for testing 8.4.3-83e508e5
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1955 [automation] update elastic stack version for testing 8.5.0-58624073
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1954 [automation] update elastic stack version for testing 8.6.0-e4c15f15
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1956 [automation] update elastic stack version for testing 7.17.7-a343880e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1919 [Release] Update version to 8.4.4
  version/version.go
Labels: Team:Automation, release

#1946 Conditional log level for api key read
  internal/pkg/api/error.go
  internal/pkg/api/handleAck.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.5.0

#1959 Updated migration query to match items with deprecated field present
  internal/pkg/dl/migration.go
  internal/pkg/dl/migration_integration_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v8.5.0

#1951 Fix fleet.migration.total log key overlap
  CHANGELOG.next.asciidoc
  internal/pkg/dl/migration.go
Labels: cleanup, backport-v8.4.0, backport-v8.5.0

#1967 [automation] update elastic stack version for testing 7.17.7-f9849b81
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1965 [automation] update elastic stack version for testing 8.4.4-ac374c4b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1966 [automation] update elastic stack version for testing 8.5.0-c52257ee
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1964 [automation] update elastic stack version for testing 8.6.0-d939cfde
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1972 [automation] update elastic stack version for testing 7.17.7-3947c049
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1971 [automation] update elastic stack version for testing 8.4.4-17ce02d0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1970 [automation] update elastic stack version for testing 8.5.0-7d416dc4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1969 [automation] update elastic stack version for testing 8.6.0-7c9f25a9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1973 [automation] update elastic stack version for testing 7.17.7-32fc38cc
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1974 [automation] update elastic stack version for testing 8.4.4-221d2ff4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1975 [automation] update elastic stack version for testing 8.5.0-4f4df9f4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1976 [automation] update elastic stack version for testing 8.6.0-c49fac70
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1978 Update to Go 1.18.7.
  .go-version
Labels: backport-v8.5.0

#1983 [automation] update elastic stack version for testing 7.17.7-8081bbcb
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1981 [automation] update elastic stack version for testing 8.6.0-5a8d757d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1982 [automation] update elastic stack version for testing 8.5.0-09886b6e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1988 [automation] update elastic stack version for testing 8.4.4-1129f33b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1987 [automation] update elastic stack version for testing 8.6.0-40086bc7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1986 [automation] update elastic stack version for testing 8.5.0-fe2e6147
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1989 [automation] update elastic stack version for testing 7.17.7-a44998d0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1993 [automation] update elastic stack version for testing 7.17.7-40d7eba9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1991 [automation] update elastic stack version for testing 8.5.0-976bca07
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1990 [automation] update elastic stack version for testing 8.6.0-233dc5d4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1992 [automation] update elastic stack version for testing 8.4.4-fdf1902b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1996 [automation] update elastic stack version for testing 7.17.7-e7a47621
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1995 [automation] update elastic stack version for testing 8.6.0-54a302f0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1994 [automation] update elastic stack version for testing 8.5.0-f8c98e5d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1997 [automation] update elastic stack version for testing 8.4.4-2db0c963
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1963 Don't send POLICY_CHANGE actions retrieved from index to agent.
  CHANGELOG.next.asciidoc
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/handleChecking_test.go
Labels: bug, Team:Fleet, Team:Elastic-Agent-Control-Plane, backport-v8.5.0

#2002 [automation] update elastic stack version for testing 7.17.7-f82fb944
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2001 [automation] update elastic stack version for testing 8.4.4-93b2bfdf
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1999 [automation] update elastic stack version for testing 8.5.0-7c74e950
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2000 [automation] update elastic stack version for testing 8.6.0-cae815eb
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2007 [automation] update elastic stack version for testing 7.17.7-c42c4e01
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2008 [automation] update elastic stack version for testing 8.4.4-e97ba82f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2005 [automation] update elastic stack version for testing 8.6.0-6545f2df
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2006 [automation] update elastic stack version for testing 8.5.0-792499b4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2013 [automation] update elastic stack version for testing 7.17.7-55166c00
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2012 [automation] update elastic stack version for testing 8.4.4-51bbfe53
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2010 [automation] update elastic stack version for testing 8.5.0-7e528e3e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2011 [automation] update elastic stack version for testing 8.6.0-055acc83
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2019 [automation] update elastic stack version for testing 7.17.7-60386d02
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2016 [automation] update elastic stack version for testing 8.6.0-baf193e8
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2018 [automation] update elastic stack version for testing 8.4.4-4edb5c6b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2017 [automation] update elastic stack version for testing 8.5.0-754ef325
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2020 [automation] update elastic stack version for testing 8.6.0-22d60ec9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2021 [automation] update elastic stack version for testing 8.4.4-9b801d60
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2022 [automation] update elastic stack version for testing 8.5.0-d7b01592
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2023 [automation] update elastic stack version for testing 7.17.7-e6ce36d2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2014 updated version to 8.6
  version/version.go
Labels: Team:Fleet, Team:Elastic-Agent-Control-Plane

#1887 Allow upgrade action to signal retry
  CHANGELOG.next.asciidoc
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleAck_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#2025 [automation] update elastic stack version for testing 7.17.7-0a02d958
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2026 [automation] update elastic stack version for testing 8.4.4-46f2f222
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2024 [automation] update elastic stack version for testing 8.6.0-b8b35931
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2004 [Release] Update version to 7.17.8
  main.go
Labels: Team:Automation, release

#2028 [automation] update elastic stack version for testing 8.4.4-1ee39d03
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2027 [automation] update elastic stack version for testing 8.5.0-bdb74671
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2032 [automation] update elastic stack version for testing 8.4.4-d66e996a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2031 [automation] update elastic stack version for testing 8.5.0-eb17cbd2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2030 [automation] update elastic stack version for testing 8.6.0-a892f234
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2036 [automation] update elastic stack version for testing 7.17.8-d89bf16d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2037 [automation] update elastic stack version for testing 8.4.4-6eb63640
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2035 [automation] update elastic stack version for testing 8.5.0-4028b295
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2034 [automation] update elastic stack version for testing 8.6.0-89d224d2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2041 [automation] update elastic stack version for testing 8.5.0-f48cdca0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2039 [automation] update elastic stack version for testing 8.6.0-949a38d2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2040 [automation] update elastic stack version for testing 8.4.4-f3b8851a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
