Repository elastic/fleet-server, pull requests merged in 2022-05, with the labels that each got.

#1411 [automation] update elastic stack version for testing 8.1.4-76569f3d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1412 [automation] update elastic stack version for testing 8.2.0-e7ad9ef0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1413 [automation] update elastic stack version for testing 7.17.4-ed667030
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1410 [automation] update elastic stack version for testing 8.3.0-eb27d7ab
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1416 [automation] update elastic stack version for testing 8.1.4-1cdc80b6
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1417 [automation] update elastic stack version for testing 7.17.4-9ca33e9a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1414 [automation] update elastic stack version for testing 8.2.0-56396fd0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1415 [automation] update elastic stack version for testing 8.3.0-0b6ea9f2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1418 Remove backport-skip automation
  .mergify.yml
Labels: backport-skip

#1422 [automation] update elastic stack version for testing 8.1.4-86899ed7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1421 [automation] update elastic stack version for testing 7.17.4-cd92752d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1420 [automation] update elastic stack version for testing 8.3.0-7f585873
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1276 Update to 8.2.1
  main.go
Labels: Team:Elastic-Agent-Control-Plane

#1425 [automation] update elastic stack version for testing 8.1.4-37d447ec
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1427 [automation] update elastic stack version for testing 7.17.4-c570579f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1426 [automation] update elastic stack version for testing 8.3.0-a1c5cfff
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1430 [automation] update elastic stack version for testing 8.1.4-6c818705
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1429 [automation] update elastic stack version for testing 8.3.0-6ba9f710
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1428 [automation] update elastic stack version for testing 7.17.4-2fe5353f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1350 Add tags to fleet server
  CHANGELOG.next.asciidoc
  internal/pkg/api/handleEnroll.go
  internal/pkg/api/schema.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: backport-skip, Team:Elastic-Agent-Control-Plane, v8.3.0

#1434 [automation] update elastic stack version for testing 8.3.0-5c1ff35f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1437 [automation] update elastic stack version for testing 7.17.4-37e626ca
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1438 [automation] update elastic stack version for testing 8.2.1-d6d75d75
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1436 [automation] update elastic stack version for testing 8.3.0-d380914f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1439 ci: use downstream pattern
  .ci/Jenkinsfile
  .ci/packaging.groovy
Labels: automation, backport-v8.2.0, backport-v8.3.0, backport-v8.1.0, backport-v7.17.0

#1440 jjbb: suppress-scm-triggering
  .ci/jobs/fleet-server-package-mbp.yml
Labels: automation, backport-skip

#1453 [automation] update elastic stack version for testing 8.3.0-53513548
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1433 Add additional docstrings
  internal/pkg/action/dispatcher.go
  internal/pkg/action/token_resolver.go
  internal/pkg/api/auth.go
  internal/pkg/apikey/apikey.go
  internal/pkg/apikey/auth.go
  internal/pkg/apikey/create.go
  internal/pkg/apikey/get.go
  internal/pkg/apikey/metadata.go
  internal/pkg/build/build.go
  internal/pkg/monitor/monitor.go
  internal/pkg/monitor/subscription_monitor.go
  internal/pkg/profile/profile.go
  internal/pkg/rollback/rollback.go
  internal/pkg/scheduler/scheduler.go
  internal/pkg/sleep/sleep.go
  internal/pkg/smap/smap.go
  internal/pkg/sqn/sqn.go
Labels: docs, Team:Elastic-Agent-Control-Plane

#1449 ci: use post-builds for reporting only
  .ci/Jenkinsfile
Labels: backport-v8.2.0, backport-v8.3.0, backport-v8.1.0, backport-v7.17.0

#1458 [automation] update elastic stack version for testing 7.17.4-6a00b8d7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1457 [automation] update elastic stack version for testing 8.2.1-91d7a53f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1459 [automation] update elastic stack version for testing 8.3.0-8ee1196f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1467 [automation] update elastic stack version for testing 8.3.0-19aba912
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1468 [automation] update elastic stack version for testing 8.2.1-3d12787c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1469 [automation] update elastic stack version for testing 7.17.4-191b5600
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1477 [automation] update elastic stack version for testing 8.3.0-e4aa1f83
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1479 [automation] update elastic stack version for testing 7.17.4-3585da41
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1478 [automation] update elastic stack version for testing 8.2.1-8d9ffca9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1432 Change pkg/monitor/mock to use testify/mock
  internal/pkg/api/server_test.go
  internal/pkg/monitor/mock/monitor.go
  internal/pkg/policy/monitor_test.go
  internal/pkg/policy/self_test.go
Labels: cleanup, Team:Elastic-Agent-Control-Plane

#1483 [automation] update elastic stack version for testing 8.2.1-93582d09
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1482 [automation] update elastic stack version for testing 8.3.0-a55286cc
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1484 [automation] update elastic stack version for testing 7.17.4-16f62393
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1351 Remove dependency on `github.com/elastic/beats/v7`
  .golangci.yml
  Makefile
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/api/metrics.go
  internal/pkg/api/server.go
  internal/pkg/config/input.go
  internal/pkg/config/output.go
  internal/pkg/config/output_test.go
  internal/pkg/logger/logger.go
  main.go
  version/version.go
Labels: backport-skip

#1486 [automation] update elastic stack version for testing 7.17.4-60cd01b1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1485 [automation] update elastic stack version for testing 8.3.0-d754f94f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1487 [automation] update elastic stack version for testing 8.2.1-54274789
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1492 [automation] update elastic stack version for testing 7.17.4-1170b674
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1491 [automation] update elastic stack version for testing 8.2.1-539cf6f5
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1490 [automation] update elastic stack version for testing 8.3.0-3a5a0cd2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1381 Add start_time and minimum_execution_duration fields to actions
  CHANGELOG.next.asciidoc
  internal/pkg/action/dispatcher.go
  internal/pkg/action/dispatcher_test.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/schema.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: enhancement, backport-skip, Team:Elastic-Agent-Control-Plane

#1493 [automation] update elastic stack version for testing 7.17.4-1572020b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1494 [automation] update elastic stack version for testing 8.3.0-bf0ad929
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1495 [automation] update elastic stack version for testing 8.2.1-e97da867
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1498 Update to 7.17.5
  main.go
Labels: Team:Elastic-Agent-Control-Plane

#1497 Update to 8.2.2
  main.go
Labels: Team:Elastic-Agent-Control-Plane

#1502 [automation] update elastic stack version for testing 8.2.1-f86dca4c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1501 [automation] update elastic stack version for testing 8.3.0-a2430aec
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1503 [automation] update elastic stack version for testing 7.17.4-d3844d00
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1504 Update main to 8.4.0
  version/version.go
Labels: Team:Elastic-Agent-Control-Plane

#1505 Update to 8.2.3
  main.go
Labels: Team:Elastic-Agent-Control-Plane

#1506 [automation] update elastic stack version for testing 7.17.5-18de74ad
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1508 [automation] update elastic stack version for testing 7.17.5-5c3baac2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1509 [automation] update elastic stack version for testing 7.17.5-366dc66d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
