Repository elastic/fleet-server, pull requests merged in 2022-07, with the labels that each got.

#1627 [automation] update elastic stack version for testing 8.4.0-3d206b5d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1629 [automation] update elastic stack version for testing 7.17.6-63d4a205
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1631 [automation] update elastic stack version for testing 8.4.0-03bd6f3f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1632 [automation] update elastic stack version for testing 8.3.2-d34285fd
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1636 [automation] update elastic stack version for testing 8.3.2-56253b46
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1637 [automation] update elastic stack version for testing 8.4.0-533f1e30
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1559 Allow to compile a binary for debug
  Makefile
  README.md
  Vagrantfile
  internal/pkg/rollback/rollback.go
Labels: enhancement

#1642 [automation] update elastic stack version for testing 7.17.6-94c92680
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1644 [automation] update elastic stack version for testing 8.4.0-d0a4da44
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1643 [automation] update elastic stack version for testing 8.3.2-97fdd78b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1646 [automation] update elastic stack version for testing 8.3.3-385d4fdb
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1647 [automation] update elastic stack version for testing 8.4.0-dd98ded4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1648 [automation] update elastic stack version for testing 7.17.6-38278486
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1652 [automation] update elastic stack version for testing 7.17.6-cff0caa9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1651 [automation] update elastic stack version for testing 8.3.3-46b07667
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1650 [automation] update elastic stack version for testing 8.4.0-164d9a10
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1655 [automation] update elastic stack version for testing 7.17.6-5c77e057
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1653 [automation] update elastic stack version for testing 8.3.3-0264aa15
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1654 [automation] update elastic stack version for testing 8.4.0-00048b66
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1657 ci: run packaging by default on branches only
  .ci/Jenkinsfile
Labels: backport-v8.3.0, backport-v7.17.0

#1662 [automation] update elastic stack version for testing 7.17.6-a62286d6
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1661 [automation] update elastic stack version for testing 8.3.3-fba30f71
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1665 [automation] update elastic stack version for testing 7.17.6-75df96d4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1664 [automation] update elastic stack version for testing 8.3.3-f93ba5f4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1663 [automation] update elastic stack version for testing 8.4.0-3cd57abb
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1670 [automation] update elastic stack version for testing 7.17.6-0aa797e4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1669 [automation] update elastic stack version for testing 8.3.3-99553f72
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1668 [automation] update elastic stack version for testing 8.4.0-a324b98b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1674 [automation] update elastic stack version for testing 8.3.3-302be7c1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1673 [automation] update elastic stack version for testing 8.4.0-31315ca3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1676 [automation] update elastic stack version for testing 7.17.6-0f95e383
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1678 [automation] update elastic stack version for testing 8.3.3-e5bc7e69
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1677 [automation] update elastic stack version for testing 8.4.0-31269fd2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1679 [automation] update elastic stack version for testing 8.3.3-508a8f45
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1680 [automation] update elastic stack version for testing 7.17.6-7ad6b445
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1682 [automation] update elastic stack version for testing 8.3.3-bb633b08
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1683 [automation] update elastic stack version for testing 7.17.6-9675035b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1687 [automation] update elastic stack version for testing 7.17.6-964edfea
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1685 [automation] update elastic stack version for testing 8.4.0-d058e92f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1686 [automation] update elastic stack version for testing 8.3.3-5fe7d8b1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1681 Add support for setting APM `transaction_sample_rate`
  CHANGELOG.next.asciidoc
  cmd/fleet/main.go
  internal/pkg/config/instrumentation.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#1689 [automation] update elastic stack version for testing 8.3.3-d520d440
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1690 [automation] update elastic stack version for testing 7.17.6-3f4b9bc6
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1691 backport: Add 8.4 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, release

#1693 Update main branch to 8.5.0
  version/version.go
Labels: Team:Elastic-Agent-Control-Plane

#1695 [automation] update elastic stack version for testing 8.3.3-8631d33c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1694 [automation] update elastic stack version for testing 8.4.0-60171339
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1675 [Release] Update version to 8.3.4
  version/version.go
Labels: Team:Automation, release

#1699 [automation] update elastic stack version for testing 8.4.0-fb724a71
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1698 [automation] update elastic stack version for testing 8.3.3-326db639
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1700 [automation] update elastic stack version for testing 7.17.6-b64de485
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
