Repository elastic/fleet-server, pull requests merged in 2022-03, with the labels that each got.

#1187 [automation] update elastic stack version for testing 7.17.1-bf42f386
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1191 [automation] update elastic stack version for testing 7.17.2-3e73f87b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1195 [automation] update elastic stack version for testing 8.1.0-fbfb1f9e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1192 [automation] update elastic stack version for testing 7.17.2-e8098595
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1196 [automation] update elastic stack version for testing 8.1.0-5eb67818
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1198 [automation] update elastic stack version for testing 8.0.2-ae36dda7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1197 [automation] update elastic stack version for testing 8.2.0-190af159
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1204 [automation] update elastic stack version for testing 8.0.2-901e2b50
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1205 [automation] update elastic stack version for testing 8.1.0-52a8d1d4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1203 [automation] update elastic stack version for testing 8.2.0-a12f7069
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1201 Bump version to 8.1.1
  main.go
Labels: backport-skip, release

#1211 Report back the detected version of the remote Elasticsearch
  CHANGELOG.next.asciidoc
  cmd/fleet/main.go
  internal/pkg/ver/check.go
Labels: backport-v8.0.0, Team:Elastic-Agent-Control-Plane, backport-v8.2.0, backport-v8.3.0, backport-v8.1.0, backport-v7.17.0

#1217 [automation] update elastic stack version for testing 8.1.1-b9a6c108
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1219 [automation] update elastic stack version for testing 7.17.2-c18736fc
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1220 [automation] update elastic stack version for testing 8.1.1-da392dcd
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1221 Update CODEOWNERS file
  .github/CODEOWNERS
Labels: backport-skip

#1225 [automation] update elastic stack version for testing 8.1.1-2d188131
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1226 [automation] update elastic stack version for testing 7.17.2-8be09371
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1214 Udpate go mod
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.3.0

#1229 [automation] update elastic stack version for testing 8.1.1-31faf00b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1230 [automation] update elastic stack version for testing 7.17.2-2208f979
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1237 [automation] update elastic stack version for testing 7.17.2-8f7db3a8
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1235 [automation] update elastic stack version for testing 8.1.1-9bb65a23
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1233 jjbb: for the packaging only
  .ci/jobs/fleet-server-package-mbp.yml
Labels: automation, Team:Automation, backport-skip

#1240 [automation] update elastic stack version for testing 8.1.1-da22c151
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1241 [automation] update elastic stack version for testing 7.17.2-15b5bc7a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1238 ci: store build/distributions
  .ci/Jenkinsfile
Labels: Team:Automation, backport-v8.0.0, backport-v8.2.0, backport-v8.1.0

#1239 [automation] update elastic stack version for testing 8.2.0-82b803a1
  dev-tools/integration/.env
  internal/pkg/bulk/bulk_integration_test.go
Labels: automation, dependency, backport-skip

#1246 [automation] update elastic stack version for testing 8.1.1-0d572bb7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1247 [automation] update elastic stack version for testing 7.17.2-3b3b663d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1245 [automation] update elastic stack version for testing 8.2.0-5cc993c1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1188 Logstash output
  CHANGELOG.next.asciidoc
  cmd/fleet/auth.go
  cmd/fleet/error.go
  cmd/fleet/handleAck.go
  cmd/fleet/handleArtifacts.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  internal/pkg/policy/parsed_policy.go
  internal/pkg/policy/parsed_policy_test.go
  internal/pkg/policy/parsed_policy_test_data.go
  internal/pkg/policy/policy_output.go
  internal/pkg/policy/policy_output_test.go
  internal/pkg/testing/bulk.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, v8.2.0, backport-v8.2.0

#1249 [automation] update elastic stack version for testing 8.1.1-c72e1d1e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1250 [automation] update elastic stack version for testing 7.17.2-81597e21
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1248 [automation] update elastic stack version for testing 8.2.0-63942b4d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1215 Remove unused VERSION file
  VERSION
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.3.0

#1255 [automation] update elastic stack version for testing 7.17.2-70a05b08
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1254 [automation] update elastic stack version for testing 8.2.0-4509f321
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1257 [automation] update elastic stack version for testing 8.1.2-2393b0c1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1258 [automation] update elastic stack version for testing 7.17.2-1941719d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1262 [automation] update elastic stack version for testing 8.1.2-5d446358
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1264 [automation] update elastic stack version for testing 7.17.2-cf7cf1eb
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1263 [automation] update elastic stack version for testing 8.1.2-d0bc828f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1261 [automation] update elastic stack version for testing 8.2.0-dcff22d7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1260 Logstash output fix
  CHANGELOG.next.asciidoc
  cmd/fleet/auth.go
  cmd/fleet/error.go
  cmd/fleet/handleAck.go
  cmd/fleet/handleArtifacts.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleEnroll.go
  internal/pkg/policy/parsed_policy.go
  internal/pkg/policy/parsed_policy_test.go
  internal/pkg/policy/parsed_policy_test_data.go
  internal/pkg/policy/policy_output.go
  internal/pkg/policy/policy_output_test.go
  internal/pkg/testing/bulk.go
Labels: Team:Elastic-Agent-Control-Plane, v8.2.0, backport-v8.2.0

#1269 [automation] update elastic stack version for testing 7.17.2-99f889e2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1268 [automation] update elastic stack version for testing 8.1.2-e94d7716
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1267 Use darwin-aarch64 artifact when building darwin
  .ci/scripts/test-release.sh
  CHANGELOG.next.asciidoc
  Makefile
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#1157 Default fleet policy removal
  CHANGELOG.next.asciidoc
  Makefile
  cmd/fleet/auth.go
  cmd/fleet/handleAck.go
  cmd/fleet/handleAck_test.go
  cmd/fleet/handleArtifacts.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleChecking_test.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/main_integration_test.go
  internal/pkg/cache/cache.go
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/config/fleet.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/coordinator/monitor_integration_test.go
  internal/pkg/coordinator/v0.go
  internal/pkg/coordinator/v0_test.go
  internal/pkg/dl/action_results_integration_test.go
  internal/pkg/dl/agent_integration_test.go
  internal/pkg/dl/enrollment_api_key.go
  internal/pkg/dl/enrollment_api_key_integration_test.go
  internal/pkg/dl/policies_integration_test.go
  internal/pkg/dl/policies_leader.go
  internal/pkg/dl/policies_leader_integration_test.go
  internal/pkg/dl/servers.go
  internal/pkg/dl/servers_integration_test.go
  internal/pkg/es/result_test.go
  internal/pkg/model/schema.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/policy/monitor_test.go
  internal/pkg/policy/policy_output.go
  internal/pkg/policy/revision.go
  internal/pkg/policy/self.go
  internal/pkg/policy/self_test.go
  internal/pkg/testing/actions.go
  main.go
  model/schema.json
Labels: enhancement, backport-skip, Team:Elastic-Agent-Control-Plane, v8.2.0

#1259 Align golangci-lint with elastic-agent/beats
  .github/workflows/golangci-lint.yml
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#1272 [automation] update elastic stack version for testing 7.17.2-a218ac35
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1271 [automation] update elastic stack version for testing 8.1.2-52f4e5e3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1234 ci: packaging pipeline for the snapshots
  .ci/packaging.groovy
  .ci/scripts/release-manager.sh
  Makefile
Labels: Team:Automation, backport-v8.2.0, backport-v8.1.0, backport-v7.17.0

#1274 ci: DRA enhancements
  .ci/packaging.groovy
  .ci/scripts/release-manager.sh
Labels: backport-v8.2.0, backport-v7.17.0
