Repository elastic/fleet-server, pull requests merged in 2022-06, with the labels that each got.

#1514 [automation] update elastic stack version for testing 7.17.5-7c990f83
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1513 [automation] update elastic stack version for testing 8.3.0-4644f7c7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1511 [automation] update elastic stack version for testing 8.4.0-481759a3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1512 [automation] update elastic stack version for testing 8.2.3-e78add13
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1516 [automation] update elastic stack version for testing 8.2.3-656a5d89
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1517 [automation] update elastic stack version for testing 8.3.0-17c7e5c0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1515 [automation] update elastic stack version for testing 8.4.0-df27a645
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1518 [automation] update elastic stack version for testing 7.17.5-a303ce60
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1521 [automation] update elastic stack version for testing 7.17.5-f01fee6a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1523 [automation] update elastic stack version for testing 8.2.3-f986a1ff
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1520 [automation] update elastic stack version for testing 8.3.0-378ebcca
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1522 [automation] update elastic stack version for testing 8.4.0-3525aaf7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1529 [automation] update elastic stack version for testing 7.17.5-572a2baf
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1530 [automation] update elastic stack version for testing 8.2.3-def79f93
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1531 [automation] update elastic stack version for testing 8.3.0-9596ee28
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1528 [automation] update elastic stack version for testing 8.4.0-42ce0eef
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1532 [automation] update elastic stack version for testing 7.17.5-1c762894
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1533 [automation] update elastic stack version for testing 8.4.0-b8fce3f8
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1534 [automation] update elastic stack version for testing 8.3.0-f530a93f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1538 [automation] update elastic stack version for testing 7.17.5-dae6f87e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1536 [automation] update elastic stack version for testing 8.4.0-64eb2b35
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1539 [automation] update elastic stack version for testing 8.2.3-7def4c60
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1537 [automation] update elastic stack version for testing 8.3.0-f13a89b4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1543 [automation] update elastic stack version for testing 8.3.0-3c22a7f7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1544 [automation] update elastic stack version for testing 8.2.3-a46e98e9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1542 [automation] update elastic stack version for testing 8.4.0-3a09e26c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1546 [automation] update elastic stack version for testing 8.2.3-303333da
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1547 [automation] update elastic stack version for testing 8.4.0-a27cbcfa
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1545 [automation] update elastic stack version for testing 8.3.0-158b3cba
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1549 [automation] update elastic stack version for testing 8.2.3-4b95b897
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1550 [automation] update elastic stack version for testing 8.4.0-3bedeef4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1551 [automation] update elastic stack version for testing 8.3.0-db012561
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1552 Fix mergify for 8.3.0
  .mergify.yml
Labels: Team:Elastic-Agent-Control-Plane

#1553 [automation] update elastic stack version for testing 8.2.3-b55b20b5
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1554 [automation] update elastic stack version for testing 8.3.0-e4e76686
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1555 [automation] update elastic stack version for testing 8.4.0-7e67f5d9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1557 [automation] update elastic stack version for testing 8.3.0-460dc667
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1556 [automation] update elastic stack version for testing 8.4.0-40cff009
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1558 Update to 8.2.4
  main.go
Labels: Team:Elastic-Agent-Control-Plane

#1561 [automation] update elastic stack version for testing 8.3.0-fe62331f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1560 [automation] update elastic stack version for testing 8.4.0-5e6770b1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1563 [automation] update elastic stack version for testing 8.2.4-4cc4fbfd
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1566 [automation] update elastic stack version for testing 8.4.0-da5a1c6d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1565 [automation] update elastic stack version for testing 8.2.4-01ccaf06
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1571 [automation] update elastic stack version for testing 8.2.4-698e06ec
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1570 [automation] update elastic stack version for testing 8.3.0-75d7500e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1569 [automation] update elastic stack version for testing 8.4.0-b13123ee
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1572 [automation] update elastic stack version for testing 8.2.4-b657c8f5
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1573 [automation] update elastic stack version for testing 8.3.0-6d4bb852
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1576 [automation] update elastic stack version for testing 8.3.0-e0057e17
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1580 [automation] update elastic stack version for testing 7.17.5-8b932302
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1579 [automation] update elastic stack version for testing 8.4.0-4fe26f2a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1583 [automation] update elastic stack version for testing 8.4.0-2e32a640
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1584 [automation] update elastic stack version for testing 8.3.0-47d97929
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1585 [automation] update elastic stack version for testing 8.2.4-b5aa40e4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1586 [automation] update elastic stack version for testing 7.17.5-8d9f50d0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1582 ci: enable build notifications as GitHub issues
  .ci/Jenkinsfile
Labels: automation, backport-v8.3.0, backport-v7.17.0

#1592 [automation] update elastic stack version for testing 8.4.0-722a7d79
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1593 [automation] update elastic stack version for testing 7.17.5-781a81f2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1590 [automation] update elastic stack version for testing 8.3.0-3b390c7b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1591 [automation] update elastic stack version for testing 8.2.4-32b57cbe
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1598 [automation] update elastic stack version for testing 7.17.5-3896ff07
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1601 [automation] update elastic stack version for testing 8.2.4-b7bb3a0c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1600 [automation] update elastic stack version for testing 8.3.0-fdf97a2e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1599 [automation] update elastic stack version for testing 8.4.0-210dd487
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1594 mergify: remove backport automation for non active branches
  .mergify.yml
Labels: automation, Team:Automation

#1589 ci: enable flaky test detector
  .ci/Jenkinsfile
Labels: backport-v8.3.0, backport-v7.17.0

#1606 [automation] update elastic stack version for testing 8.4.0-a6aa9f3b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1607 [automation] update elastic stack version for testing 8.2.4-9b981623
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1610 8.3.1 update
  version/version.go
Labels: Team:Elastic-Agent-Control-Plane

#1616 [automation] update elastic stack version for testing 7.17.5-b5794350
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1615 [automation] update elastic stack version for testing 8.3.0-729c5564
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1614 [automation] update elastic stack version for testing 8.4.0-4ec2d3b3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1613 [automation] update elastic stack version for testing 8.2.4-62f5ece5
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1619 [automation] update elastic stack version for testing 8.4.0-86cc80f3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1621 [automation] update elastic stack version for testing 8.3.1-b95de5e6
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1620 [automation] update elastic stack version for testing 8.2.4-e7c42e26
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1540 Update Readme with instructions to run fleet-server on Vagrant
  .gitignore
  Makefile
  README.md
  Vagrantfile
  cmd/fleet/main.go
  internal/pkg/api/auth.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleEnroll.go
  internal/pkg/bulk/opApiKey.go
  internal/pkg/es/client.go
  internal/pkg/monitor/monitor.go
  internal/pkg/rollback/rollback.go
Labels: documentation, enhancement

#1618 Update to 8.3.2
  version/version.go
Labels: Team:Elastic-Agent-Control-Plane

#1605 On Fleet Server reboot gives a grace period
  CHANGELOG.next.asciidoc
  internal/pkg/coordinator/monitor.go
  internal/pkg/coordinator/monitor_integration_test.go
Labels: Team:Elastic-Agent-Control-Plane
