Repository elastic/fleet-server, pull requests merged in 2022-08, with the labels that each got.

#1702 [automation] update elastic stack version for testing 7.17.6-74b6df3e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1703 [automation] update elastic stack version for testing 8.4.0-d88c8a44
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1705 [automation] update elastic stack version for testing 8.4.0-5954f776
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1706 [automation] update elastic stack version for testing 8.5.0-c54c3404
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1707 [automation] update elastic stack version for testing 8.3.4-9c50d4cb
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1708 [automation] update elastic stack version for testing 8.5.0-7dbc10f8
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1710 [automation] update elastic stack version for testing 7.17.6-02b91d00
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1711 [automation] update elastic stack version for testing 8.3.4-a15c6beb
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1712 [automation] update elastic stack version for testing 7.17.6-308858b9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1713 [automation] update elastic stack version for testing 8.3.4-ce266bfe
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1714 [automation] update elastic stack version for testing 8.4.0-b5074ef3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1715 [automation] update elastic stack version for testing 8.4.0-43c061d1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1717 [automation] update elastic stack version for testing 7.17.6-39f8da8e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1721 [automation] update elastic stack version for testing 7.17.6-49d2f2df
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1719 [automation] update elastic stack version for testing 8.3.4-9c6c318b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1720 [automation] update elastic stack version for testing 8.4.0-4b3e8f6e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1723 [automation] update elastic stack version for testing 7.17.6-a65acb36
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1722 [automation] update elastic stack version for testing 8.4.0-96568c7b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1724 [automation] update elastic stack version for testing 8.3.4-fd43be48
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1726 [automation] update elastic stack version for testing 8.4.0-9adc8090
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1727 [automation] update elastic stack version for testing 8.3.4-b4aa6143
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1725 [automation] update elastic stack version for testing 8.5.0-41aadc32
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1728 [automation] update elastic stack version for testing 7.17.6-e11a9305
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1709 [automation] Update go release version 1.18.5
  .go-version
  Dockerfile.build
  Makefile
Labels: automation, dependency, backport-v8.5.0

#1733 [automation] update elastic stack version for testing 8.4.0-c17572db
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1734 [automation] update elastic stack version for testing 8.5.0-60a4c029
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1732 [automation] update elastic stack version for testing 8.3.4-a5e24e15
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1735 [automation] update elastic stack version for testing 7.17.6-9b06d311
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1737 [automation] update elastic stack version for testing 8.3.4-adc3e57f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1671 Log redacted config on config changes
  CHANGELOG.next.asciidoc
  cmd/fleet/main.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#1740 [automation] update elastic stack version for testing 7.17.6-efe703c7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1742 [automation] update elastic stack version for testing 8.4.0-fea9abbe
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1741 [automation] update elastic stack version for testing 8.3.4-6d6eaf28
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1739 Protect access to policiesCanceller using a mutext
  CHANGELOG.next.asciidoc
  internal/pkg/bulk/bulk_test.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/coordinator/monitor_integration_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.3.0, backport-v8.4.0, backport-v8.5.0

#1750 [automation] update elastic stack version for testing 7.17.6-03b746cb
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1748 [automation] update elastic stack version for testing 8.4.0-9bd354a1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1749 [automation] update elastic stack version for testing 8.3.4-58ddca7b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1747 Support for Elastic Agent V2 status
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/schema.go
  internal/pkg/checkin/bulk.go
  internal/pkg/checkin/bulk_test.go
  internal/pkg/dl/constants.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: enhancement

#1753 [automation] update elastic stack version for testing 7.17.6-202119fd
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1752 [automation] update elastic stack version for testing 8.4.0-aff0df12
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1755 [automation] update elastic stack version for testing 7.17.6-091e6fb1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1757 [automation] update elastic stack version for testing 8.3.4-e23a59c6
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1758 [automation] update elastic stack version for testing 8.4.0-b95305c2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1756 [automation] update elastic stack version for testing 8.5.0-6b9f92c0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1763 [automation] update elastic stack version for testing 7.17.6-b8ca5a33
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1762 [automation] update elastic stack version for testing 8.3.4-70c0b53c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1761 [automation] update elastic stack version for testing 8.4.0-910fe5e1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1760 [automation] update elastic stack version for testing 8.5.0-0616acda
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1767 [automation] update elastic stack version for testing 7.17.6-a9c53531
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1766 [automation] update elastic stack version for testing 8.4.0-7f4eb04b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1765 [automation] update elastic stack version for testing 8.5.0-dd6f2bb0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1764 [automation] update elastic stack version for testing 8.3.4-45336fec
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1770 [automation] update elastic stack version for testing 7.17.6-4816e9ef
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1771 [automation] update elastic stack version for testing 8.4.0-fa661330
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1769 [automation] update elastic stack version for testing 8.3.4-97a7bb79
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1768 [automation] update elastic stack version for testing 8.5.0-feb644de
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1692 [Release] Update version to 8.4.1
  version/version.go
Labels: Team:Automation, release

#1772 Update version to 7.17.7
  main.go
Labels: Team:Elastic-Agent-Control-Plane

#1777 [automation] update elastic stack version for testing 8.3.4-5621f166
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1776 [automation] update elastic stack version for testing 8.5.0-7783a03c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1778 [automation] update elastic stack version for testing 7.17.6-c5d77a20
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1781 [automation] update elastic stack version for testing 8.4.1-74c5d538
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1780 [automation] update elastic stack version for testing 8.5.0-17b8a62d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1782 [automation] update elastic stack version for testing 8.3.4-22a90cba
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1783 [automation] update elastic stack version for testing 8.4.1-14f69e2b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1784 [automation] update elastic stack version for testing 8.5.0-9aed3b11
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1785 [automation] update elastic stack version for testing 8.3.4-6089c81a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1786 [automation] update elastic stack version for testing 7.17.7-a3635a2e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1751 [v2] Switch to Elastic Agent v2 control protocol
  NOTICE.txt
  cmd/fleet/main.go
  cmd/fleet/main_integration_test.go
  cmd/fleet/server_integration_test.go
  go.mod
  go.sum
  internal/pkg/api/handleStatus.go
  internal/pkg/api/handleStatus_test.go
  internal/pkg/logger/logger.go
  internal/pkg/policy/policy_output_test.go
  internal/pkg/policy/self.go
  internal/pkg/policy/self_test.go
  internal/pkg/state/reporter.go
  internal/pkg/status/reporter.go
Labels: Team:Elastic-Agent-Control-Plane

#1787 [automation] update elastic stack version for testing 8.4.1-b72ec52c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1788 [automation] update elastic stack version for testing 8.5.0-440e0896
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1789 [automation] update elastic stack version for testing 7.17.7-18723602
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1775 [Release] Update version to 8.4.2
  version/version.go
Labels: Team:Automation, release

#1792 [automation] update elastic stack version for testing 8.4.1-65181fd0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1791 [automation] update elastic stack version for testing 8.5.0-fedc3e60
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
