Repository elastic/fleet-server, pull requests merged in 2022-02, with the labels that each got.

#1121 [automation] update elastic stack version for testing 8.0.0-09bea260
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1004 [Release] Bump version to 7.17.1
  main.go
Labels: Team:Automation, backport-skip

#1122 [automation] update elastic stack version for testing 7.17.1-7ef8bcb5
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1125 Update master branch to 8.2.0
  .mergify.yml
  main.go
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#1127 [automation] update elastic stack version for testing 7.17.1-aa300c4a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1126 [automation] update elastic stack version for testing 8.0.0-56a14b95
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1112 update main references
  .ci/jobs/fleet-server.yml
  .mergify.yml
  README.md
  dev-tools/cherrypick_pr
Labels: backport-v8.0.0, backport-v7.17.0

#1133 [automation] update elastic stack version for testing 8.0.0-1018d5a4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1074 [automation] Update go release version 1.17.6
  .go-version
Labels: automation, dependency, backport-skip

#1135 [automation] update elastic stack version for testing 7.17.1-f7e4bfc6
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1136 [automation] update elastic stack version for testing 8.1.0-815726c3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1138 [automation] update elastic stack version for testing 7.17.1-48ecd1f2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1139 [automation] update elastic stack version for testing 8.1.0-98e72485
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1141 Add github action for automating QA labels
  .github/workflows/qa-labels.yml
Labels: automation, backport-skip, Team:Elastic-Agent-Control-Plane

#1140 [automation] update elastic stack version for testing 8.2.0-ff5ac1e4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1146 [automation] update elastic stack version for testing 7.17.1-d1501547
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1145 [automation] update elastic stack version for testing 8.1.0-9063dd89
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1143 [automation] Update go release version 1.17.7
  .go-version
Labels: automation, dependency, backport-v8.2.0, backport-v8.1.0

#1149 [automation] update elastic stack version for testing 8.1.0-c6173806
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1148 ci: notify stages in the CI with GitHub checks
  .ci/Jenkinsfile
Labels: backport-v8.0.0, backport-v8.1.0

#1151 [automation] update elastic stack version for testing 7.17.1-9bbee73a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1154 [automation] update elastic stack version for testing 8.1.0-732c5a10
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1158 [automation] update elastic stack version for testing 8.1.0-6dfec5b9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1162 [automation] update elastic stack version for testing 8.1.0-3aaf806b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1168 [automation] update elastic stack version for testing 8.1.0-03fdea33
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1169 [automation] update elastic stack version for testing 8.2.0-313c1e34
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1165 Add Golangci-lint as a linter using the github-action
  .github/workflows/golangci-lint.yml
  .github/workflows/project-assigner.yml
  .golangci.yml
Labels: backport-v8.0.0, Team:Elastic-Agent-Control-Plane, backport-v8.2.0, backport-v8.3.0, backport-v8.1.0, backport-v7.17.0

#1173 [automation] update elastic stack version for testing 8.1.0-6704585f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1172 [automation] update elastic stack version for testing 8.2.0-c2195520
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1164 Populate action_input_type for the .fleet-actions-results
  cmd/fleet/handleAck.go
  cmd/fleet/handleAck_test.go
  cmd/fleet/schema.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#1175 [automation] update elastic stack version for testing 7.17.1-952e96f1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1176 [automation] update elastic stack version for testing 8.1.0-f6199768
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1147 ci: enable upload artifacts
  .ci/Jenkinsfile
Labels: backport-v8.0.0, backport-v8.1.0

#1160 Bump version to 7.17.2
  main.go
Labels: backport-skip, release

#1166 Refactor make check
  .ci/Jenkinsfile
  Makefile
Labels: backport-v8.0.0, Team:Elastic-Agent-Control-Plane, backport-v8.2.0, backport-v8.3.0, backport-v8.1.0, backport-v7.17.0
