Repository elastic/fleet-server, pull requests merged in 2022-04, with the labels that each got.

#1283 [automation] update elastic stack version for testing 7.17.3-22be2d34
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1284 [automation] update elastic stack version for testing 8.1.2-ed029c28
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1282 [automation] update elastic stack version for testing 8.3.0-1ecd9720
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1281 [automation] update elastic stack version for testing 8.2.0-5d1042d1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1287 Revert "Default fleet policy removal"
  CHANGELOG.next.asciidoc
  Makefile
  cmd/fleet/auth.go
  cmd/fleet/handleAck.go
  cmd/fleet/handleAck_test.go
  cmd/fleet/handleArtifacts.go
  cmd/fleet/handleCheckin.go
  cmd/fleet/handleChecking_test.go
  cmd/fleet/handleEnroll.go
  cmd/fleet/main_integration_test.go
  internal/pkg/cache/cache.go
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/config/fleet.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/coordinator/monitor_integration_test.go
  internal/pkg/coordinator/v0.go
  internal/pkg/coordinator/v0_test.go
  internal/pkg/dl/action_results_integration_test.go
  internal/pkg/dl/agent_integration_test.go
  internal/pkg/dl/enrollment_api_key.go
  internal/pkg/dl/enrollment_api_key_integration_test.go
  internal/pkg/dl/policies_integration_test.go
  internal/pkg/dl/policies_leader.go
  internal/pkg/dl/policies_leader_integration_test.go
  internal/pkg/dl/servers.go
  internal/pkg/dl/servers_integration_test.go
  internal/pkg/es/result_test.go
  internal/pkg/model/schema.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/policy/monitor_test.go
  internal/pkg/policy/policy_output.go
  internal/pkg/policy/revision.go
  internal/pkg/policy/self.go
  internal/pkg/policy/self_test.go
  internal/pkg/testing/actions.go
  main.go
  model/schema.json
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#1292 fix: update mergify's base branch for 8.1 and 8.2
  .mergify.yml
Labels: bug, Team:Automation, backport-skip

#1295 [automation] update elastic stack version for testing 7.17.3-42e5086c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1294 [automation] update elastic stack version for testing 8.3.0-4cd86339
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1296 [automation] update elastic stack version for testing 8.2.0-f531236e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1297 Remove windows and darwin linting
  .github/workflows/golangci-lint.yml
Labels: backport-v8.2.0, backport-v8.3.0

#1270 Update Go dependencies
  NOTICE.txt
  cmd/fleet/main_integration_test.go
  dev-tools/buildlimits/buildlimits.go
  dev-tools/notice/overrides.json
  dev-tools/notice/rules.json
  go.mod
  go.sum
  internal/pkg/config/env_defaults.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0, backport-v8.3.0

#1280 ci: daily release artifacts for staging
  .ci/packaging.groovy
Labels: backport-v8.2.0, backport-v8.3.0, backport-v7.17.0

#1299 Always add `api_key` to Elasticsearch output
  cmd/fleet/handleCheckin.go
  internal/pkg/policy/policy_output.go
  internal/pkg/policy/policy_output_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0, backport-v8.3.0

#1308 [automation] update elastic stack version for testing 7.17.3-206df1ed
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1311 [automation] update elastic stack version for testing 8.1.3-4eb9bf7f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1307 Flaky test enrollment_api_key_integration_test.go
  internal/pkg/dl/enrollment_api_key_integration_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0, backport-v8.3.0

#1309 [automation] update elastic stack version for testing 8.3.0-657f2d50
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1310 [automation] update elastic stack version for testing 8.2.0-12b59372
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1318 [automation] update elastic stack version for testing 7.17.3-60b577ee
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1317 [automation] update elastic stack version for testing 8.1.3-c3f4b7e6
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1315 [automation] update elastic stack version for testing 8.3.0-00f4f855
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1316 [automation] update elastic stack version for testing 8.2.0-fdfc79e3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1323 [automation] update elastic stack version for testing 7.17.3-0bbada2a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1321 [automation] update elastic stack version for testing 8.1.3-6f211282
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1322 [automation] update elastic stack version for testing 8.2.0-c56d8262
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1320 [automation] update elastic stack version for testing 8.3.0-5bb6f468
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1327 [automation] update elastic stack version for testing 7.17.3-2d046908
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1326 [automation] update elastic stack version for testing 8.1.3-25093d2a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1324 [automation] update elastic stack version for testing 8.2.0-4df380a5
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1325 [automation] update elastic stack version for testing 8.3.0-76e0128f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1331 [automation] update elastic stack version for testing 7.17.3-4c0e3956
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1332 [automation] update elastic stack version for testing 8.1.3-91a16370
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1330 [automation] update elastic stack version for testing 8.2.0-bcbc1a13
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1329 [automation] update elastic stack version for testing 8.3.0-8d19ff01
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1319 Refactor: move files from cmd/fleet to pkg/api
  .golangci.yml
  cmd/fleet/main.go
  cmd/fleet/server_integration_test.go
  internal/pkg/api/auth.go
  internal/pkg/api/error.go
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleAck_test.go
  internal/pkg/api/handleArtifacts.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleChecking_test.go
  internal/pkg/api/handleEnroll.go
  internal/pkg/api/handleStatus.go
  internal/pkg/api/handleStatus_test.go
  internal/pkg/api/metrics.go
  internal/pkg/api/router.go
  internal/pkg/api/schema.go
  internal/pkg/api/server.go
  internal/pkg/api/server_test.go
  internal/pkg/api/userAgent.go
  internal/pkg/api/userAgent_test.go
  internal/pkg/build/build.go
Labels: cleanup, Team:Elastic-Agent-Control-Plane, backport-v8.3.0

#1335 [automation] update elastic stack version for testing 7.17.3-860249fc
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1336 [automation] update elastic stack version for testing 8.1.3-9689383f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1342 [automation] update elastic stack version for testing 7.17.3-b688e1c0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1341 [automation] update elastic stack version for testing 8.1.3-f8a17b61
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1343 [automation] update elastic stack version for testing 8.2.0-a99722cc
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1344 Create elastic-agent-project-board.yml
  .github/workflows/elastic-agent-project-board.yml
Labels: backport-skip

#1348 [automation] update elastic stack version for testing 8.1.3-bb164e02
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1349 [automation] update elastic stack version for testing 7.17.3-d599ee07
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1347 [automation] update elastic stack version for testing 8.2.0-39d3fe7f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1346 [automation] update elastic stack version for testing 8.3.0-4be61f32
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1333 Copy `licenses` package to fleet-server
  dev-tools/buildlimits/buildlimits.go
  dev-tools/cmd/license/license_generate.go
  licenses/APACHE-LICENSE-2.0-header.txt
  licenses/APACHE-LICENSE-2.0.txt
  licenses/ELASTIC-LICENSE-2.0-header.txt
  licenses/ELASTIC-LICENSE-2.0.txt
  licenses/ELASTIC-LICENSE-header.txt
  licenses/ELASTIC-LICENSE.txt
  licenses/license.go
  licenses/license_header.go
Labels: backport-v8.3.0

#1356 [automation] update elastic stack version for testing 7.17.3-a0d290fb
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1354 [automation] update elastic stack version for testing 8.1.3-5c80e943
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1353 [automation] update elastic stack version for testing 8.3.0-55ba6f37
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1355 [automation] update elastic stack version for testing 8.2.0-edf55ea1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1357 [automation] update elastic stack version for testing 7.17.3-feda78d8
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1359 [automation] update elastic stack version for testing 8.1.3-28740185
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1363 [automation] update elastic stack version for testing 8.1.3-2a8b1f31
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1358 [automation] update elastic stack version for testing 8.3.0-c655cda8
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1361 [automation] update elastic stack version for testing 8.2.0-3a7e2f99
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1369 [automation] update elastic stack version for testing 8.1.3-0c4e7b42
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1370 [automation] update elastic stack version for testing 7.17.3-b148b9ca
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1328 Linting - field renaming
  Makefile
  cmd/fleet/main_integration_test.go
  internal/pkg/api/auth.go
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleAck_test.go
  internal/pkg/api/handleArtifacts.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleChecking_test.go
  internal/pkg/api/handleEnroll.go
  internal/pkg/cache/cache.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/coordinator/monitor_integration_test.go
  internal/pkg/coordinator/v0.go
  internal/pkg/coordinator/v0_test.go
  internal/pkg/dl/action_results.go
  internal/pkg/dl/action_results_integration_test.go
  internal/pkg/dl/actions.go
  internal/pkg/dl/agent.go
  internal/pkg/dl/agent_integration_test.go
  internal/pkg/dl/constants.go
  internal/pkg/dl/enrollment_api_key.go
  internal/pkg/dl/enrollment_api_key_integration_test.go
  internal/pkg/dl/policies.go
  internal/pkg/dl/policies_integration_test.go
  internal/pkg/dl/policies_leader.go
  internal/pkg/dl/policies_leader_integration_test.go
  internal/pkg/dl/seqno.go
  internal/pkg/dl/servers.go
  internal/pkg/dl/servers_integration_test.go
  internal/pkg/es/result_test.go
  internal/pkg/model/schema.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/policy/monitor_test.go
  internal/pkg/policy/policy_output.go
  internal/pkg/policy/policy_output_test.go
  internal/pkg/policy/revision.go
  internal/pkg/policy/self.go
  internal/pkg/policy/self_test.go
  internal/pkg/testing/actions.go
  main.go
Labels: cleanup, backport-skip, Team:Elastic-Agent-Control-Plane

#1368 [automation] update elastic stack version for testing 8.2.0-a7e9513d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1367 [automation] update elastic stack version for testing 8.3.0-e0f27b1a
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1337 Bump 8.1.4
  main.go
Labels: backport-skip

#1365 Update Golangci-lint to 1.45.2
  .github/workflows/golangci-lint.yml
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#1375 [automation] update elastic stack version for testing 7.17.3-e9aee937
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1366 Update Go 1.17.9
  .go-version
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.2.0

#1374 [automation] update elastic stack version for testing 8.3.0-55bd5fae
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1373 [automation] update elastic stack version for testing 8.2.0-000e1c18
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1379 Revert "[7.17](backport #1366) Update Go 1.17.9"
  .go-version
Labels: Team:Elastic-Agent-Control-Plane

#1388 [automation] update elastic stack version for testing 8.1.4-bc369beb
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1384 [automation] update elastic stack version for testing 7.17.4-51efa5cc
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1385 [automation] update elastic stack version for testing 8.2.0-c47183cf
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1383 [automation] update elastic stack version for testing 8.3.0-04455a76
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1372 ci: split dra meta-stage in two stages
  .ci/packaging.groovy
Labels: automation, backport-v8.2.0, backport-v8.3.0, backport-v8.1.0, backport-v7.17.0

#1390 [automation] update elastic stack version for testing 8.3.0-99e29e67
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1392 [automation] update elastic stack version for testing 7.17.4-4d7a6e74
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1398 [automation] update elastic stack version for testing 8.1.4-96de35ab
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1396 [automation] update elastic stack version for testing 8.3.0-ed7759bd
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1397 [automation] update elastic stack version for testing 8.2.0-63f66f47
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1399 [automation] update elastic stack version for testing 7.17.4-073e030e
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1400 [automation] update elastic stack version for testing 8.1.4-483e60fd
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1402 [automation] update elastic stack version for testing 8.3.0-6b041601
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1405 [automation] update elastic stack version for testing 8.2.0-8b4cfac3
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1404 [automation] update elastic stack version for testing 8.3.0-cb2ce38c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1407 [automation] update elastic stack version for testing 8.1.4-7b3e4fd0
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1409 [automation] update elastic stack version for testing 7.17.4-40d3b33d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1408 [automation] update elastic stack version for testing 8.3.0-194e3512
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
