Repository elastic/fleet-server, pull requests merged in 2023-06, with the labels that each got.

#2652 add a comment-driven trigger for tests of the downstream pipeline
  .buildkite/pull-requests.json
Labels: ci

#2660 [updatecli] update elastic stack version for testing 7.17.11-b78588c3-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2658 [updatecli] update elastic stack version for testing 8.8.1-951ef2b6-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2661 [updatecli] update elastic stack version for testing 7.17.11-a516d267-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2662 [updatecli] update elastic stack version for testing 8.8.1-afb32ff1-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2657 Bump elastic-agent-client to v7.1.2
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-v8.8.0

#2670 [updatecli] update elastic stack version for testing 7.17.11-50dd0ed0-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2672 Update make generate with new oapi release
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/api/openapi.gen.go
  pkg/api/client.gen.go
  pkg/api/types.gen.go
  testing/go.mod
  testing/go.sum
Labels: Team:Fleet, tech debt

#2664 Add step to trigger gitops to update image
  .buildkite/pipeline.yml
Labels: Team:Fleet, ci

#2665 Add unit test to check if configFromUnits handles multiple hosts
  internal/pkg/server/agent_test.go
Labels: bug, Team:Fleet, Team:Elastic-Agent-Control-Plane

#2675 [updatecli] update elastic stack version for testing 7.17.11-ba9a7d5f-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2674 [updatecli] update elastic stack version for testing 8.9.0-9046815c-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2673 [Release] 8.8.1 changelog
  Makefile
  changelog/8.8.1.asciidoc
  changelog/8.8.1.yaml
  changelog/fragments/1668434027-Accept-raw-errors-as-a-fallback-to-detailed-error-type.yaml
  changelog/fragments/1671566400-filter-out-UPDATE_TAGS-and-FORCE_UNENROLL.yaml
  changelog/fragments/1672689600-remove-automatic-agent-unenrollment.yaml
  changelog/fragments/1673467200-replaced-upgrade-expiration-and-minimum_execution_time.yaml
  changelog/fragments/1673553600-document-how-to-run-fleet-server-locally.yaml
  changelog/fragments/1674244800-fleet-server-file-upload.yaml
  changelog/fragments/1676500216-pass_action_signature.yaml
  changelog/fragments/1677009600-fix-fleet-server-discard-keys.yaml
  changelog/fragments/1678132800-fleet-server-stand-alone-no-kibana.yaml
  changelog/fragments/1680807600-isolate-logger-restart.yaml
  changelog/fragments/1680807600-secret-files.yaml
  changelog/fragments/1681246555-Add-poll_duration-to-checkin-requests.yaml
  changelog/fragments/1681412400-action-apm-tracing.yaml
  changelog/fragments/1681906741-memory_limit.yaml
  changelog/fragments/1685037431-Add-config-diagnostics-hook.yaml
Labels: Team:Fleet, docs, release

#2667 [Release] Update version to 8.8.2
  version/version.go
Labels: Team:Automation, release

#2678 Update dependencies in Component
  catalog-info.yaml
Labels: ci

#2681 [updatecli] update elastic stack version for testing 8.9.0-f7b4ff02-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2676 Pin oapi version used in generate command
  Makefile
Labels: Team:Fleet, tech debt

#2682 Remove newlines filter_condition setting
  catalog-info.yaml
Labels: ci

#2666 File delivery
  NOTICE.txt
  changelog/fragments/1685985303-file-delivery.yaml
  go.mod
  go.sum
  internal/pkg/api/api.go
  internal/pkg/api/error.go
  internal/pkg/api/handleFileDelivery.go
  internal/pkg/api/metrics.go
  internal/pkg/api/openapi.gen.go
  internal/pkg/api/router.go
  internal/pkg/api/router_test.go
  internal/pkg/api/server.go
  internal/pkg/api/server_test.go
  internal/pkg/config/env_defaults.go
  internal/pkg/config/limits.go
  internal/pkg/file/cbor/decode.go
  internal/pkg/file/cbor/decode_test.go
  internal/pkg/file/delivery/delivery.go
  internal/pkg/file/delivery/doc.go
  internal/pkg/file/delivery/es.go
  internal/pkg/file/es.go
  internal/pkg/file/es_test.go
  internal/pkg/file/file.go
  internal/pkg/file/uploader/finalize.go
  internal/pkg/server/fleet.go
  model/openapi.yml
  pkg/api/client.gen.go
Labels: enhancement, Team:Fleet

#2656 fix condition for the docker push step
  .buildkite/pipeline.yml
Labels: ci

#2687 [updatecli] update elastic stack version for testing 7.17.11-777002b0-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2668 [updatecli] update elastic stack version for testing 8.8.2-3ed30946-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2677 [Fleet] Add elastic-api-version support
  internal/pkg/api/apiVersion.go
  internal/pkg/api/apiVersion_test.go
  internal/pkg/api/error.go
  internal/pkg/api/openapi.gen.go
  internal/pkg/api/router.go
  model/openapi.yml
  pkg/api/client.gen.go
  pkg/api/types.gen.go
Labels: Team:Fleet

#2686 [updatecli] update elastic stack version for testing 8.9.0-f766627c-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2685 add the canceling and skipping intermediate builds for the triggered …
  catalog-info.yaml
Labels: ci

#2691 [updatecli] update elastic stack version for testing 8.9.0-37a365f9-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2695 [updatecli] update elastic stack version for testing 7.17.11-e46e5ca7-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2694 [updatecli] update elastic stack version for testing 8.8.2-157bf445-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2688 [Fleet] Add e2e tests for api versions
  internal/pkg/api/apiVersion.go
  pkg/api/versions/2022_06_01/api/client.gen.go
  pkg/api/versions/2022_06_01/api/types.gen.go
  sonar-project.properties
  testing/e2e/agent_container_test.go
  testing/e2e/api_version/api_version.go
  testing/e2e/api_version/client_api_2023_06_01.go
  testing/e2e/api_version/client_api_current.go
  testing/e2e/stand_alone_test.go
Labels: Team:Fleet

#2655 Using enrollment Id in agent enroll to delete duplicate agent on failed enroll
  internal/pkg/api/handleEnroll.go
  internal/pkg/api/handleEnroll_test.go
  internal/pkg/api/openapi.gen.go
  internal/pkg/dl/agent.go
  internal/pkg/dl/agent_test.go
  internal/pkg/dl/constants.go
  internal/pkg/model/schema.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/testing/fleet-server-testing.yml
  model/openapi.yml
  model/schema.json
  pkg/api/types.gen.go
  sonar-project.properties
Labels: enhancement

#2699 [updatecli] update elastic stack version for testing 8.9.0-fefa3eb8-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2703 [updatecli] update elastic stack version for testing 7.17.11-6470dfa7-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2701 [updatecli] update elastic stack version for testing 8.8.2-0c8e2646-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2704 [updatecli] update elastic stack version for testing 8.9.0-473a43eb-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2698 Add missing changelog fragment
  changelog/fragments/1686781749-Add-elastic-api-version-header-support.yaml
Labels: Team:Fleet, tech debt

#2707 [updatecli] update elastic stack version for testing 7.17.11-4433090a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2709 [updatecli] update elastic stack version for testing 8.9.0-9ee1e6fb-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2713 [updatecli] update elastic stack version for testing 7.17.11-8753e430-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2711 [updatecli] update elastic stack version for testing 8.8.2-6bda6fd3-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2697 Reuse error channel
  changelog/fragments/1686780651-reuse-error-channel.yaml
  internal/pkg/server/agent.go
  internal/pkg/server/agent_integration_test.go
  internal/pkg/server/fleet.go
  internal/pkg/server/fleet_integration_test.go
Labels: bug, Team:Fleet

#2684 [Automation] Bump Golang version to 1.20.5
  .buildkite/pipeline.yml
  .go-version
  .golangci.yml
  go.sum
Labels: backport-skip

#2714 Add config for main Buildkite pipeline
  .buildkite/hooks/post-checkout
  .ci/bump-golang.yml
Labels: Team:Fleet

#2716 [updatecli] update elastic stack version for testing 7.17.11-57933c35-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2718 [updatecli] update elastic stack version for testing 8.8.2-c9f8756a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2717 [updatecli] update elastic stack version for testing 8.9.0-0032a096-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2692 add delivery module tests
  internal/pkg/api/handleFileDelivery.go
  internal/pkg/api/handleFileDelivery_test.go
  internal/pkg/api/handleUpload_test.go
  internal/pkg/file/delivery/delivery_test.go
  internal/pkg/file/delivery/es.go
Labels: cleanup, v8.9.0, 8.9-candidate

#2720 Bump the version on main to 8.10.0
  version/version.go
Labels: backport-skip

#2729 add the trigger package-registry pipeline
  .buildkite/pipeline.yml
Labels: ci

#2651 package step
  .buildkite/hooks/post-checkout
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/pipeline.package.mbp.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/package.sh
Labels: ci

#2733 [updatecli] update elastic stack version for testing 8.8.2-c7e9ae2e-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2728 [8.9](backport #2692) Adds delivery module tests
  internal/pkg/api/handleFileDelivery.go
  internal/pkg/api/handleFileDelivery_test.go
  internal/pkg/api/handleUpload_test.go
  internal/pkg/file/delivery/delivery_test.go
  internal/pkg/file/delivery/es.go
Labels: backport

#2737 [updatecli] update elastic stack version for testing 7.17.11-706e8811-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2736 [updatecli] update elastic stack version for testing 8.8.2-652417ba-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2739 [updatecli] update elastic stack version for testing 7.17.11-ee6563d4-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2740 [updatecli] update elastic stack version for testing 8.8.2-33f1abe8-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2727 [updatecli] update elastic stack version for testing 8.10.0-aaab0171-SNAPSHOT
  dev-tools/integration/.env
  version/version.go
Labels: automation, dependency, backport-skip

#2746 [updatecli] update elastic stack version for testing 8.8.2-438a24ff-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2747 [updatecli] update elastic stack version for testing 8.10.0-9fc07504-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2744 Update apm to v2.4.3
  NOTICE.txt
  go.mod
  go.sum
Labels: bug, Team:Fleet, flaky-test

#2719 [Release] Update version to 8.8.3
  version/version.go
Labels: Team:Automation, release

#2715 [Release] Update version to 7.17.12
  main.go
Labels: Team:Automation, release

#2750 [updatecli] update elastic stack version for testing 7.17.11-670b6a4a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2752 [updatecli] update elastic stack version for testing 8.8.2-41f17f3c-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2751 [updatecli] update elastic stack version for testing 8.10.0-759b2cb2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2702 Dra snapshot stage
  .buildkite/hooks/post-checkout
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/pipeline.package.mbp.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/dra_snapshot.sh
  .buildkite/scripts/release-manager.sh
  catalog-info.yaml
Labels: ci

#2735 get the go version from the .go-version file
  .buildkite/hooks/post-checkout
  .buildkite/pipeline.yml
  .buildkite/pull-requests.json
Labels: ci

#2732 [updatecli] update elastic stack version for testing 8.9.0-bbb2ee5d-SNAPSHOT
  .buildkite/hooks/post-checkout
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/pipeline.package.mbp.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/package.sh
  .mergify.yml
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2756 [updatecli] update elastic stack version for testing 8.9.0-dd1f0db2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2758 [updatecli] update elastic stack version for testing 8.10.0-18649b44-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
