Repository elastic/fleet-server, pull requests merged in 2023-11, with the labels that each got.

#3069 [Fleet] Better handle policy not found error for static tokens
  internal/pkg/api/error.go
Labels: Team:Fleet

#3072 [updatecli] update elastic stack version for testing 8.10.5-2cbba330-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3060 Define action.data and ack event schemas
  changelog/fragments/1698445691-Define-action.data-and-ack-event-schema.yaml
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleAck_test.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/openapi.gen.go
  internal/pkg/api/openapi_spec_test.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/server/fleet_secrets_integration_test.go
  model/openapi.yml
  pkg/api/types.gen.go
  testing/e2e/api_version/client_api_current.go
Labels: Team:Fleet, tech debt

#3076 [updatecli] update elastic stack version for testing 8.10.5-d6b719a1-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3077 [updatecli] update elastic stack version for testing 8.10.5-952c31ce-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3073 Update module dependencies
  .buildkite/pipeline.yml
  Makefile
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/api/openapi.gen.go
  internal/pkg/bulk/bulk_test.go
  pkg/api/client.gen.go
  pkg/api/types.gen.go
  pkg/api/versions/2023_06_01/api/client.gen.go
  pkg/api/versions/2023_06_01/api/types.gen.go
  testing/go.mod
  testing/go.sum
Labels: Team:Fleet, tech debt

#3052 [updatecli] update elastic stack version for testing 7.17.15-982e299a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3080 [updatecli] update elastic stack version for testing 8.10.5-5c458ac8-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3085 [updatecli] update elastic stack version for testing 8.10.5-b9ae0cc2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3006 [Release] Update version to 8.11.1
  version/version.go
Labels: Team:Automation, release

#3086 Replace all secret references in input map
  changelog/fragments/1699380976-Replace-any-secret-ref-in-input-map.yaml
  internal/pkg/policy/secret.go
  internal/pkg/policy/secret_test.go
Labels: bug, Team:Fleet, backport-v8.11.0

#3094 [Release] Update version to 8.11.2
  version/version.go
Labels: Team:Automation, release

#3096 [Release] Update version to 7.17.16
  main.go
Labels: Team:Automation, release

#3036 [updatecli] update elastic stack version for testing 8.12.0-628b3b84-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3097 [updatecli] update elastic stack version for testing 8.11.1-2f6a8ab6-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3092 Remove internal/pkg/testing from sonarqube coverage
  sonar-project.properties
Labels: Team:Fleet, tech debt

#3081 [updatecli] update elastic stack version for testing 7.17.15-aad9f113-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3093 [Automation] Bump Golang version to 1.21.4
  .go-version
  .golangci.yml
Labels: backport-skip

#3104 [updatecli] update elastic stack version for testing 8.11.2-a8fca3bd-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3105 [updatecli] update elastic stack version for testing 8.12.0-82c28a25-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3107 [updatecli] update elastic stack version for testing 7.17.16-95c51018-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3108 [updatecli] update elastic stack version for testing 8.12.0-c18d0d89-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3109 [updatecli] update elastic stack version for testing 8.11.2-e0eeeb99-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3112 [updatecli] update elastic stack version for testing 7.17.16-641039af-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3111 [updatecli] update elastic stack version for testing 8.12.0-7521d760-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3114 Add tags to the provisioned EC deployment
  dev-tools/cloud/Makefile
  dev-tools/cloud/terraform/main.tf
Labels: automation, ci

#3113 [updatecli] update elastic stack version for testing 8.11.2-01f6d366-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3118 [updatecli] update elastic stack version for testing 7.17.16-1c2c59f9-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3123 [updatecli] update elastic stack version for testing 7.17.16-36c2b6c2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3125 [updatecli] update elastic stack version for testing 8.12.0-d6c4164b-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3122 [updatecli] update elastic stack version for testing 8.11.2-8c8386ee-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3124 Add additional transaction labels with error details to requests.
  changelog/fragments/1701111919-Enrich-transaction-APM-errors.yaml
  internal/pkg/api/error.go
  internal/pkg/api/error_test.go
Labels: enhancement, Team:Fleet

#3051 Support for remote ES output
  Makefile
  changelog/fragments/1698660041-remote-es-output.yaml
  dev-tools/integration/.env
  dev-tools/integration/docker-compose.yml
  dev-tools/integration/get-elasticsearch-servicetoken.sh
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleAck_test.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/bulk/bulk_remote_output_test.go
  internal/pkg/bulk/bulk_test.go
  internal/pkg/bulk/engine.go
  internal/pkg/bulk/opt.go
  internal/pkg/dl/migration_integration_test.go
  internal/pkg/dl/policies.go
  internal/pkg/dl/policies_integration_test.go
  internal/pkg/model/schema.go
  internal/pkg/policy/parsed_policy.go
  internal/pkg/policy/parsed_policy_data_test.go
  internal/pkg/policy/parsed_policy_test.go
  internal/pkg/policy/policy_output.go
  internal/pkg/policy/policy_output_integration_test.go
  internal/pkg/policy/policy_output_test.go
  internal/pkg/policy/secret.go
  internal/pkg/policy/secret_test.go
  internal/pkg/policy/self_test.go
  internal/pkg/policy/standalone_test.go
  internal/pkg/server/fleet.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/server/fleet_secrets_integration_test.go
  internal/pkg/server/remote_es_output_integration_test.go
  internal/pkg/testing/bulk.go
  internal/pkg/testing/esutil/client.go
  model/schema.json
Labels: enhancement

#3129 [updatecli] update elastic stack version for testing 8.12.0-ec4853e4-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
