Repository elastic/fleet-server, pull requests merged in 2023-05, with the labels that each got.

#2551 [updatecli] update elastic stack version for testing 8.7.1-79685088-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2531 Make Internal Server Error default error
  changelog/fragments/1683024407-API-default-error-is-now-500.yaml
  internal/pkg/api/auth.go
  internal/pkg/api/error.go
  internal/pkg/api/handleUpload.go
  internal/pkg/api/openapi.gen.go
  internal/pkg/apikey/auth.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/uploader/upload.go
  model/openapi.yml
Labels: Team:Fleet, backport-skip

#2554 Replace pre-checkout with post-checkout
  .buildkite/hooks/post-checkout
  .buildkite/hooks/pre-checkout
  .buildkite/pull-requests.json
Labels: ci

#2534 backport: Add 8.8 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, release

#2558 [updatecli] update elastic stack version for testing 8.9.0-a2c79020-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2548 [updatecli] update elastic stack version for testing 8.8.0-de6751d7-SNAPSHOT
  dev-tools/integration/.env
  fleet-server.reference.yml
  internal/pkg/bulk/bulk_integration_test.go
Labels: automation, dependency, backport-skip

#2561 [updatecli] update elastic stack version for testing 8.9.0-5c23b5b2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2564 [updatecli] update elastic stack version for testing 8.7.2-a5f8cdcb-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2562 [updatecli] update elastic stack version for testing 8.8.0-97faefbe-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2563 [updatecli] update elastic stack version for testing 8.9.0-23370c3a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2552 upgrade elastic-agent-client to 7.1.1 for pprof fix
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/server/agent.go
  internal/pkg/server/agent_test.go
Labels: bug, backport-v8.7.0, backport-v8.8.0

#2571 [updatecli] update elastic stack version for testing 7.17.11-47c70080-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2569 [updatecli] update elastic stack version for testing 8.7.2-848575be-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2573 Add filter_condition to avoid duplicated builds
  catalog-info.yaml
Labels: ci

#2572 [updatecli] update elastic stack version for testing 8.8.0-867f1c4e-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2574 [updatecli] update elastic stack version for testing 8.7.2-dd4c72f2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2576 [updatecli] update elastic stack version for testing 8.9.0-2dbf1e1f-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2577 [updatecli] update elastic stack version for testing 7.17.11-ad2a1253-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2578 [updatecli] update elastic stack version for testing 8.7.2-9848dc50-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2580 [updatecli] update elastic stack version for testing 8.8.0-c26f78b8-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2559 [Fleet] Allow to deploy a custom fleet server image in cloud
  .ci/Jenkinsfile
  .gitignore
  Makefile
  README.md
  dev-tools/cloud/Makefile
  dev-tools/cloud/docker/build.sh
  dev-tools/cloud/terraform/main.tf
  dev-tools/cloud/terraform/outputs.tf
  testing/cloude2e/status_test.go
Labels: Team:Fleet

#2584 Merge sonar project properties and unit coverage target
  .github/workflows/build.yml
  .github/workflows/sonarcloud.yml
  Makefile
  sonar-project.properties
Labels: backport-skip

#2585 [Fleet] Allow to enable instrumentation through environment variable
  internal/pkg/server/fleet.go
  internal/pkg/server/fleet_test.go
Labels: Team:Fleet, v8.9.0

#2587 Add sonarqube code coverage badge
  README.md
Labels: backport-skip, ci

#2411 Address fixmes in openapi spec
  internal/pkg/api/api.go
  internal/pkg/api/openapi.gen.go
  model/openapi.yml
Labels: cleanup, Team:Fleet

#2589 [updatecli] update elastic stack version for testing 8.7.2-7653c06b-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2582 fix for action_seq_no being overwritten with 0
  README.md
  changelog/fragments/1684151814-fix-action-seq-no.yaml
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/checkin/bulk_test.go
Labels: v8.9.0

#2566 [Automation] Bump Golang version to 1.20.4
  .go-version
  .golangci.yml
Labels: backport-skip

#2543 add steps: check-ci, make-local, unit-test, int-test, annotate
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/integration_test.sh
  .buildkite/scripts/unit_test.sh
Labels: ci

#2598 [updatecli] update elastic stack version for testing 7.17.11-53c77961-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2601 [updatecli] update elastic stack version for testing 8.7.2-99e4ac2a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2609 [updatecli] update elastic stack version for testing 7.17.11-874490f1-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2608 [updatecli] update elastic stack version for testing 8.7.2-738acb99-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2607 [updatecli] update elastic stack version for testing 8.8.0-cc834a5d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2612 [updatecli] update elastic stack version for testing 7.17.11-b843b253-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2615 [updatecli] update elastic stack version for testing 8.7.2-34fb9774-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2600 [updatecli] update elastic stack version for testing 8.9.0-df4abdd6-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2622 [updatecli] update elastic stack version for testing 7.17.11-835d340b-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2620 [updatecli] update elastic stack version for testing 8.7.2-3ff44d96-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2619 [updatecli] update elastic stack version for testing 8.8.0-1b82ff0f-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2606 [Fleet] Fake agent in fleet server standalone
  cmd/fleet/main.go
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
Labels: Team:Fleet, Project:Serverless

#2624 Filter branches run in Buildkite
  catalog-info.yaml
Labels: ci

#2625 [updatecli] update elastic stack version for testing 7.17.11-dde35cb5-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2604 add the "Publish Docker images" step to the Buildkite pipeline
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/pipeline.yml
  .buildkite/scripts/build_push_docker_image.sh
  .buildkite/scripts/common.sh
Labels: ci

#2535 [Release] Update version to 8.8.1
  version/version.go
Labels: Team:Automation, release

#2631 [updatecli] update elastic stack version for testing 7.17.11-97b4b531-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2630 [updatecli] update elastic stack version for testing 8.8.0-e7f7cdfa-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2618 Fleet server add cloud e2e test
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/pipeline.yml
  .buildkite/scripts/build_push_docker_image.sh
  .buildkite/scripts/cloud_e2e_test.sh
  .buildkite/scripts/common.sh
  dev-tools/cloud/docker/build.sh
Labels: ci

#2629 [updatecli] update elastic stack version for testing 8.7.2-3e95e75d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2636 [updatecli] update elastic stack version for testing 8.9.0-95ded584-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2632 Add diagnostics config hook
  NOTICE.txt
  changelog/fragments/1685037431-Add-config-diagnostics-hook.yaml
  go.mod
  internal/pkg/server/agent.go
Labels: enhancement, Team:Fleet, Team:Elastic-Agent-Control-Plane, backport-v8.8.0

#2642 [updatecli] update elastic stack version for testing 8.7.2-81170f47-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2641 [updatecli] update elastic stack version for testing 8.9.0-0b9c4000-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2646 Add E2E test step to buildkite
  .buildkite/pipeline.yml
  .buildkite/scripts/e2e_test.sh
Labels: Team:Fleet, ci

#2643 Remove Elastic Agent control plane team as code owner.
  .github/CODEOWNERS
Labels: Team:Fleet, backport-v8.7.0, backport-v8.8.0

#2650 [updatecli] update elastic stack version for testing 8.8.1-8b995292-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2649 [updatecli] update elastic stack version for testing 8.9.0-3cc641a9-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2633 Refactor Upload portions into more generic: File
  internal/pkg/api/error.go
  internal/pkg/api/handleUpload.go
  internal/pkg/api/handleUpload_test.go
  internal/pkg/cache/cache.go
  internal/pkg/file/cbor/chunk.go
  internal/pkg/file/cbor/chunk_test.go
  internal/pkg/file/doc.go
  internal/pkg/file/es.go
  internal/pkg/file/es_test.go
  internal/pkg/file/file.go
  internal/pkg/file/uploader/doc.go
  internal/pkg/file/uploader/es.go
  internal/pkg/file/uploader/finalize.go
  internal/pkg/file/uploader/info.go
  internal/pkg/file/uploader/jsdict.go
  internal/pkg/file/uploader/jsdict_test.go
  internal/pkg/file/uploader/upload.go
  internal/pkg/file/uploader/upload_test.go
  internal/pkg/uploader/info.go
Labels: cleanup

#2639 Packaging pipeline initialization
  .buildkite/pipeline.package.mbp.yml
  catalog-info.yaml
Labels: ci

#2653 [updatecli] update elastic stack version for testing 8.9.0-3b0166e4-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2610 Prometheus metrics
  NOTICE.txt
  changelog/fragments/1684437851-Expose-prometheus-metrics.yaml
  go.mod
  go.sum
  internal/pkg/api/metrics.go
  internal/pkg/api/metrics_integration_test.go
  internal/pkg/api/server.go
  internal/pkg/server/fleet.go
Labels: enhancement, Team:Fleet
