Repository elastic/fleet-server, pull requests merged in 2023-08, with the labels that each got.

#2856 [updatecli] update elastic stack version for testing 8.10.0-ed2e01b4-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2858 [updatecli] update elastic stack version for testing 7.17.13-7f46ddb9-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2859 Change badge to reflect buildkite builds
  README.md
Labels: cleanup, Team:Fleet

#2863 replace secret refs
  changelog/fragments/1691492339-replace-secret-refs.yaml
  dev-tools/e2e/kibana.yml
  internal/pkg/api/handleCheckin.go
  internal/pkg/bulk/engine.go
  internal/pkg/bulk/secret.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/parsed_policy.go
  internal/pkg/policy/parsed_policy_test.go
  internal/pkg/policy/policy_output_integration_test.go
  internal/pkg/policy/policy_output_test.go
  internal/pkg/policy/secret.go
  internal/pkg/policy/secret_test.go
  internal/pkg/server/fleet_secrets_integration_test.go
  internal/pkg/testing/bulk.go
Labels: enhancement

#2866 [updatecli] update elastic stack version for testing 7.17.13-1882ecdc-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2865 [updatecli] update elastic stack version for testing 8.10.0-46c2dc52-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2867 Change dockerfile from golang-buster tp golang-bullseye
  Dockerfile
Labels: Team:Fleet, tech debt

#2869 [updatecli] update elastic stack version for testing 8.10.0-22c6ae41-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2873 [updatecli] update elastic stack version for testing 7.17.13-1b4d0dba-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2874 [updatecli] update elastic stack version for testing 8.10.0-0aabd193-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2791 [Automation] Bump Golang version to 1.20.7
  .go-version
  .golangci.yml
  Makefile
  go.sum
  testing/go.mod
  testing/go.sum
Labels: backport-skip

#2876 deleting `secret_references` from computed agent policy
  internal/pkg/policy/secret.go
  internal/pkg/policy/secret_test.go
Labels: cleanup, v8.10.0

#2875 Update elastic-agent-client to v7.3.0.
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/server/agent_test.go
  testing/go.mod
  testing/go.sum
Labels: Team:Elastic-Agent

#2879 [updatecli] update elastic stack version for testing 7.17.13-7c96d528-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2880 [Fleet] Fix static enrollment tokens blocking db enrollemnt tokens
  internal/pkg/api/handleEnroll.go
  internal/pkg/api/handleEnroll_test.go
Labels: Team:Fleet

#2882 fix the GCP credentials variable name
  .buildkite/hooks/pre-exit
  .buildkite/scripts/common.sh
Labels: ci

#2884 backport: Add 8.10 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, release, backport-v8.10.0

#2888 Fix branch version number
  version/version.go
Labels: backport-skip

#2881 [Release] Update version to 8.9.2
  version/version.go
Labels: Team:Automation, release

#2890 [buildkite] Update condition for downstream package step
  .buildkite/pipeline.yml
Labels: backport-v8.10.0

#2883 Bump the version on main to 8.11.0
  version/version.go
Labels: backport-skip

#2894 [updatecli] update elastic stack version for testing 8.10.0-96e4cccf-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2896 [updatecli] update elastic stack version for testing 7.17.13-dde9c3ba-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2891 backport the buildkite pipelines from the main branch to the branch 7.17
  .buildkite/hooks/post-checkout
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/pipeline.package.mbp.yml
  .buildkite/pipeline.yml
  .buildkite/pull-requests.json
  .buildkite/scripts/common.sh
  .buildkite/scripts/dra_release.sh
  .buildkite/scripts/integration_test.sh
  .buildkite/scripts/package.sh
  .buildkite/scripts/release-manager.sh
  .buildkite/scripts/release_test.sh
  .buildkite/scripts/unit_test.sh
  catalog-info.yaml
Labels: ci

#2897 Remove the Jenkins job for the 7.17 branch
  .ci/jobs/fleet-server-package-mbp.yml
  .ci/jobs/fleet-server.yml
  .ci/jobs/folders.yml
  .mergify.yml
Labels: ci

#2900 [updatecli] update elastic stack version for testing 7.17.13-23b69bf5-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2904 [updatecli] update elastic stack version for testing 7.17.13-9cee84e3-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2907 [updatecli] update elastic stack version for testing 7.17.13-7e207efe-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2905 [updatecli] update elastic stack version for testing 8.9.2-a6da2234-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2906 [updatecli] update elastic stack version for testing 8.10.0-ffe0de5c-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2913 Add branch setting to pipeline
  .buildkite/pipeline.yml
Labels: backport-v8.10.0

#2915 remove .ci folder
  .buildkite/scripts/makefile_test-release.sh
  .ci/Jenkinsfile
  .ci/bump-go-release-version.sh
  .ci/bump-stack-version.sh
  .ci/jobs/defaults.yml
  .ci/packaging.groovy
  .ci/scripts/install-docker-compose.sh
  Makefile
Labels: ci

#2895 [updatecli] update elastic stack version for testing 8.11.0-73e185bf-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2922 [updatecli] update elastic stack version for testing 8.10.0-edf31268-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2920 [updatecli] update elastic stack version for testing 8.11.0-76b03348-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2901 Add new upgrade_details field used in checkin
  Makefile
  changelog/fragments/1692641595-Add-support-for-upgrade_details-on-checkin.yaml
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/openapi.gen.go
  internal/pkg/api/openapi_spec_test.go
  internal/pkg/dl/constants.go
  internal/pkg/model/schema.go
  internal/pkg/testing/cache/cache.go
  model/openapi.yml
  model/schema.json
  pkg/api/client.gen.go
  pkg/api/types.gen.go
Labels: enhancement, Team:Fleet

#2925 [updatecli] update elastic stack version for testing 8.11.0-ba1a8c0f-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2924 Update elastic-agent libs to v0.3.13
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-v8.9.0, backport-v8.10.0

#2931 [updatecli] update elastic stack version for testing 8.11.0-16180d4a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2930 [updatecli] update elastic stack version for testing 8.10.0-b58178d3-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2921 [updatecli] update elastic stack version for testing 7.17.13-1c18dee3-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2919 [updatecli] update elastic stack version for testing 8.9.2-a804d52d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2936 [updatecli] update elastic stack version for testing 8.10.0-e6a0cfad-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2937 [updatecli] update elastic stack version for testing 8.11.0-1e5443be-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
