Repository elastic/fleet-server, pull requests merged in 2023-12, with the labels that each got.

#3132 [updatecli] update elastic stack version for testing 8.11.2-078bc9ad-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3128 [updatecli] update elastic stack version for testing 7.17.16-5dd1fb58-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3138 Remove logger and timings from tests
  internal/pkg/bulk/bulk_test.go
Labels: Team:Fleet, flaky-test

#3139 Use nop loggers to prevent test failures
  internal/pkg/bulk/bulk_remote_output_test.go
Labels: Team:Fleet, flaky-test

#3140 [updatecli] update elastic stack version for testing 7.17.16-460da4c1-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3136 [updatecli] update elastic stack version for testing 8.12.0-9d443b17-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3145 Bump the version on main to 8.13.0
  version/version.go
Labels: backport-skip

#3142 [updatecli] update elastic stack version for testing 8.11.2-0fa17a74-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3144 [updatecli] update elastic stack version for testing 7.17.16-e29c45be-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3153 [updatecli] update elastic stack version for testing 8.12.0-9bbde39d-SNAPSHOT
  .buildkite/pipeline.yml
  .buildkite/scripts/run_benchmark.sh
  .github/workflows/benchmark.yml
  .gitignore
  Makefile
  dev-tools/integration/.env
  gobenchdata-checks.yml
  version/version.go
Labels: automation, dependency, backport-skip

#3150 [Release] Update version to 7.17.17
  main.go
Labels: Team:Automation, release

#3154 invalidate remote api keys on unenroll
  dev-tools/integration/.env
  internal/pkg/api/auth.go
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/model/ext.go
  internal/pkg/model/ext_test.go
  internal/pkg/server/remote_es_output_integration_test.go
Labels: bug

#3146 backport: Add 8.12 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, release, backport-v8.12.0

#3161 [Release] Update version to 8.11.4
  version/version.go
Labels: Team:Automation, release

#3158 [updatecli] update elastic stack version for testing 7.17.16-cf899701-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3159 [updatecli] update elastic stack version for testing 8.11.3-dce3355e-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3156 [Automation] Bump Golang version to 1.21.5
  .go-version
  .golangci.yml
Labels: backport-skip

#3168 chore: use pinned versions
  dev-tools/integration/.env
Labels: backport-skip

#3157 ci(action): auto-bump daily and change slack notification channel
  .github/workflows/bump-golang.yml
Labels: automation

#3170 Update linter
  .github/workflows/golangci-lint.yml
  Makefile
  internal/pkg/action/dispatcher.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/openapi_spec_test.go
  internal/pkg/bulk/bulk_test.go
  internal/pkg/bulk/helpers.go
  internal/pkg/cache/cache.go
  internal/pkg/dl/actions.go
  internal/pkg/dl/enrollment_api_key.go
  internal/pkg/dl/enrollment_api_key_integration_test.go
  internal/pkg/dl/migration_integration_test.go
  internal/pkg/dl/policies_leader.go
  internal/pkg/es/info.go
  internal/pkg/file/delivery/delivery_test.go
  internal/pkg/file/uploader/upload_test.go
  internal/pkg/gcheckpt/checkpoint.go
  internal/pkg/policy/policy_output_integration_test.go
  internal/pkg/server/fleet.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/testing/esutil/client.go
  internal/pkg/testing/esutil/esutil.go
Labels: Team:Fleet, tech debt

#3169 [updatecli] update elastic stack version for testing 8.12.0-3faaf80d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3167 chore: use pinned versions
  dev-tools/integration/.env
Labels: backport-skip

#3175 [updatecli] update elastic stack version for testing 8.13.0-ubdkmnyz-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3171 [updatecli] update elastic stack version for testing 8.12.0-83badc78-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3176 [updatecli] update elastic stack version for testing 8.11.4-d6b1ea5a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3174 [updatecli] update elastic stack version for testing 7.17.17-7f0b87e8-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3165 Use Shutdown to gracefully halt HTTP servers
  changelog/fragments/1702574888-Drain-HTTP-connections-on-shutdown.yaml
  fleet-server.reference.yml
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleStatus.go
  internal/pkg/api/server.go
  internal/pkg/checkin/bulk.go
  internal/pkg/config/config_test.go
  internal/pkg/config/timeouts.go
  internal/pkg/profile/profile.go
  internal/pkg/profile/profile_test.go
  internal/pkg/server/fleet.go
  internal/pkg/server/fleet_integration_test.go
Labels: enhancement, Team:Fleet

#3183 [updatecli] update elastic stack version for testing 8.12.0-cf3c9e0f-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3182 [updatecli] update elastic stack version for testing 7.17.17-13e2edc2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3181 [updatecli] update elastic stack version for testing 8.13.0-yufkxnwm-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3180 [updatecli] update elastic stack version for testing 8.11.4-eb79a552-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3185 [Buildkite] Add dependabot as a user to run builds in Pull Requests
  .buildkite/pull-requests.json
Labels: Team:Fleet, backport-skip, ci

#3178 replace policy_throttle with policy_limit
  .buildkite/pipeline.perf-tests.yaml
  .buildkite/pipeline.yml
  changelog/fragments/1702940211-Replace-policy-throttle-with-limiter.yaml
  fleet-server.reference.yml
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/server_test.go
  internal/pkg/config/defaults/lte10000_limits.yml
  internal/pkg/config/defaults/lte20000_limits.yml
  internal/pkg/config/defaults/lte2500_limite.yml
  internal/pkg/config/defaults/lte40000_limits.yml
  internal/pkg/config/defaults/lte5000_limits.yml
  internal/pkg/config/defaults/max_limits.yml
  internal/pkg/config/env_defaults.go
  internal/pkg/config/limits.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/policy/monitor_test.go
  internal/pkg/server/fleet.go
Labels: enhancement, Team:Fleet

#3186 [updatecli] update elastic stack version for testing 7.17.17-514f2280-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3187 [updatecli] update elastic stack version for testing 8.12.0-01443900-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3188 [updatecli] update elastic stack version for testing 8.11.4-4f9102a1-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3189 [updatecli] update elastic stack version for testing 8.13.0-qvykcic3-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
