Repository elastic/fleet-server, pull requests merged in 2023-10, with the labels that each got.

#3001 [updatecli] update elastic stack version for testing 8.10.3-57d6bd70-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3002 [updatecli] update elastic stack version for testing 8.10.3-75e0d7cb-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2994 Add ActionLimit and a gzip writer pool to handle checkin responses
  changelog/fragments/1696358866-Add-action-dispatcher-rate-limiter.yaml
  fleet-server.reference.yml
  internal/pkg/action/dispatcher.go
  internal/pkg/action/dispatcher_test.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/config/env_defaults.go
  internal/pkg/config/limits.go
  internal/pkg/config/timeouts.go
  internal/pkg/server/fleet.go
Labels: enhancement, Team:Fleet, Project:FleetScaling

#3005 backport: Add 8.11 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, release, backport-v8.11.0

#3011 Update enrollment logs
  internal/pkg/api/handleEnroll.go
Labels: backport-v8.10.0

#3004 Bump the version on main to 8.12.0
  version/version.go
Labels: backport-skip

#3017 [updatecli] update elastic stack version for testing 8.10.3-17f9519a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3019 [updatecli] update elastic stack version for testing 8.10.3-a2f2d849-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3022 [updatecli] update elastic stack version for testing 8.10.3-61debe57-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2980 [updatecli] update elastic stack version for testing 7.17.14-a522fb9c-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3021 [Release] Update version to 7.17.15
  main.go
Labels: Team:Automation, release

#3020 [Release] Update version to 8.10.4
  version/version.go
Labels: Team:Automation, release

#3023 [Fleet] Fix kibana config in e2e tests
  dev-tools/e2e/kibana.yml
  dev-tools/e2e/wait-for-kibana.sh
  dev-tools/integration/.env
Labels: Team:Fleet

#3014 Buildkite migration is now complete, removing fleet-server jobs
  .buildkite/scripts/test-release.sh
  .ci/Jenkinsfile
  .ci/bump-elastic-stack-snapshot.yml
  .ci/bump-golang.yml
  .ci/jobs/defaults.yml
  .ci/jobs/fleet-server-package-mbp.yml
  .ci/jobs/fleet-server.yml
  .ci/jobs/folders.yml
  .ci/packaging.groovy
  .ci/scripts/install-docker-compose.sh
  Makefile
Labels: Team:Fleet

#3018 [Automation] Bump Golang version to 1.20.9
  .go-version
  .golangci.yml
Labels: backport-skip

#3032 [Fleet] Quality gates for production canary
  .buildkite/pipeline.tests-production-canary.yaml
  .buildkite/pipeline.tests-staging.yaml
Labels: Team:Fleet

#3027 [updatecli] update elastic stack version for testing 8.10.4-b2fddf0a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3034 Fix bulker error attributes to be ECS complient
  changelog/fragments/1697136150-Fix-bulker-error-message-attribute.yaml
  internal/pkg/bulk/opApiKey.go
  internal/pkg/bulk/opBulk.go
  internal/pkg/bulk/opRead.go
  internal/pkg/bulk/opSearch.go
Labels: bug, Team:Fleet, backport-v8.11.0

#3029 [updatecli] update elastic stack version for testing 8.12.0-1a1295ff-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3038 Update go version to 1.21.3
  .go-version
  .golangci.yml
  internal/pkg/policy/parsed_policy_data_test.go
Labels: Team:Fleet, tech debt

#3041 [updatecli] update elastic stack version for testing 8.10.4-945697b8-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3040 [Release] Update version to 8.10.5
  version/version.go
Labels: Team:Automation, release

#3039 Relax version checks for snapshot builds
  Makefile
  README.md
  changelog/fragments/1697230491-Relax-version-checks-in-snapshot-builds.yaml
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/userAgent.go
  internal/pkg/api/userAgent_test.go
  internal/pkg/api/verConst.go
  internal/pkg/api/verConst_snapshot.go
  internal/pkg/api/verConst_snapshot_test.go
Labels: enhancement, Team:Fleet

#3043 [Buildkite] Allow failures to triggering package-registry job
  .buildkite/pipeline.yml
Labels: Team:Fleet, ci, backport-v8.11.0

#3042 [updatecli] update elastic stack version for testing 8.10.5-fede41a8-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3047 [updatecli] update elastic stack version for testing 8.10.5-69d64a75-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3049 [updatecli] update elastic stack version for testing 8.10.5-0028f476-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3050 [updatecli] update elastic stack version for testing 8.10.5-b919c0d9-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3028 [updatecli] update elastic stack version for testing 7.17.15-2d46ac23-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3053 Send errors in API calls and bulker flushes to APM
  changelog/fragments/1698163014-apm-errors.yaml
  internal/pkg/api/error.go
  internal/pkg/bulk/engine.go
Labels: backport-v8.11.0

#3056 [Fleet] Improve error handling for invalid base64 token
  internal/pkg/apikey/apikey.go
  internal/pkg/apikey/apikey_test.go
Labels: bug, Team:Fleet

#3054 [Fleet] Bump x/net and grpc dependencies
  NOTICE.txt
  go.mod
  go.sum
  testing/go.mod
  testing/go.sum
Labels: Team:Fleet, backport-v8.11.0

#3048 Add top level keys for policy definition into specs
  changelog/fragments/1698276551-Define-policy-data-schema.yaml
  internal/pkg/api/handleCheckin.go
  internal/pkg/coordinator/monitor_integration_test.go
  internal/pkg/coordinator/v0.go
  internal/pkg/coordinator/v0_test.go
  internal/pkg/dl/policies_integration_test.go
  internal/pkg/model/schema.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/policy/monitor_test.go
  internal/pkg/policy/parsed_policy.go
  internal/pkg/policy/parsed_policy_test.go
  internal/pkg/policy/policy_output.go
  internal/pkg/policy/policy_output_integration_test.go
  internal/pkg/policy/policy_output_test.go
  internal/pkg/policy/secret.go
  internal/pkg/policy/secret_test.go
  internal/pkg/policy/self.go
  internal/pkg/policy/self_test.go
  internal/pkg/server/agent_integration_test.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/server/fleet_secrets_integration_test.go
  model/openapi.yml
  model/schema.json
Labels: Team:Fleet, tech debt

#3063 [updatecli] update elastic stack version for testing 8.10.5-602db7b7-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3061 [Fleet] Support output secrets
  changelog/fragments/1698420960-output-secrets.yaml
  internal/pkg/policy/parsed_policy.go
  internal/pkg/policy/secret.go
  internal/pkg/policy/secret_test.go
Labels: Team:Fleet

#3065 [updatecli] update elastic stack version for testing 8.10.5-4e5678b2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3067 Fix mutation issue when using parsed policies
  go.mod
  go.sum
  internal/pkg/api/handleCheckin.go
  internal/pkg/model/ext.go
  testing/go.mod
  testing/go.sum
Labels: bug, Team:Fleet

#3071 [updatecli] update elastic stack version for testing 8.10.5-7673c4c2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
