Repository elastic/fleet-server, pull requests merged in 2023-02, with the labels that each got.

#2309 [automation] update elastic stack version for testing 8.7.0-87b130b2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2310 [automation] update elastic stack version for testing 7.17.9-663e90b2
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2315 [automation] update elastic stack version for testing 7.17.9-f3ee8926
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2314 [automation] update elastic stack version for testing 8.7.0-a8bf765b
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2313 [automation] update elastic stack version for testing 8.6.2-b5f10a44
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2316 [automation] update elastic stack version for testing 8.6.2-9fa37b7d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2317 [automation] update elastic stack version for testing 8.7.0-1ef3b708
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2312 [Release] Update version to 7.17.10
  main.go
Labels: Team:Automation, release

#2319 [automation] update elastic stack version for testing 8.6.2-74b1938c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2324 [automation] update elastic stack version for testing 7.17.10-f1f67132
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2323 [automation] update elastic stack version for testing 8.6.2-7c4539d9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2326 backport: Add 8.7 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, release

#2325 Bump the version on main to 8.8.0
  version/version.go
Labels: backport-skip

#2331 Allow the the Warn log level to be specified as "warning" and "warn"
  CHANGELOG.next.asciidoc
  internal/pkg/config/config_test.go
  internal/pkg/config/fleet.go
Labels: bug, Team:Fleet, backport-v8.6.0, backport-v8.7.0

#2334 automation: bump snapshot stack
  .ci/bump-elastic-stack-snapshot.yml
  .ci/bump-stack-version.sh
  .github/workflows/bump-elastic-stack-snapshot.yml
  .github/workflows/bump-golang.yml
  .github/workflows/opentelemetry.yml
Labels: automation, backport-skip

#2340 updatecli: fix the bump elastic stack
  .ci/bump-elastic-stack-snapshot.yml
  .github/workflows/bump-elastic-stack-snapshot.yml
Labels: backport-skip

#2343 [updatecli] update elastic stack version for testing 8.7.0-dd1a1621-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2344 updatecli: ensure one branch per release branch
  .ci/bump-elastic-stack-snapshot.yml
Labels: backport-skip

#2341 Increase checkin long-poll time to 28m and write timeout to 29m
  CHANGELOG.next.asciidoc
  internal/pkg/api/handleCheckin.go
  internal/pkg/config/config_test.go
  internal/pkg/config/timeouts.go
  internal/pkg/server/standAlone_dev.go
  model/openapi.yml
Labels: enhancement, Team:Fleet

#2345 action: use composite updatecli
  .github/workflows/bump-elastic-stack-snapshot.yml
  .github/workflows/bump-golang.yml
Labels: backport-skip

#2347 [updatecli] update elastic stack version for testing 8.7.0-52171374-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2349 [updatecli] update elastic stack version for testing 8.6.2-8caa8b27-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2348 [updatecli] update elastic stack version for testing 8.8.0-bd3b6869-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2356 [updatecli] update elastic stack version for testing 8.6.2-03dd602a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2355 [updatecli] update elastic stack version for testing 8.8.0-56b80d12-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2353 Pass "signed" data with the action to the agent
  changelog/fragments/1676500216-pass_action_signature.yaml
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/schema.go
  internal/pkg/api/schema_test.go
  internal/pkg/model/schema.go
  internal/pkg/model/schema_test.go
  model/openapi.yml
  model/schema.json
Labels: 8.8-candidate, Team:Security-Defend-Workflows

#2357 [updatecli] update elastic stack version for testing 8.8.0-123bc644-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2358 [updatecli] update elastic stack version for testing 8.7.0-4412a58d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2361 [updatecli] update elastic stack version for testing 8.7.0-91bd3c0f-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2362 [updatecli] update elastic stack version for testing 8.8.0-4c33ca65-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2360 Upload route rate limits
  internal/pkg/api/handleUpload.go
  internal/pkg/api/metrics.go
  internal/pkg/api/router.go
  internal/pkg/config/env_defaults.go
  internal/pkg/config/limits.go
  internal/pkg/limit/httpwrapper.go
Labels: bug, backport-v8.7.0

#2335 [Release] Update version to 8.6.3
  version/version.go
Labels: Team:Automation, release

#2354 Fix fleet-server discarding extra server.* keys when assembling config
  CHANGELOG.next.asciidoc
  internal/pkg/server/agent.go
  internal/pkg/server/agent_test.go
Labels: bug, Team:Fleet, backport-v8.6.0, backport-v8.7.0

#2369 [updatecli] update elastic stack version for testing 7.17.10-0fbed52a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2368 [updatecli] update elastic stack version for testing 8.8.0-4671daa2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2372 [updatecli] update elastic stack version for testing 8.7.0-ec872331-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2373 [updatecli] update elastic stack version for testing 8.8.0-5d46a537-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2378 [updatecli] update elastic stack version for testing 8.8.0-ad6ea1d3-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2376 [updatecli] update elastic stack version for testing 8.7.0-c05d21f2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2380 [updatecli] update elastic stack version for testing 7.17.10-72c5bb9c-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2379 [updatecli] update elastic stack version for testing 8.7.0-0cf05406-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2381 [updatecli] update elastic stack version for testing 8.6.3-e20210f5-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2322 Use oapi-codegen to generate server router
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Makefile
  NOTICE.txt
  cmd/fleet/main.go
  go.mod
  go.sum
  internal/pkg/api/api.go
  internal/pkg/api/auth.go
  internal/pkg/api/error.go
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleAck_test.go
  internal/pkg/api/handleArtifacts.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/handleEnroll.go
  internal/pkg/api/handleStatus.go
  internal/pkg/api/handleStatus_test.go
  internal/pkg/api/handleUpload.go
  internal/pkg/api/handleUpload_test.go
  internal/pkg/api/metrics.go
  internal/pkg/api/openapi.gen.go
  internal/pkg/api/openapi_spec_test.go
  internal/pkg/api/router.go
  internal/pkg/api/router_test.go
  internal/pkg/api/schema.go
  internal/pkg/api/schema_test.go
  internal/pkg/api/server.go
  internal/pkg/api/server_test.go
  internal/pkg/api/userAgent.go
  internal/pkg/api/userAgent_test.go
  internal/pkg/api/utils.go
  internal/pkg/bulk/engine.go
  internal/pkg/es/client.go
  internal/pkg/limit/httpwrapper.go
  internal/pkg/limit/limiter.go
  internal/pkg/limit/limiter_test.go
  internal/pkg/logger/http.go
  internal/pkg/logger/http_test.go
  internal/pkg/monitor/monitor_integration_test.go
  internal/pkg/server/agent_integration_test.go
  internal/pkg/server/fleet.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/server/standAlone_dev.go
  internal/pkg/uploader/cbor/chunk.go
  internal/pkg/uploader/doc.go
  main.go
  model/oapi-cfg.yml
  model/openapi.yml
Labels: Team:Fleet, tech debt

#2389 [updatecli] update elastic stack version for testing 8.6.3-9bb26cf2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2390 [updatecli] update elastic stack version for testing 8.7.0-8c4f161e-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2382 [updatecli] update elastic stack version for testing 8.8.0-f8a27ec5-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
