Repository elastic/fleet-server, pull requests merged in 2023-07, with the labels that each got.

#2760 fix go version
  .buildkite/hooks/post-checkout
  .buildkite/pipeline.yml
Labels: ci

#2762 [updatecli] update elastic stack version for testing 8.8.3-1f4ea904-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2763 [updatecli] update elastic stack version for testing 8.8.3-dcc440f7-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2764 [updatecli] update elastic stack version for testing 8.9.0-872b2eab-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2766 [updatecli] update elastic stack version for testing 8.9.0-55dfeb9a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2771 [TLS-446] stop triggering old pipeline; all envs are in new
  .buildkite/pipeline.yml
Labels: cleanup

#2723 Dra release staging stage
  .buildkite/hooks/post-checkout
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/pipeline.package.mbp.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/dra_release.sh
  .buildkite/scripts/release-manager.sh
  .ci/bump-golang.yml
Labels: ci

#2772 [updatecli] update elastic stack version for testing 7.17.12-a5bf8147-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2774 [updatecli] update elastic stack version for testing 8.8.3-193fc993-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2775 [updatecli] update elastic stack version for testing 8.10.0-89405a28-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2778 [updatecli] update elastic stack version for testing 7.17.12-18dff279-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2779 [updatecli] update elastic stack version for testing 8.9.0-a302929e-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2780 [updatecli] update elastic stack version for testing 8.10.0-daadfd9e-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2783 [updatecli] update elastic stack version for testing 7.17.12-3f1ad8e1-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2786 [updatecli] update elastic stack version for testing 8.8.3-412b0627-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2784 [updatecli] update elastic stack version for testing 8.9.0-53fadbe2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2782 using actionID+agentID as action results doc id
  changelog/fragments/1689251909-unique-action-results.yaml
  internal/pkg/api/handleAck.go
  internal/pkg/dl/action_results.go
  internal/pkg/dl/action_results_integration_test.go
Labels: enhancement

#2788 [updatecli] update elastic stack version for testing 7.17.12-c78d45be-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2787 [updatecli] update elastic stack version for testing 8.8.3-40270fd0-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2789 [updatecli] update elastic stack version for testing 8.10.0-464beb1d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2790 [updatecli] update elastic stack version for testing 8.9.0-905e99b1-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2792 [updatecli] update elastic stack version for testing 8.8.3-a6972ae1-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2794 [updatecli] update elastic stack version for testing 8.9.0-6fafc4ad-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2800 [updatecli] update elastic stack version for testing 8.10.0-e6b42036-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2801 [updatecli] update elastic stack version for testing 8.9.0-164e5e60-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2804 [updatecli] update elastic stack version for testing 7.17.12-4a94a841-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2802 [updatecli] update elastic stack version for testing 8.8.3-d11d374b-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2803 [updatecli] update elastic stack version for testing 8.10.0-506cd98d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2805 [updatecli] update elastic stack version for testing 8.9.0-5732cdbc-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2808 [updatecli] update elastic stack version for testing 7.17.12-5a5017c5-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2807 [updatecli] update elastic stack version for testing 8.8.3-7453d831-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2654 feat: support static tokens to be used for agent enrollment
  changelog/fragments/1687329868-policy-static-token.yaml
  fleet-server.reference.yml
  internal/pkg/api/handleEnroll.go
  internal/pkg/api/handleEnroll_test.go
  internal/pkg/bulk/opApiKey.go
  internal/pkg/bulk/opt.go
  internal/pkg/config/input.go
  testing/e2e/stand_alone_test.go
  testing/e2e/testdata/stand-alone-https.tpl
Labels: enhancement

#2776 go life with buildkite pipeline
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/dra_release.sh
  .buildkite/scripts/dra_snapshot.sh
  .buildkite/scripts/release-manager.sh
  .ci/jobs/fleet-server-package-mbp.yml
  .ci/jobs/fleet-server.yml
Labels: ci

#2815 [Fleet] Fix docker publish step in buildkite
  .buildkite/pipeline.yml
Labels: Team:Fleet

#2814 change the agent's image and packages for ARM platform
  .buildkite/pipeline.package.mbp.yml
  .buildkite/scripts/common.sh
Labels: ci

#2722 [Release] Update version to 8.9.1
  version/version.go
Labels: Team:Automation, release

#2822 [Release] Update version to 7.17.13
  main.go
Labels: Team:Automation, release

#2827 hot-fix rda-release script
  .buildkite/scripts/dra_release.sh
Labels: ci

#2830 [updatecli] update elastic stack version for testing 7.17.12-7c1d40f1-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2829 [updatecli] update elastic stack version for testing 8.8.3-3c98aafb-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2831 add the FOLDER definition
  .buildkite/scripts/dra_release.sh
Labels: ci

#2833 add export FOLDER and export OUTPUT_FILE
  .buildkite/scripts/dra_release.sh
  .buildkite/scripts/package.sh
Labels: ci

#2834 fix package type var
  .buildkite/scripts/package.sh
Labels: ci

#2835 migrate release manager dependencies
  .buildkite/scripts/dra_release.sh
Labels: ci

#2836 fix the folder_path issue
  .buildkite/scripts/dra_release.sh
Labels: ci

#2832 [Fleet] Support ARM build for fleet server standalone docker image
  .buildkite/scripts/build_push_docker_image.sh
  .buildkite/scripts/common.sh
  Dockerfile
  Makefile
  testing/e2e/stand_alone_container_test.go
Labels: Team:Fleet

#2837 add path to release-manager script
  .buildkite/scripts/dra_release.sh
  .buildkite/scripts/release-manager.sh
Labels: ci

#2838 add export WORKSPACE
  .buildkite/scripts/dra_release.sh
Labels: ci

#2843 [updatecli] update elastic stack version for testing 8.8.3-02d9b756-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2840 debug the release-manager script
  .buildkite/pipeline.package.mbp.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/dra_release.sh
  .buildkite/scripts/package.sh
  .buildkite/scripts/release-manager.sh
Labels: ci

#2844 [updatecli] update elastic stack version for testing 8.10.0-439345ab-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2845 test dra
  .buildkite/scripts/dra_release.sh
  .buildkite/scripts/release-manager.sh
Labels: ci

#2846 change VAULT secrets
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/scripts/release-manager.sh
Labels: ci

#2848 [updatecli] update elastic stack version for testing 8.8.3-e0b5ba55-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2849 [updatecli] update elastic stack version for testing 8.10.0-ec4cafa5-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2850 Add output type kafka to agent policies
  changelog/fragments/1690563780-Add-kafka-output-type-for-agent-policies.yaml
  internal/pkg/policy/policy_output.go
  internal/pkg/policy/policy_output_test.go
Labels: enhancement, Team:Fleet

#2853 [updatecli] update elastic stack version for testing 8.10.0-3213a03f-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2851 allow service-tests to run without var
  .buildkite/pipeline.service-tests.yml
Labels: Team:Fleet, ci
