Repository elastic/fleet-server, pull requests merged in 2023-01, with the labels that each got.

#2096 Remove automatic agent unenrollment
  CHANGELOG.next.asciidoc
  NOTICE.txt
  internal/pkg/coordinator/monitor.go
  internal/pkg/coordinator/monitor_integration_test.go
  internal/pkg/dl/agent.go
  internal/pkg/dl/agent_integration_test.go
Labels: breaking change

#2206 Fix the index monitor checkpoint tracking for when the documents are deleted
  CHANGELOG.next.asciidoc
  internal/pkg/monitor/monitor.go
  internal/pkg/monitor/monitor_integration_test.go
Labels: bug, backport-v8.4.0, backport-v8.5.0, backport-v8.6.0

#2251 [automation] update elastic stack version for testing 8.6.0-91e609be
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2253 [automation] update elastic stack version for testing 8.5.4-1b0ccb68
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2258 [automation] update elastic stack version for testing 8.5.4-cade095d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2257 [automation] update elastic stack version for testing 8.6.0-08ebeaf7
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2256 [automation] update elastic stack version for testing 8.7.0-129a645f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2262 [automation] update elastic stack version for testing 8.5.4-fb007f04
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2261 [automation] update elastic stack version for testing 8.6.0-9105192d
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2263 [automation] update elastic stack version for testing 8.7.0-df9bb536
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2264 [automation] update elastic stack version for testing 8.7.0-61c35791
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2088 [Release] Update version to 8.6.1
  version/version.go
Labels: Team:Automation, release

#2265 [automation] update elastic stack version for testing 8.5.4-6280647c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2268 [automation] update elastic stack version for testing 8.5.4-1969ac34
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2212 Allow dev stand-alone execution
  CHANGELOG.next.asciidoc
  Makefile
  README.md
  cmd/fleet/main.go
  fleet-server.yml
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleStatus_test.go
  internal/pkg/bulk/bulk_test.go
  internal/pkg/bulk/opMulti_integration_test.go
  internal/pkg/bulk/opMulti_test.go
  internal/pkg/checkin/bulk_test.go
  internal/pkg/config/env_defaults.go
  internal/pkg/config/env_defaults_test.go
  internal/pkg/policy/self.go
  internal/pkg/server/agent.go
  internal/pkg/server/fleet.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/server/standAlone_dev.go
  internal/pkg/server/standAlone_release.go
  internal/pkg/testing/fleet-server-testing.yml
  internal/pkg/testing/log/log.go
  internal/pkg/testing/setup.go
  internal/pkg/throttle/throttle_test.go
  internal/pkg/ver/check_test.go
Labels: enhancement, Team:Fleet

#2274 [automation] update elastic stack version for testing 8.6.1-436ca0d1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2275 [automation] update elastic stack version for testing 8.7.0-3ec4e846
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2272 [automation] Update go release version 1.18.10
  .go-version
Labels: automation, dependency, backport-skip, backport-v8.6.0

#2281 [automation] update elastic stack version for testing 8.6.1-cc0796ca
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2282 action: use opentelemetry composite action
  .github/workflows/opentelemetry.yml
Labels: automation, Team:Automation, backport-v7.17.0, backport-v8.6.0

#2285 chore: update new year 2023
  NOTICE.txt
Labels: backport-skip

#2287 [automation] update elastic stack version for testing 7.17.9-a4381da5
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2286 [automation] update elastic stack version for testing 8.7.0-88fbfe89
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2290 [automation] update elastic stack version for testing 7.17.9-62814092
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2291 [automation] update elastic stack version for testing 8.7.0-304110fc
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#1902 File Upload Feature
  CHANGELOG.next.asciidoc
  internal/pkg/api/handleUpload.go
  internal/pkg/api/handleUpload_test.go
  internal/pkg/api/metrics.go
  internal/pkg/api/router.go
  internal/pkg/api/router_test.go
  internal/pkg/bulk/schema_easyjson.go
  internal/pkg/cache/cache.go
  internal/pkg/es/result.go
  internal/pkg/server/fleet.go
  internal/pkg/uploader/cbor/chunk.go
  internal/pkg/uploader/cbor/chunk_test.go
  internal/pkg/uploader/doc.go
  internal/pkg/uploader/es.go
  internal/pkg/uploader/es_test.go
  internal/pkg/uploader/finalize.go
  internal/pkg/uploader/info.go
  internal/pkg/uploader/jsdict.go
  internal/pkg/uploader/jsdict_test.go
  internal/pkg/uploader/upload.go
  internal/pkg/uploader/upload/info.go
  internal/pkg/uploader/upload_test.go
  model/schema.json
Labels: enhancement, 8.6-candidate

#2293 [automation] update elastic stack version for testing 8.6.1-8f6887b9
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2292 [automation] update elastic stack version for testing 8.7.0-909f3a86
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2297 [automation] update elastic stack version for testing 8.7.0-ba9bcc38
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2302 [automation] update elastic stack version for testing 8.7.0-1604eae1
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2296 [Release] Update version to 8.6.2
  version/version.go
Labels: Team:Automation, release

#2299 Openapi docs for File Upload routes
  model/openapi.yml
Labels: docs

#2304 [automation] update elastic stack version for testing 8.6.2-a887b34c
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2305 [automation] update elastic stack version for testing 8.7.0-975fd02f
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2307 [automation] update elastic stack version for testing 8.6.2-6e25dbb4
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2306 [automation] update elastic stack version for testing 8.7.0-4687ed94
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2301 Update openapi spec with diagnostics ack info
  model/openapi.yml
Labels: Team:Fleet
