Repository elastic/fleet-server, pull requests merged in 2023-09, with the labels that each got.

#2939 TLS-626 make sure e2e tests are being triggered before updating gitops
  .buildkite/pipeline.yml
Labels: ci

#2941 [updatecli] update elastic stack version for testing 8.11.0-8369a13a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2942 trigger scale tests from fleet-server-tests
  .buildkite/pipeline.tests-qa.yaml
  .buildkite/pipeline.tests-staging.yaml
Labels: enhancement

#2938 Sonarqube integration
  .buildkite/pipeline.yml
  .github/workflows/build.yml
  Makefile
  sonar-project.properties
Labels: enhancement

#2940 [updatecli] update elastic stack version for testing 8.10.0-e4344f1d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2945 [updatecli] update elastic stack version for testing 8.11.0-e6822a57-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2933 [Release] Update version to 8.9.3
  version/version.go
Labels: Team:Automation, release

#2934 [Release] Update version to 7.17.14
  main.go
Labels: Team:Automation, release

#2948 [updatecli] update elastic stack version for testing 8.10.0-8e2a7511-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2947 [updatecli] update elastic stack version for testing 8.11.0-32daf5de-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2952 [updatecli] update elastic stack version for testing 8.10.0-befeb0ae-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2929 Add more span for APM tracking
  NOTICE.txt
  changelog/fragments/1693593237-Expand-APM-traces.yaml
  go.mod
  go.sum
  internal/pkg/api/auth.go
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleArtifacts.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/handleEnroll.go
  internal/pkg/api/handleStatus.go
  internal/pkg/api/handleUpload.go
  internal/pkg/api/userAgent.go
  internal/pkg/api/userAgent_test.go
  internal/pkg/bulk/block.go
  internal/pkg/bulk/engine.go
  internal/pkg/bulk/opApiKey.go
  internal/pkg/bulk/opBulk.go
  internal/pkg/bulk/opMulti.go
  internal/pkg/bulk/opRead.go
  internal/pkg/bulk/opSearch.go
  internal/pkg/bulk/opt.go
  internal/pkg/bulk/secret.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/file/delivery/delivery.go
  internal/pkg/file/delivery/es.go
  internal/pkg/file/es.go
  internal/pkg/file/uploader/es.go
  internal/pkg/file/uploader/finalize.go
  internal/pkg/file/uploader/upload.go
  internal/pkg/monitor/monitor.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/parsed_policy.go
  internal/pkg/policy/policy_output.go
  internal/pkg/policy/self.go
  internal/pkg/policy/standalone.go
  internal/pkg/server/fleet.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/testing/bulk.go
Labels: enhancement, Team:Fleet

#2954 Fix TestServerInstrumentation with timeout
  internal/pkg/server/fleet_integration_test.go
Labels: Team:Fleet, flaky-test

#2955 [updatecli] update elastic stack version for testing 8.10.0-fa76ee05-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2956 [updatecli] update elastic stack version for testing 8.11.0-0d7477b6-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2957 Fix flaky instrumentation test
  internal/pkg/server/fleet_integration_test.go
Labels: Team:Fleet, flaky-test

#2965 [updatecli] update elastic stack version for testing 8.10.0-516050d7-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2961 [updatecli] update elastic stack version for testing 8.11.0-7dab12da-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2962 Add e2e coverage for sonar
  .buildkite/pipeline.yml
  .buildkite/scripts/e2e_test.sh
  Makefile
  sonar-project.properties
  testing/e2e/e2e_test.go
  testing/e2e/stand_alone_test.go
Labels: Team:Fleet, tech debt

#2970 [updatecli] update elastic stack version for testing 8.10.1-f9739ba2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2968 [updatecli] update elastic stack version for testing 8.11.0-f9ab12e0-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2971 [updatecli] update elastic stack version for testing 8.10.1-a0832870-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2973 [updatecli] update elastic stack version for testing 8.11.0-2b227d89-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2972 [updatecli] update elastic stack version for testing 8.10.1-1dffad09-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2974 [Release] Update version to 8.10.2
  version/version.go
Labels: Team:Automation, release

#2975 [updatecli] update elastic stack version for testing 8.11.0-f88f1d11-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2969 [updatecli] update elastic stack version for testing 7.17.14-f1d9b80b-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2976 [updatecli] update elastic stack version for testing 8.10.2-9d743908-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2959 [Automation] Bump Golang version to 1.20.8
  .go-version
  .golangci.yml
Labels: backport-skip

#2978 added 10m wait before quality gates
  .buildkite/pipeline.tests-qa.yaml
  .buildkite/pipeline.tests-staging.yaml
Labels: enhancement

#2979 [updatecli] update elastic stack version for testing 8.11.0-91824658-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2981 [updatecli] update elastic stack version for testing 8.10.2-d38be4c2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2982 [Fleet] Fix quality gates to use correct docker image
  .buildkite/pipeline.tests-qa.yaml
  .buildkite/pipeline.tests-staging.yaml
Labels: Team:Fleet

#2984 [Release] Update version to 8.10.3
  version/version.go
Labels: Team:Automation, release

#2987 [updatecli] update elastic stack version for testing 8.11.0-c47419c4-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2988 Improve README instructions for running a dev instance
  README.md
Labels: Team:Fleet, docs

#2977 Add PGP key retrieval endpoint
  README.md
  changelog/fragments/1695236064-Add-PGP-key-endpoint.yaml
  fleet-server.reference.yml
  internal/pkg/api/api.go
  internal/pkg/api/error.go
  internal/pkg/api/handlePGPRequest.go
  internal/pkg/api/handlePGPRequest_test.go
  internal/pkg/api/metrics.go
  internal/pkg/api/openapi.gen.go
  internal/pkg/api/router.go
  internal/pkg/api/server.go
  internal/pkg/api/server_test.go
  internal/pkg/cache/cache.go
  internal/pkg/config/config_test.go
  internal/pkg/config/env_defaults.go
  internal/pkg/config/input.go
  internal/pkg/config/limits.go
  internal/pkg/config/pgp.go
  internal/pkg/server/fleet.go
  internal/pkg/testing/cache/cache.go
  model/openapi.yml
  pkg/api/client.gen.go
  testing/e2e/README.md
  testing/e2e/agent_container_test.go
  testing/e2e/agent_install_test.go
  testing/e2e/api_version/client_api_2023_06_01.go
  testing/e2e/api_version/client_api_current.go
  testing/e2e/api_version/const.go
  testing/e2e/const.go
  testing/e2e/const_windows.go
  testing/e2e/doc.go
  testing/e2e/e2e_test.go
  testing/e2e/scaffold/scaffold.go
  testing/e2e/stand_alone_api_test.go
  testing/e2e/stand_alone_container_test.go
  testing/e2e/stand_alone_test.go
Labels: enhancement, Team:Fleet

#2986 [updatecli] update elastic stack version for testing 8.10.3-aa09190a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2991 turn down error logs in serverless
  internal/pkg/api/server.go
  internal/pkg/bulk/opRead.go
  internal/pkg/bulk/opSearch.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/monitor/monitor.go
  internal/pkg/scheduler/scheduler.go
Labels: enhancement

#2993 [updatecli] update elastic stack version for testing 8.11.0-6faed5c7-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2992 [updatecli] update elastic stack version for testing 8.10.3-345ef27d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2996 added basic quality gates to prod
  .buildkite/pipeline.tests-production.yaml
Labels: enhancement

#2998 [updatecli] update elastic stack version for testing 8.10.3-a4520544-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3000 [updatecli] update elastic stack version for testing 8.10.3-8e865fb7-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
