Repository elastic/fleet-server, pull requests merged in 2023-04, with the labels that each got.

#2467 [updatecli] update elastic stack version for testing 7.17.10-4f8b8753-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2466 [updatecli] update elastic stack version for testing 8.6.3-7488d6a9-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2468 [updatecli] update elastic stack version for testing 8.7.1-8f4cbaed-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2470 [updatecli] update elastic stack version for testing 8.6.3-a928ca66-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2469 [updatecli] update elastic stack version for testing 8.7.1-f71f9a90-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2449 Add github workflow for running go benchmarks on pull requests
  .github/workflows/benchmark.yml
Labels: enhancement

#2474 [updatecli] update elastic stack version for testing 7.17.10-55b185ac-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2473 [updatecli] update elastic stack version for testing 8.7.1-c94aa5f2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2475 Fix APM dependency
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/api/router.go
Labels: bug, Team:Fleet

#2459 Add support for gathering secret values from files.
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/config/config.go
  internal/pkg/config/instrumentation.go
  internal/pkg/config/instrumentation_test.go
  internal/pkg/config/output.go
  internal/pkg/config/output_test.go
  internal/pkg/config/testdata/ca.crt
  internal/pkg/config/testdata/ca.key
  internal/pkg/config/testdata/fleet-server.crt
  internal/pkg/config/testdata/fleet-server.key
  internal/pkg/server/agent_test.go
  internal/pkg/server/fleet.go
Labels: enhancement, Team:Fleet

#2454 Separate logger level reload from config reload
  CHANGELOG.next.asciidoc
  internal/pkg/config/config.go
  internal/pkg/config/fleet.go
  internal/pkg/config/fleet_test.go
  internal/pkg/config/logging.go
  internal/pkg/config/logging_test.go
  internal/pkg/logger/logger.go
  internal/pkg/logger/logger_test.go
  internal/pkg/server/agent_integration_test.go
  internal/pkg/server/fleet.go
  internal/pkg/server/fleet_test.go
Labels: bug, Team:Fleet

#2477 [updatecli] update elastic stack version for testing 8.7.1-43e3152f-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2481 [updatecli] update elastic stack version for testing 7.17.10-d950519d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2480 [updatecli] update elastic stack version for testing 8.7.1-975b29ab-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2476 Rename secret file attributes to use path suffix
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/config/instrumentation.go
  internal/pkg/config/instrumentation_test.go
  internal/pkg/config/output.go
  internal/pkg/config/output_test.go
Labels: Team:Elastic-Agent-Control-Plane, tech debt

#2486 [updatecli] update elastic stack version for testing 7.17.10-82b535ea-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2487 [updatecli] update elastic stack version for testing 8.7.1-db61f97d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2488 Remove service token from output validation
  internal/pkg/config/output.go
Labels: bug, Team:Fleet

#2483 Update dependencies
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Fleet, tech debt

#2493 [updatecli] update elastic stack version for testing 8.7.1-16046737-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2472 Add action APM metadata
  CHANGELOG.next.asciidoc
  NOTICE.txt
  go.mod
  internal/pkg/api/auth.go
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/openapi.gen.go
  internal/pkg/bulk/engine.go
  internal/pkg/bulk/opBulk.go
  internal/pkg/model/schema.go
  internal/pkg/testing/bulk.go
  model/openapi.yml
  model/schema.json
Labels: v8.8.0

#2491 Add poll_timeout attribute to checkin endpoint
  changelog/fragments/1681246555-Add-poll_duration-to-checkin-requests.yaml
  go.mod
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/openapi.gen.go
  internal/pkg/config/config_test.go
  internal/pkg/config/instrumentation.go
  internal/pkg/config/testdata/input-config.yml
  internal/pkg/config/timeouts.go
  internal/pkg/logger/http.go
  internal/pkg/server/fleet_integration_test.go
  model/openapi.yml
Labels: enhancement, Team:Fleet, Team:Elastic-Agent-Control-Plane

#2502 [updatecli] update elastic stack version for testing 8.7.1-75c765d0-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2500 remove licenses/ and dev-tools/cmd/license
  dev-tools/cmd/license/license_generate.go
  licenses/APACHE-LICENSE-2.0-header.txt
  licenses/APACHE-LICENSE-2.0.txt
  licenses/ELASTIC-LICENSE-2.0-header.txt
  licenses/ELASTIC-LICENSE-2.0.txt
  licenses/ELASTIC-LICENSE-header.txt
  licenses/ELASTIC-LICENSE.txt
  licenses/license.go
  licenses/license_header.go
Labels: cleanup, Team:Fleet

#2507 [updatecli] update elastic stack version for testing 7.17.10-c5c6d943-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2508 [updatecli] update elastic stack version for testing 8.7.1-87dfc35a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2515 [updatecli] update elastic stack version for testing 8.7.1-be1e8648-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2520 [updatecli] update elastic stack version for testing 7.17.10-1105d382-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2518 add catalog-info.yaml
  catalog-info.yaml
Labels: ci

#2522 [updatecli] update elastic stack version for testing 7.17.10-be0a95c3-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2524 [updatecli] update elastic stack version for testing 7.17.10-8bd5ded4-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2525 [updatecli] update elastic stack version for testing 8.7.1-02d8313a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2528 Add component entity to Backstage
  catalog-info.yaml
Labels: ci

#2526 Add the initial empty Buildkite pipeline
  .buildkite/pipeline.yml
Labels: enhancement, Team:Fleet, ci

#2529 Add fleet-server.reference.yml
  fleet-server.reference.yml
Labels: Team:Fleet, tech debt

#2544 [updatecli] update elastic stack version for testing 8.6.3-153a82ef-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2545 [updatecli] update elastic stack version for testing 8.7.1-af0797eb-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2533 Bump the version on main to 8.9.0
  version/version.go
Labels: backport-skip

#2530 add .buildkite/pull-requests.json file
  .buildkite/pull-requests.json
Labels: ci

#2549 [updatecli] update elastic stack version for testing 8.7.1-f44ecfbf-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
