Repository elastic/fleet-server, pull requests merged in 2023-03, with the labels that each got.

#2386 Remove agent tag duplicates
  internal/pkg/api/handleEnroll.go
  internal/pkg/api/handleEnroll_test.go
Labels: bug

#2321 [updatecli][githubrelease] Bump version to 1.19.5
  .github/workflows/golangci-lint.yml
  .go-version
  .golangci.yml
  NOTICE.txt
  go.mod
  go.sum
Labels: backport-v7.17.0, backport-v8.7.0

#2394 [updatecli] update elastic stack version for testing 8.6.3-05dd8895-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2396 [updatecli] update elastic stack version for testing 8.8.0-431cc5c2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2397 [updatecli] update elastic stack version for testing 8.7.0-0e27acda-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2398 [updatecli] update elastic stack version for testing 8.8.0-3648efbb-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2399 [updatecli] update elastic stack version for testing 8.7.0-b02b23e7-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2400 [updatecli] update elastic stack version for testing 8.6.3-70d2e959-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2405 [updatecli] update elastic stack version for testing 7.17.10-274f22a3-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2403 [updatecli] update elastic stack version for testing 8.6.3-3395a806-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2404 [updatecli] update elastic stack version for testing 8.7.0-a77bb5f1-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2402 [updatecli] update elastic stack version for testing 8.8.0-4dc109f9-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2407 [updatecli] update elastic stack version for testing 7.17.10-26a8527c-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2409 [updatecli] update elastic stack version for testing 8.6.3-a99e7a4f-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2408 [updatecli] update elastic stack version for testing 8.7.0-ee1c1335-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2413 [updatecli] update elastic stack version for testing 8.8.0-ba3f07b2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2418 [updatecli] update elastic stack version for testing 8.6.3-fdab5f2a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2406 [updatecli][githubrelease] Bump version to 1.19.6
  .go-version
  .golangci.yml
Labels: backport-skip, backport-v8.7.0

#2423 [updatecli][githubrelease] Bump version to 1.19.7
  .go-version
  .golangci.yml
Labels: Team:Elastic-Agent, backport-v8.7.0

#2428 [updatecli] update elastic stack version for testing 7.17.10-58141e3d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2426 [updatecli] update elastic stack version for testing 8.6.3-f262dde5-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2427 [updatecli] update elastic stack version for testing 8.7.0-a1ea0fcc-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2429 [updatecli] update elastic stack version for testing 7.17.10-61c4df0d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2430 [updatecli] update elastic stack version for testing 8.6.3-677cac11-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2432 [updatecli] update elastic stack version for testing 8.6.3-5ba327ff-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2436 [updatecli] update elastic stack version for testing 7.17.10-fb2882fc-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2439 [updatecli] update elastic stack version for testing 8.6.3-43bbf105-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2437 Fix missing Mock for MUpdate in benchmark tests
  internal/pkg/checkin/bulk_test.go
Labels: bug, flaky-test

#2444 [updatecli] update elastic stack version for testing 8.6.3-a3787e40-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2443 [updatecli] update elastic stack version for testing 8.7.0-11fca61c-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2441 Add benchmark and benchstat make targets
  Makefile
  README.md
Labels: enhancement, Supportability

#2452 [updatecli] update elastic stack version for testing 7.17.10-319f366a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2451 [updatecli] update elastic stack version for testing 8.6.3-b0dbc9d5-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2450 Add comments and unit test for gathering variables from env var
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
Labels: Team:Fleet, tech debt

#2455 [updatecli] update elastic stack version for testing 8.7.0-f15b1cb4-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2448 [Fleet] Fleet server standalone should be healthy before .fleet-policies is created
  internal/pkg/policy/standalone.go
  internal/pkg/policy/standalone_test.go
Labels: Team:Fleet, v8.8.0

#2457 [updatecli] update elastic stack version for testing 8.6.3-c7851810-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2446 Add stage to publish fleet-server docker image
  .ci/Jenkinsfile
  Makefile
  README.md
Labels: enhancement, Team:Fleet

#2458 [updatecli] update elastic stack version for testing 7.17.10-5423f09a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#2327 [Release] Update version to 8.7.1
  version/version.go
Labels: Team:Automation, release

#2462 [updatecli] update elastic stack version for testing 8.7.0-9232727f-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
