Repository elastic/fleet-server, pull requests merged in 2024-06, with the labels that each got.

#3476 [Release] Update version to 8.14.1
  version/version.go
Labels: Team:Automation, release

#3611 [Fleet] Replace findByApiKeyID with a get call when possible
  internal/pkg/api/auth.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/bulk/engine.go
  internal/pkg/bulk/opRead.go
  internal/pkg/bulk/schema.go
  internal/pkg/dl/agent.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/testing/bulk.go
Labels: Team:Elastic-Agent-Control-Plane

#3595 Enable E2E agent tests
  Makefile
  README.md
  Vagrantfile
  testing/e2e/agent_container_test.go
  testing/e2e/agent_install_test.go
  testing/go.mod
  testing/go.sum
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#3626 [Release] Update version to 8.14.2
  version/version.go
Labels: Team:Automation, release

#3632 Add github-actions to the allowed list for BK jobs
  .buildkite/pull-requests.json
Labels: backport-skip

#3627 [Release] Update version to 7.17.23
  main.go
Labels: Team:Automation, release

#3638 Allow bot triggered PRs to run CI
  .buildkite/pull-requests.json
Labels: backport-skip, ci

#3665 Updating github.com/elastic/beats dependency to latest 7.x release
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Elastic-Agent-Control-Plane
