Repository elastic/fleet-server, pull requests merged in 2024-04, with the labels that each got.

#3418 [Release] Update version to 8.13.2
  version/version.go
Labels: Team:Automation, release

#3404 [updatecli] update elastic stack version for testing 8.13.1-6f55db03-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3417 [updatecli] update elastic stack version for testing 7.17.20-b4f6d976-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3416 [updatecli] update elastic stack version for testing 8.14.0-20c1806a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3425 increase synthetic max poll
  .buildkite/pipeline.tests-staging.yaml
Labels: flaky-test

#3428 [updatecli] update elastic stack version for testing 7.17.20-3f8de4fb-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3426 [updatecli] update elastic stack version for testing 8.14.0-f2b0327c-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3431 [updatecli] update elastic stack version for testing 7.17.20-cded590f-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3433 [updatecli] update elastic stack version for testing 8.13.2-fcd9deb3-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3443 [updatecli] update elastic stack version for testing 8.13.2-948b05e8-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3432 [updatecli] update elastic stack version for testing 8.14.0-34b4df0a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3444 [Release] Update version to 8.13.3
  version/version.go
Labels: Team:Automation, release

#3446 [updatecli] update elastic stack version for testing 8.14.0-540ac545-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3442 [updatecli] update elastic stack version for testing 7.17.20-b0cf208a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3457 [updatecli] update elastic stack version for testing 7.17.20-53774e91-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3462 [updatecli] update elastic stack version for testing 7.17.21-c880ec9d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3461 [updatecli] update elastic stack version for testing 8.13.3-19734ad9-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3460 [updatecli] update elastic stack version for testing 8.14.0-cf1b0234-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3411 agent-mode loads output from policy
  changelog/fragments/1712108631-Use-policy-outputs-when-running-in-agent-mode.yaml
  internal/pkg/config/config.go
  internal/pkg/config/output.go
  internal/pkg/config/output_test.go
  internal/pkg/policy/self.go
  internal/pkg/policy/self_test.go
  internal/pkg/server/agent.go
  internal/pkg/server/fleet.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/server/fleet_secrets_integration_test.go
  internal/pkg/server/remote_es_output_integration_test.go
  internal/pkg/testing/log/log.go
  internal/pkg/testing/setup.go
Labels: enhancement, Team:Fleet

#3469 Update elastic-agent-libs to v0.9.4
  NOTICE.txt
  go.mod
  go.sum
  testing/go.mod
  testing/go.sum
Labels: bug, Team:Fleet

#3466 [updatecli] update elastic stack version for testing 7.17.21-29fdcf2a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3467 [updatecli] update elastic stack version for testing 8.13.3-b68daf90-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3471 [updatecli] update elastic stack version for testing 8.13.3-3dc31fcb-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3472 [updatecli] update elastic stack version for testing 7.17.21-e9b73307-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3477 [updatecli] update elastic stack version for testing 7.17.21-53490780-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3478 [updatecli] update elastic stack version for testing 8.14.0-318ae53b-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3479 [updatecli] update elastic stack version for testing 8.13.3-c9047748-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3481 [updatecli] update elastic stack version for testing 7.17.21-5d83bb4d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3480 [updatecli] update elastic stack version for testing 8.13.3-22bed9d1-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3484 Update elastic-agent-libs to v0.9.5
  NOTICE.txt
  go.mod
  go.sum
  testing/go.mod
  testing/go.sum
Labels: Team:Fleet, dependency

#3474 Bump the version on main to 8.15.0
  version/version.go
Labels: backport-skip

#3475 backport: Add 8.14 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, release, backport-v8.14.0

#3473 Update beats import to v7.17.20
  NOTICE.txt
  cmd/fleet/main_integration_test.go
  cmd/fleet/server.go
  dev-tools/notice/overrides.json
  go.mod
  go.sum
Labels: bug, backport, Team:Fleet

#3488 [updatecli] update elastic stack version for testing 8.13.3-94d3b00c-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3487 [updatecli] update elastic stack version for testing 7.17.21-5339d087-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3495 Revert "agent-mode loads output from policy"
  changelog/fragments/1712108631-Use-policy-outputs-when-running-in-agent-mode.yaml
  internal/pkg/config/config.go
  internal/pkg/config/output.go
  internal/pkg/config/output_test.go
  internal/pkg/policy/self.go
  internal/pkg/policy/self_test.go
  internal/pkg/server/agent.go
  internal/pkg/server/fleet.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/server/fleet_secrets_integration_test.go
  internal/pkg/server/remote_es_output_integration_test.go
  internal/pkg/testing/log/log.go
  internal/pkg/testing/setup.go
Labels: Team:Fleet, backport-v8.14.0

#3491 [updatecli] update elastic stack version for testing 8.13.3-6596e7ab-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3493 [updatecli] update elastic stack version for testing 8.14.0-1067ed11-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3494 [updatecli] update elastic stack version for testing 7.17.21-75fbaabb-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3498 [updatecli] update elastic stack version for testing 8.14.0-32f53a5b-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3492 [updatecli] update elastic stack version for testing 8.15.0-053650c4-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3497 [updatecli] update elastic stack version for testing 7.17.21-b7eaea35-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
