Repository elastic/fleet-server, pull requests merged in 2024-12, with the labels that each got.

#3986 Add timeout to bulker flush, add default case in failQueue
  changelog/fragments/1732889737-deadline-bulk-flush.yaml
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/bulk/engine.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#4169 Refactor API struct constructor
  changelog/fragments/1733164563-Refactor-API-struct-constructor.yaml
  internal/pkg/api/api.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/handleStatus.go
  internal/pkg/api/handleStatus_test.go
  internal/pkg/api/server.go
  internal/pkg/api/server_test.go
  internal/pkg/server/fleet.go
Labels: Team:Elastic-Agent-Control-Plane, tech debt, backport-8.x

#4156 On week improvements
  internal/pkg/checkin/bulk.go
  internal/pkg/server/agent.go
  internal/pkg/server/fleet.go
Labels: Team:Elastic-Agent-Control-Plane, tech debt, backport-8.x

#4168 Replace most context.TODO calls, comment on other Background and TODOs
  changelog/fragments/1733164018-Replace-use-of-context.TODO.yaml
  cmd/fleet/main.go
  internal/pkg/action/dispatcher.go
  internal/pkg/api/handleArtifacts.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleFileDelivery.go
  internal/pkg/api/handleUpload.go
  internal/pkg/api/metrics.go
  internal/pkg/api/server.go
  internal/pkg/bulk/engine.go
  internal/pkg/cache/cache.go
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/config/env_defaults.go
  internal/pkg/config/env_defaults_test.go
  internal/pkg/file/uploader/finalize.go
  internal/pkg/limit/listener.go
  internal/pkg/profile/profile.go
  internal/pkg/server/agent.go
  internal/pkg/server/fleet.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/state/reporter.go
  internal/pkg/testing/esutil/datastream.go
  internal/pkg/testing/esutil/esutil.go
  internal/pkg/testing/esutil/ilm.go
  internal/pkg/testing/esutil/index.go
  internal/pkg/testing/esutil/template.go
  internal/pkg/throttle/throttle.go
  internal/pkg/throttle/throttle_test.go
Labels: Team:Elastic-Agent-Control-Plane, tech debt, backport-8.x

#4171 Remove race condition when accessing remote bulker map
  changelog/fragments/1733181546-Remove-race-in-remote-bulker-access.yaml
  internal/pkg/bulk/bulk_remote_output_test.go
  internal/pkg/bulk/engine.go
Labels: bug, flaky-test, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.16, backport-8.17

#4182 Redact static tokens and custom http headers
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.16, backport-8.17

#4181 Prevent mapping explosion on logs
  internal/pkg/api/handleCheckin.go
  internal/pkg/server/fleet.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.16

#4221 Audit unenroll should not set unenrolled_at attribute
  changelog/fragments/1734380253-Audit-unenroll-does-not-set-unenrolled_at-attribute.yaml
  internal/pkg/api/handleAudit.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/checkin/deleteAuditFieldsOnCheckin.painless
  internal/pkg/server/fleet_integration_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.16, backport-8.17

#4152 Revert "Skip tests that depend on `8.18.0-SNAPSHOT` artifacts being available"
  .buildkite/pipeline.yml
  testing/e2e/agent_install_test.go
Labels: Team:Elastic-Agent-Control-Plane

#4238 Call tlscommon.SetInsecureDefaults
  internal/pkg/config/config.go
  internal/pkg/config/config_test.go
  internal/pkg/config/testdata/tls.yml
  internal/pkg/config/testdata/tls10.yml
Labels: backport, Team:Elastic-Agent-Control-Plane

#4256 Remove PGP endpoint auth requirement
  changelog/fragments/1735593163-Remove-auth-requirement-from-PGP-key-endpoint.yaml
  internal/pkg/api/error.go
  internal/pkg/api/handlePGPRequest.go
  internal/pkg/api/openapi.gen.go
  model/openapi.yml
  pkg/api/client.gen.go
  testing/e2e/api_version/client_api_current.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.16, backport-8.17
