Repository elastic/fleet-server, pull requests merged in 2024-09, with the labels that each got.

#3855 audit/unenroll orphaned reason will replace uninstalled
  internal/pkg/api/handleAudit.go
  internal/pkg/api/handleAudit_test.go
  internal/pkg/server/fleet_integration_test.go
  testing/e2e/api_version/client_api_current.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#3879 Automatically label PRs to `main` with `backport-v8.x`
  .mergify.yml
Labels: automation, backport-skip

#3885 mergify: add backport-v8.x always for main
  .mergify.yml
Labels: backport-v8.x

#3878 mergify: support for backport-major.minor
  .mergify.yml
Labels: backport-v8.x

#3891 mergify: replace queue action for queue_rules
  .mergify.yml
Labels: backport-8.x

#3892 mergify: avoid label automation always
  .mergify.yml
Labels: backport-8.x

#3889 Fix version source when making e2e agent image
  Makefile
  dev-tools/e2e/build.sh
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-8.x

#3924 Update go to 1.23.1
  .go-version
  .golangci.yml
  changelog/fragments/1726777859-Update-go-to-v1.23.1.yaml
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x

#3928 Update golangci-lint version
  .github/workflows/golangci-lint.yml
  Makefile
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleArtifacts.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleEnroll.go
  internal/pkg/api/handleStatus.go
  internal/pkg/api/openapi_spec_test.go
  internal/pkg/bulk/opMulti.go
  internal/pkg/cache/cache.go
  internal/pkg/config/env_defaults.go
  internal/pkg/dl/migration_integration_test.go
  internal/pkg/file/cbor/chunk.go
  internal/pkg/file/cbor/chunk_test.go
  internal/pkg/file/uploader/upload_test.go
  internal/pkg/logger/http.go
  internal/pkg/monitor/monitor.go
  internal/pkg/policy/policy_output_integration_test.go
  internal/pkg/scheduler/scheduler.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/testing/port.go
Labels: Team:Elastic-Agent-Control-Plane, tech debt, backport-8.x

#3935 Fix bad error handling in api key auth
  changelog/fragments/1726845328-Fix-authentication-return-error-code.yaml
  internal/pkg/apikey/auth.go
  internal/pkg/apikey/auth_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#3904 Fix test setup to run on ARM instances
  Dockerfile.build
  Makefile
  dev-tools/integration/docker-compose.yml
Labels: Team:Elastic-Agent-Control-Plane, tech debt, backport-8.x

#3938 Add make multipass target
  Makefile
  dev-tools/multipass-cloud-init.yml.envsubst
Labels: backport-skip, Team:Elastic-Agent-Control-Plane, tech debt

#3953 Unskip cloud E2E tests
  .buildkite/pipeline.yml
Labels: backport-8.x
