Repository elastic/fleet-server, pull requests merged in 2024-10, with the labels that each got.

#3965 Update go to 1.23.1
  .go-version
  .golangci.yml
Labels: Team:Elastic-Agent-Control-Plane

#3908 Add secret_paths attributes to policies sent to agents
  Makefile
  changelog/fragments/1726509909-Add-secret-paths-list-to-policies-sent-to-agents.yaml
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/openapi.gen.go
  internal/pkg/policy/parsed_policy.go
  internal/pkg/policy/secret.go
  internal/pkg/policy/secret_test.go
  internal/pkg/server/fleet_secrets_integration_test.go
  model/openapi.yml
  pkg/api/types.gen.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x

#3916 CP-7781 - switching bk pipeline to gpctl promote after synthetics
  .buildkite/pipeline.yml
Labels: Team:Elastic-Agent, backport-8.x

#3981 CP-7782 - Replace E2E pipeline execution with serverless-quality-gate…
  .buildkite/pipeline.tests-production.yaml
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#4001 Allow bulk integration tests to accept alternate errors from Elasticsearch
  internal/pkg/bulk/bulk_integration_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x

#3927 Add test collector plugin for Buildkite analytics
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#4014 backport: Add 8.16 branch
  .mergify.yml
Labels: Team:Elastic-Agent-Control-Plane, release, backport-8.x

#4012 [Integration testing] Remove AltErr and only expect 400 from ES bulk API
  internal/pkg/bulk/bulk_integration_test.go
Labels: cleanup, Team:Elastic-Agent-Control-Plane, backport-8.x

#3991 Don't fail checkin if agent has upgrade details with no action
  changelog/fragments/1728652985-Dont-fail-checkin-if-upgrade-action-not-found.yaml
  internal/pkg/api/handleCheckin.go
  testing/e2e/api_version/client_api_current.go
Labels: Team:Fleet, Team:Elastic-Agent-Control-Plane, backport-8.x

#4042 update elastic-agent-libs
  NOTICE.txt
  changelog/fragments/1729782694-Fleet-Server-uses-'ssl.verification_mode:-certificate'-by-default-for-incomming-client-connections.yaml
  go.mod
  go.sum
  testing/go.mod
  testing/go.sum
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.16

#4037 Support sampling rate in APM configuration
  internal/pkg/server/agent.go
  internal/pkg/server/agent_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.16
