Repository elastic/fleet-server, pull requests merged in 2024-11, with the labels that each got.

#4087 Update version of elastic/ec terraform provider to latest
  dev-tools/cloud/terraform/main.tf
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.16

#4090 Replace deprecated deployment template ID
  dev-tools/cloud/terraform/main.tf
Labels: Team:Elastic-Agent-Control-Plane, backport-8.16

#4065 [Release] Update version to 8.16.1
  version/version.go
Labels: Team:Elastic-Agent-Control-Plane, release

#4133 Skip tests that depend on `8.18.0-SNAPSHOT` artifacts being available
  .buildkite/pipeline.yml
  testing/e2e/agent_install_test.go
Labels: Team:Elastic-Agent-Control-Plane

#4141 [Fleet] Add version flag
  cmd/fleet/main.go
Labels: Team:Fleet, backport-8.x

#4142 Fix server.address field in HTTP logs
  changelog/fragments/1732279064-Fix-server.address-field-in-HTTP-logs.yaml
  internal/pkg/logger/http.go
  internal/pkg/logger/http_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-8.x

#4151 gh-actions: support 2.0 slack that contains a breaking change and the signature changed
  .github/workflows/bump-elastic-stack-snapshot.yml
  .github/workflows/bump-golang.yml
Labels: backport-8.x
