Repository elastic/fleet-server, pull requests merged in 2024-05, with the labels that each got.

#3502 [updatecli] update elastic stack version for testing 8.14.0-b1148041-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3501 [updatecli] update elastic stack version for testing 7.17.21-48567783-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3510 [updatecli] update elastic stack version for testing 8.13.3-dae2338c-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3500 [updatecli] update elastic stack version for testing 8.15.0-aa640648-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3503 [Release] Update version to 8.13.4
  version/version.go
Labels: Team:Automation, release

#3504 [Release] Update version to 7.17.22
  main.go
Labels: Team:Automation, release

#3514 [updatecli] update elastic stack version for testing 7.17.21-86bc1e1e-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3518 [updatecli] update elastic stack version for testing 7.17.21-4f451c48-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3517 [updatecli] update elastic stack version for testing 8.15.0-3eefdcff-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3513 [updatecli] update elastic stack version for testing 8.14.0-ba404a5d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3522 Fix remote ES client to use ssl.* settings
  Makefile
  dev-tools/integration/docker-compose.yml
  dev-tools/integration/get-elasticsearch-servicetoken.sh
  dev-tools/integration/wait-for-elasticsearch.sh
  internal/pkg/bulk/engine.go
  internal/pkg/server/remote_es_output_integration_test.go
Labels: bug, backport-skip, Team:Elastic-Agent-Control-Plane

#3511 [updatecli] update elastic stack version for testing 8.13.4-cc6fca83-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3528 [Automation] Bump Golang version to 1.21.10
  .go-version
  .golangci.yml
  changelog/fragments/1715195075-Upgrade-to-Go-1.21.10.yaml
Labels: Team:Elastic-Agent-Control-Plane, backport-v8.14.0

#3520 [updatecli] update elastic stack version for testing 7.17.22-60b5dd1b-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip, Team:Elastic-Agent-Control-Plane

#3519 [updatecli] update elastic stack version for testing 8.15.0-177234da-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip, Team:Elastic-Agent-Control-Plane

#3527 [Release] Update version to 8.13.5
  version/version.go
Labels: Team:Automation, release

#3521 [updatecli] update elastic stack version for testing 8.14.0-fd69f4fd-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip, Team:Elastic-Agent-Control-Plane

#3536 [updatecli] update elastic stack version for testing 8.14.0-99ead9e9-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3534 [updatecli] update elastic stack version for testing 8.13.5-f94896f6-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip, Team:Elastic-Agent-Control-Plane

#3538 [updatecli] update elastic stack version for testing 8.14.0-15ba0fb2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3542 [updatecli] update elastic stack version for testing 8.13.5-a2355063-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3541 [updatecli] update elastic stack version for testing 8.15.0-2d092d81-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3540 [updatecli] update elastic stack version for testing 8.14.0-0e5b6971-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3543 [updatecli] update elastic stack version for testing 8.14.0-526ba7a5-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3546 [updatecli] update elastic stack version for testing 8.13.5-28857d3f-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3545 [updatecli] update elastic stack version for testing 8.15.0-00171e66-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3544 [updatecli] update elastic stack version for testing 7.17.22-3c259c3f-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3535 Pass namespaces to Fleet Server managed documents
  changelog/fragments/1715862782-support-namespaces.yaml
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleAck_test.go
  internal/pkg/api/handleEnroll.go
  internal/pkg/api/handleEnroll_test.go
  internal/pkg/api/handleUpload.go
  internal/pkg/file/file.go
  internal/pkg/file/uploader/upload.go
  internal/pkg/file/uploader/upload_test.go
  internal/pkg/model/schema.go
  internal/pkg/server/namespaces_integration_test.go
  model/schema.json
Labels: Team:Elastic-Agent-Control-Plane

#3551 [updatecli] update elastic stack version for testing 7.17.22-f8bdfabc-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3550 [updatecli] update elastic stack version for testing 8.15.0-c0a6b373-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3549 [updatecli] update elastic stack version for testing 8.13.5-201eb198-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3556 [updatecli] update elastic stack version for testing 8.15.0-9593fdd6-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3558 [updatecli] update elastic stack version for testing 8.14.0-be62218d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3557 [updatecli] update elastic stack version for testing 8.13.5-05470747-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3555 [updatecli] update elastic stack version for testing 7.17.22-6a08b6db-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3564 [updatecli] update elastic stack version for testing 7.17.22-cc1e0082-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3563 [updatecli] update elastic stack version for testing 8.13.5-3f0620ae-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3562 [updatecli] update elastic stack version for testing 8.14.0-f5ce0819-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3561 [updatecli] update elastic stack version for testing 8.15.0-1a872dbc-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3559 chore(deps): update docker.elastic.co/ci-agent-images/quality-gate-seedling docker tag to v0.0.4
  .buildkite/pipeline.fleet-server-tests.yaml
Labels: Team:Fleet

#3565 github-actions: use GitHub secrets
  .github/workflows/bump-elastic-stack-snapshot.yml
  .github/workflows/bump-golang.yml
Labels: Team:Elastic-Agent-Control-Plane

#3506 Agent mode support for bootstrap output
  changelog/fragments/1714519181-Agent-mode-support-for-bootstrap-output.yaml
  internal/pkg/server/agent.go
  internal/pkg/server/agent_integration_test.go
  internal/pkg/server/agent_test.go
  internal/pkg/server/fleet.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#3568 [updatecli] update elastic stack version for testing 8.15.0-73defe35-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3569 [updatecli] update elastic stack version for testing 7.17.22-13d5abd0-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3567 [updatecli] update elastic stack version for testing 8.13.5-d5b1e962-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3572 Fix flaky cert tests
  internal/pkg/api/server_test.go
Labels: flaky-test, Team:Elastic-Agent-Control-Plane, backport-v8.13.0, backport-v8.14.0
