Repository elastic/fleet-server, pull requests merged in 2024-01, with the labels that each got.

#3177 added download_rate to openapi
  NOTICE.txt
  internal/pkg/api/openapi.gen.go
  internal/pkg/api/openapi_spec_test.go
  model/openapi.yml
  pkg/api/types.gen.go
Labels: enhancement, v8.12.0

#3197 [8.12] added download_rate to openapi (#3177)
  NOTICE.txt
  internal/pkg/api/openapi.gen.go
  internal/pkg/api/openapi_spec_test.go
  model/openapi.yml
  pkg/api/types.gen.go
Labels: backport, v8.12.0

#3194 [updatecli] update elastic stack version for testing 8.11.4-05ba2d97-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3192 [updatecli] update elastic stack version for testing 7.17.17-33216749-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3193 [updatecli] update elastic stack version for testing 8.12.0-2335225c-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3200 [updatecli] update elastic stack version for testing 8.11.4-c8acd73b-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3191 [updatecli] update elastic stack version for testing 8.13.0-toucn398-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3201 Add mtls attributes to reference and unit tests
  fleet-server.reference.yml
  internal/pkg/api/server_test.go
  internal/pkg/es/client_test.go
  internal/pkg/monitor/mock/monitor.go
  internal/pkg/testing/certs/certs.go
Labels: enhancement, Team:Fleet

#3203 [updatecli] update elastic stack version for testing 8.12.0-a87bc5c4-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3202 [updatecli] update elastic stack version for testing 8.13.0-ybxdr713-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3206 fix multiple secret ref replace
  internal/pkg/policy/secret.go
  internal/pkg/policy/secret_test.go
Labels: bug, backport-v8.12.0

#3208 [updatecli] update elastic stack version for testing 8.11.4-8881462e-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3210 [updatecli] update elastic stack version for testing 7.17.17-95dddbc3-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3217 [Release] Update version to 8.11.5
  version/version.go
Labels: Team:Automation, release

#3212 [updatecli] update elastic stack version for testing 8.11.4-2da4f338-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3213 [updatecli] update elastic stack version for testing 8.13.0-u5089rwg-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3215 [updatecli] update elastic stack version for testing 7.17.17-0b4d6d87-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3218 [Fleet] Ignore not yet created .fleet-policies index
  internal/pkg/bulk/bulk_integration_test.go
  internal/pkg/bulk/opSearch.go
  internal/pkg/bulk/opt.go
  internal/pkg/dl/policies.go
Labels: Team:Fleet

#3216 [Automation] Bump Golang version to 1.21.6
  .go-version
  .golangci.yml
Labels: backport-skip

#3223 Add Kibana + Fleet Server dev guide link to README
  README.md
Labels: docs

#3224 Update elastic-agent-libs to v0.7.4
  NOTICE.txt
  go.mod
  go.sum
Labels: Team:Fleet, tech debt

#3221 [updatecli] update elastic stack version for testing 7.17.17-1107dfdb-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3220 [updatecli] update elastic stack version for testing 8.13.0-sq0d327c-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3147 [Release] Update version to 8.12.1
  version/version.go
Labels: Team:Automation, release

#3226 [updatecli] update elastic stack version for testing 7.17.17-bf0a38e4-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3227 [updatecli] update elastic stack version for testing 8.13.0-knq1zsti-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3231 [Release] Update version to 7.17.18
  main.go
Labels: Team:Automation, release

#3232 Add e2e test for timeout and 429 on startup
  testing/e2e/stand_alone_test.go
  testing/e2e/statusProxy.go
  testing/e2e/testdata/stand-alone-http-proxy.tpl
Labels: bug, Team:Fleet

#3233 Stricter validation for required checkin API attributes
  changelog/fragments/1705963635-Stricter-validation-for-required-checkin-API-attributes.yaml
  internal/pkg/api/handleCheckin.go
  internal/pkg/server/fleet_integration_test.go
  testing/e2e/api_version/client_api_2023_06_01.go
  testing/e2e/api_version/client_api_current.go
Labels: bug, Team:Fleet

#3230 [updatecli] update elastic stack version for testing 7.17.17-36eb4463-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3235 Change response codes for elasticsearch failures to 503
  changelog/fragments/1706127160-Change-response-codes-for-elasticsearch-failures-to-503.yaml
  internal/pkg/api/error.go
  internal/pkg/api/error_test.go
Labels: enhancement, Team:Fleet

#3242 migrate DRA gcp bucket
  .buildkite/hooks/pre-command
  .buildkite/scripts/common.sh
Labels: backport-v7.17.0, ci, backport-v8.12.0

#3225 [updatecli] update elastic stack version for testing 8.12.1-lipljxnp-SNAPSHOT
  .buildkite/hooks/pre-command
  .buildkite/scripts/common.sh
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3238 [updatecli] update elastic stack version for testing 7.17.18-b8c750dd-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3241 remove io.ReadAll from bulker and API endpoints
  internal/pkg/api/handleAck.go
  internal/pkg/api/handlePGPRequest.go
  internal/pkg/bulk/helpers.go
Labels: Team:Fleet, tech debt

#3246 [updatecli] update elastic stack version for testing 8.12.1-3x3y2wtd-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3236 [updatecli] update elastic stack version for testing 8.13.0-yil7wib0-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
