Repository elastic/fleet-server, pull requests merged in 2024-07, with the labels that each got.

#3676 Update go to v1.22.4
  .go-version
  .golangci.yml
  changelog/fragments/1719961369-Update-go-to-v1.22.4.yaml
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#3677 [Fleet] Support download rate in string with unit format
  NOTICE.txt
  changelog/fragments/1720021515-fix_download_rate.yaml
  go.mod
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/metadata.go
  internal/pkg/api/metadata_test.go
Labels: Team:Fleet, Team:Elastic-Agent-Control-Plane, backport-v8.15.0

#3131 Remove the coordinator
  changelog/fragments/1701298362-Remove-policy-coordinator.yaml
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleAck_test.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/coordinator/coordinator.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/coordinator/monitor_integration_test.go
  internal/pkg/coordinator/v0.go
  internal/pkg/coordinator/v0_test.go
  internal/pkg/dl/constants.go
  internal/pkg/dl/migration.go
  internal/pkg/dl/migration_integration_test.go
  internal/pkg/dl/policies.go
  internal/pkg/dl/policies_integration_test.go
  internal/pkg/dl/policies_leader.go
  internal/pkg/dl/policies_leader_integration_test.go
  internal/pkg/dl/servers.go
  internal/pkg/dl/servers_integration_test.go
  internal/pkg/model/schema.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/policy/monitor_test.go
  internal/pkg/policy/revision.go
  internal/pkg/policy/self_test.go
  internal/pkg/policy/sub.go
  internal/pkg/policy/sub_test.go
  internal/pkg/server/fleet.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/server/namespaces_integration_test.go
  internal/pkg/server/remote_es_output_integration_test.go
  model/schema.json
Labels: Team:Fleet, tech debt

#3692 [backport 7.17]Update elastic-agent-client to v7.8.1
  NOTICE.txt
  go.mod
  go.sum
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#3706 Update pipeline.tests-staging.yaml
  .buildkite/pipeline.tests-staging.yaml
Labels: bug

#3693 Add github vault plugin bot to allowed list
  .buildkite/pull-requests.json
Labels: backport-skip

#3729 Fix log message
  internal/pkg/monitor/subscription_monitor.go
Labels: cleanup, backport-v8.15.0

#3700 Switch to PAT generated token
  .buildkite/hooks/pre-command
Labels: backport-v7.17.0, ci, backport-v8.14.0, backport-v8.15.0

#3760 Switch the base Docker image to Wolfi
  Dockerfile
Labels: enhancement, backport-skip, Team:Elastic-Agent-Control-Plane

#3751 Update github.com/elastic/beats/v7
  NOTICE.txt
  go.mod
  go.sum
Labels: enhancement, Team:Elastic-Agent-Control-Plane
