Repository elastic/fleet-server, pull requests merged in 2024-08, with the labels that each got.

#3789 Fix-DRA-curl-command
  .buildkite/hooks/pre-command
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-v7.17.0, backport-v8.14.0, backport-v8.15.0

#3798 Adding fail catch to curl command
  .buildkite/hooks/pre-command
Labels: Team:Elastic-Agent-Control-Plane, backport-v7.17.0, backport-v8.14.0, backport-v8.15.0

#3818 Add `/api/fleet/agents/:id/audit/unenroll` endpoint
  changelog/fragments/1723590385-Add-audit-unenroll-API.yaml
  fleet-server.reference.yml
  internal/pkg/api/api.go
  internal/pkg/api/error.go
  internal/pkg/api/handleAudit.go
  internal/pkg/api/handleAudit_test.go
  internal/pkg/api/metrics.go
  internal/pkg/api/openapi.gen.go
  internal/pkg/api/router.go
  internal/pkg/api/router_test.go
  internal/pkg/api/server.go
  internal/pkg/api/server_test.go
  internal/pkg/config/defaults/lte10000_limits.yml
  internal/pkg/config/defaults/lte20000_limits.yml
  internal/pkg/config/defaults/lte2500_limite.yml
  internal/pkg/config/defaults/lte40000_limits.yml
  internal/pkg/config/defaults/lte5000_limits.yml
  internal/pkg/config/defaults/max_limits.yml
  internal/pkg/config/env_defaults.go
  internal/pkg/config/limits.go
  internal/pkg/dl/constants.go
  internal/pkg/model/schema.go
  internal/pkg/server/fleet.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/testing/setup.go
  model/openapi.yml
  model/schema.json
  pkg/api/client.gen.go
  pkg/api/types.gen.go
  testing/e2e/api_version/client_api_current.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#3827 Alter checkin API to remove attributes set by audit/unenroll API
  changelog/fragments/1724283895-Checkin-after-audit-unenroll-API.yaml
  internal/pkg/api/handleCheckin.go
  internal/pkg/checkin/bulk.go
  internal/pkg/checkin/bulk_test.go
  internal/pkg/checkin/deleteAuditFieldsOnCheckin.painless
  internal/pkg/server/fleet_integration_test.go
  testing/e2e/api_version/client_api_current.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#3835 Cleanup integration test setup
  Makefile
  dev-tools/e2e/docker-compose.yml
  dev-tools/integration/docker-compose.yml
  dev-tools/integration/elasticsearch.yml
  dev-tools/integration/wait-for-elasticsearch.sh
Labels: Team:Elastic-Agent-Control-Plane, tech debt
