Repository elastic/fleet-server, pull requests merged in 2024-03, with the labels that each got.

#3320 [updatecli] update elastic stack version for testing 8.13.0-67f2fee7-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3319 [updatecli] update elastic stack version for testing 8.12.3-3f627ed1-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3318 [updatecli] update elastic stack version for testing 7.17.19-471911c1-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3317 [updatecli] update elastic stack version for testing 8.14.0-14244116-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3295 Make benchmarks more consistent
  .buildkite/pipeline.yml
  .buildkite/scripts/run_benchmark.sh
  Makefile
  internal/pkg/api/handleAck_test.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/bulk/bulk_integration_test.go
  internal/pkg/bulk/bulk_test.go
  internal/pkg/bulk/opMulti_integration_test.go
  internal/pkg/bulk/opMulti_test.go
  internal/pkg/checkin/bulk_test.go
  internal/pkg/dsl/tmpl_test.go
  internal/pkg/policy/sub_test.go
Labels: Team:Fleet

#3327 [Automation] Bump Golang version to 1.21.8
  .go-version
  .golangci.yml
Labels: backport-skip

#3322 [updatecli] update elastic stack version for testing 8.13.0-863a113a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3324 [updatecli] update elastic stack version for testing 7.17.19-542eded5-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3325 [updatecli] update elastic stack version for testing 8.12.3-39cea920-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3323 [updatecli] update elastic stack version for testing 8.14.0-37cbef48-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3335 Stop self monitor output health reporting if output config is not ack…
  changelog/fragments/1710157707-fix-self-monitor-output-health.yaml
  internal/pkg/bulk/engine.go
  internal/pkg/policy/self.go
  internal/pkg/policy/self_test.go
  internal/pkg/testing/bulk.go
Labels: bug

#3330 [updatecli] update elastic stack version for testing 7.17.19-1b83f14d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3331 [updatecli] update elastic stack version for testing 8.13.0-6815ad42-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3332 [updatecli] update elastic stack version for testing 8.12.3-00a3f705-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3329 [updatecli] update elastic stack version for testing 8.14.0-8783136e-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3339 [updatecli] update elastic stack version for testing 7.17.19-cd4b6257-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3342 [updatecli] update elastic stack version for testing 8.12.3-98aa2390-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3340 [updatecli] update elastic stack version for testing 8.14.0-faa2d2d3-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3341 [updatecli] update elastic stack version for testing 8.13.0-72b525a7-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3337 Update elastic agent client to v7.8.0
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/server/agent.go
  internal/pkg/server/agent_integration_test.go
  testing/go.mod
  testing/go.sum
Labels: Team:Fleet

#3350 Allow level: trace in settings action
  changelog/fragments/1710319964-Allow-level:-trace-for-settings-actions.yaml
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/openapi.gen.go
  model/openapi.yml
  pkg/api/types.gen.go
Labels: enhancement, Team:Fleet

#3356 [updatecli] update elastic stack version for testing 7.17.19-0b4cdbdc-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3358 [updatecli] update elastic stack version for testing 8.12.3-530f08ed-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3357 [updatecli] update elastic stack version for testing 8.13.0-e56dde0a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3359 Fix dependabot label
  .github/dependabot.yml
Labels: Team:Fleet

#3338 Calculate unhealthy reason (input/output/other) on agent documents
  changelog/fragments/1710256335-add-unhealthy-reason.yaml
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/checkin/bulk.go
  internal/pkg/checkin/bulk_test.go
  internal/pkg/dl/constants.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: enhancement

#3361 [updatecli] update elastic stack version for testing 8.13.0-099ad3d3-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3363 [updatecli] update elastic stack version for testing 8.12.3-068eda6a-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3362 [updatecli] update elastic stack version for testing 7.17.19-023068fa-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3364 [updatecli] update elastic stack version for testing 8.14.0-a2d5464c-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3369 [updatecli] update elastic stack version for testing 8.14.0-09a11c1c-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3371 [updatecli] update elastic stack version for testing 8.12.3-38b17954-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3370 [updatecli] update elastic stack version for testing 8.13.0-a9fbad89-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3368 [updatecli] update elastic stack version for testing 7.17.19-a2ab9cd7-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3353 Add go.mod to pkg/api
  NOTICE.txt
  go.mod
  go.sum
  pkg/api/go.mod
  pkg/api/go.sum
  testing/e2e/README.md
  testing/e2e/api_version/client_api_2023_06_01.go
  testing/e2e/api_version/client_api_current.go
  testing/go.mod
  testing/go.sum
Labels: Team:Fleet

#3376 [updatecli] update elastic stack version for testing 8.14.0-892adbf2-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3375 [updatecli] update elastic stack version for testing 8.13.0-de4951fb-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3374 [updatecli] update elastic stack version for testing 7.17.19-b8d7cdf4-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3377 [updatecli] update elastic stack version for testing 8.12.3-ef3d6214-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3381 [updatecli] update elastic stack version for testing 8.12.3-f215049e-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3382 [updatecli] update elastic stack version for testing 8.14.0-14d688f1-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3383 [updatecli] update elastic stack version for testing 8.13.0-32b2aea6-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3385 Rename file to remove invalid char
  changelog/fragments/1710319964-Allow-level-trace-for-settings-actions.yaml
Labels: Team:Fleet

#3388 Fix push docker image script: only push to latest tag if on main
  .buildkite/scripts/build_push_docker_image.sh
Labels: bug

#3390 [updatecli] update elastic stack version for testing 8.14.0-c03b2a22-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3389 [updatecli] update elastic stack version for testing 7.17.19-e408206f-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3393 fix for docker image script
  .buildkite/scripts/build_push_docker_image.sh
Labels: bug

#3391 Update beats import to v7.17.18
  Makefile
  NOTICE.txt
  cmd/fleet/main_integration_test.go
  dev-tools/notice/overrides.json
  go.mod
  go.sum
Labels: backport, Team:Fleet, tech debt

#3395 [updatecli] update elastic stack version for testing 8.14.0-0321523b-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3394 [updatecli] update elastic stack version for testing 8.13.0-11aed950-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3399 [updatecli] update elastic stack version for testing 8.14.0-4e9e4428-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3400 [updatecli] update elastic stack version for testing 8.13.0-72a3bf67-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3401 [updatecli] update elastic stack version for testing 7.17.19-69bcc6b5-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3402 [updatecli] update elastic stack version for testing 8.12.3-96ef37fe-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3282 [Release] Update version to 8.13.1
  version/version.go
Labels: Team:Automation, release

#3378 [Release] Update version to 7.17.20
  main.go
Labels: Team:Automation, release

#3405 [updatecli] update elastic stack version for testing 8.14.0-433ba96e-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3403 [updatecli] update elastic stack version for testing 7.17.19-72c65e83-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3406 [Fleet] Change action and policy rate limiter error log level to warn
  internal/pkg/action/dispatcher.go
  internal/pkg/policy/monitor.go
Labels: Team:Fleet

#3410 [updatecli] update elastic stack version for testing 8.14.0-7d0b3a7e-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3414 [updatecli] update elastic stack version for testing 8.14.0-3267fa9f-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip
