Repository elastic/fleet-server, pull requests merged in 2024-02, with the labels that each got.

#3243 [Buildkite] Ignore non successful exit code in cloud-deploy target (test-cloude2e)
  Makefile
  dev-tools/cloud/Makefile
  dev-tools/cloud/launch_cloud_e2e_tests.sh
Labels: Team:Fleet, ci

#3249 [Buildkite] Update terraform ec provider for Cloud E2E tests step
  .buildkite/pipeline.yml
  dev-tools/cloud/terraform/main.tf
  dev-tools/cloud/terraform/outputs.tf
Labels: Team:Fleet, ci

#3257 [Release] Update version to 7.17.19
  main.go
Labels: Team:Automation, release

#3256 [Release] Update version to 8.12.2
  version/version.go
Labels: Team:Automation, release

#3234 Add policy monitor debounce time
  changelog/fragments/1706034813-Add-policy_debounce_time-to-monitor.yaml
  fleet-server.reference.yml
  internal/pkg/bulk/engine.go
  internal/pkg/bulk/opBulk.go
  internal/pkg/config/config_test.go
  internal/pkg/config/monitor.go
  internal/pkg/monitor/monitor.go
  internal/pkg/monitor/monitor_integration_test.go
  internal/pkg/monitor/subscription_monitor.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/policy/policy_output.go
  internal/pkg/server/fleet.go
  internal/pkg/testing/actions.go
  internal/pkg/testing/bulk.go
  internal/pkg/testing/rnd/rnd.go
Labels: enhancement, Team:Fleet

#3252 [updatecli] update elastic stack version for testing 7.17.18-18102b55-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3250 [updatecli] update elastic stack version for testing 8.12.1-6b6cce09-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3251 [updatecli] update elastic stack version for testing 8.13.0-c6fcd738-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3259 [Automation] Bump Golang version to 1.21.7
  .go-version
  .golangci.yml
Labels: backport-skip

#3253 [CI] MacOS 13 Unit tests
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/local_build.sh
  Makefile
  sonar-project.properties
Labels: enhancement

#3247 make str log fields consistent
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleAck_test.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/bulk/engine.go
  internal/pkg/coordinator/monitor.go
  internal/pkg/dl/policies.go
  internal/pkg/logger/ecs.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/policy_output.go
  internal/pkg/policy/self.go
Labels: cleanup

#3255 Replace policy and action limiters with a checkin limiter
  changelog/fragments/1707246268-Move-action-limiter-to-checkin-response-writer.yaml
  fleet-server.reference.yml
  internal/pkg/action/dispatcher.go
  internal/pkg/action/dispatcher_test.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/server_test.go
  internal/pkg/config/defaults/lte10000_limits.yml
  internal/pkg/config/defaults/lte20000_limits.yml
  internal/pkg/config/defaults/lte2500_limite.yml
  internal/pkg/config/defaults/lte40000_limits.yml
  internal/pkg/config/defaults/lte5000_limits.yml
  internal/pkg/config/defaults/max_limits.yml
  internal/pkg/config/env_defaults.go
  internal/pkg/config/limits.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/policy/monitor_test.go
  internal/pkg/server/fleet.go
Labels: enhancement, Team:Fleet

#3262 github-action: use wildcards for discovering all the workflows
  .github/workflows/opentelemetry.yml
Labels: backport-skip

#3260 Fix fleet-server.reference.yml indentation
  fleet-server.reference.yml
Labels: Feature:fleet-server, Team:Fleet, backport-v8.12.0

#3258 [updatecli] update elastic stack version for testing 8.12.2-ae12c9ba-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3261 [updatecli] update elastic stack version for testing 8.13.0-4cf79044-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3264 fix process upgrade details when null
  changelog/fragments/1707481003-fix-upgraded-at.yaml
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: bug, backport-v8.12.0

#3269 make revision idx log fields consistent
  internal/pkg/policy/monitor.go
Labels: enhancement

#3274 Revert "Replace policy and action limiters with a checkin limiter"
  changelog/fragments/1702940211-Replace-policy-throttle-with-limiter.yaml
  fleet-server.reference.yml
  internal/pkg/action/dispatcher.go
  internal/pkg/action/dispatcher_test.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/server_test.go
  internal/pkg/config/defaults/lte10000_limits.yml
  internal/pkg/config/defaults/lte20000_limits.yml
  internal/pkg/config/defaults/lte2500_limite.yml
  internal/pkg/config/defaults/lte40000_limits.yml
  internal/pkg/config/defaults/lte5000_limits.yml
  internal/pkg/config/defaults/max_limits.yml
  internal/pkg/config/env_defaults.go
  internal/pkg/config/limits.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/policy/monitor_test.go
  internal/pkg/server/fleet.go
Labels: Team:Fleet

#3271 [updatecli] update elastic stack version for testing 7.17.19-53e789c3-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3277 Consume APMConfig from input units in agent mode
  changelog/fragments/1707852625-Prefer-elastic-agent-client-APMConfig-in-agent-mode.yaml
  internal/pkg/server/agent.go
  internal/pkg/server/agent_test.go
Labels: enhancement, Team:Fleet

#3280 Bump the version on main to 8.14.0
  version/version.go
Labels: backport-skip

#3275 [updatecli] update elastic stack version for testing 7.17.19-c3e20ba6-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3270 [updatecli] update elastic stack version for testing 8.12.2-5f8ffc93-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3284 [updatecli] update elastic stack version for testing 7.17.19-0343082b-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3288 [updatecli] update elastic stack version for testing 7.17.19-fc9da510-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3287 [updatecli] update elastic stack version for testing 8.12.2-0bde1b22-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3294 [updatecli] update elastic stack version for testing 8.12.2-bf518ba4-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3276 [updatecli] update elastic stack version for testing 8.14.0-8dc05a81-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3286 Skip flakey subtest
  internal/pkg/api/server_test.go
Labels: flaky-test, backport-v8.13.0

#3285 [updatecli] update elastic stack version for testing 8.13.0-466f28cb-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3281 backport: Add 8.13 branch
  .mergify.yml
Labels: Team:Automation, impact:critical, release, backport-v8.13.0

#3303 [updatecli] update elastic stack version for testing 7.17.19-74d9fe02-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3302 [updatecli] update elastic stack version for testing 8.13.0-c44bedb9-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3301 [updatecli] update elastic stack version for testing 8.14.0-74a79bf3-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3312 [updatecli] update elastic stack version for testing 8.13.0-6775ba34-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3311 [updatecli] update elastic stack version for testing 8.14.0-d7334334-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3313 [updatecli] update elastic stack version for testing 8.12.2-5482c56d-SNAPSHOT
  dev-tools/integration/.env
Labels: automation, dependency, backport-skip

#3314 Use fleet-server binary version for cloude2e images
  Makefile
  dev-tools/cloud/docker/build.sh
Labels: Team:Fleet, backport-v8.12.0, backport-v8.13.0

#3292 [Release] Update version to 8.12.3
  version/version.go
Labels: Team:Automation, release
