Repository elastic/fleet-server, pull requests merged in 2025-02, with the labels that each got.

#4403 Use --develop flag for agent install e2e tests
  dev-tools/e2e/kibana.yml
  dev-tools/integration/.env
  testing/e2e/agent_install_test.go
  testing/e2e/const.go
  testing/e2e/const_windows.go
Labels: Team:Elastic-Agent-Control-Plane, tech debt, backport-9.0

#4405 Upgrade x/crypto and x/net to latest
  NOTICE.txt
  changelog/fragments/1738701949-Upgrade-golang.org-x-net-to-v0.34.0-and-golang.org-x-crypto-to-v0.32.0..yaml
  go.mod
  go.sum
  testing/go.mod
  testing/go.sum
Labels: Team:Elastic-Agent-Control-Plane, backport-7.17, backport-8.x, backport-8.16, backport-8.17, backport-8.18, backport-9.0

#4404 mergify: support backport-active-8, backport-active-9 and backport-active-all
  .mergify.yml
Labels: backport-skip

#4420 mergify: support 8.x for the backport-active-8
  .mergify.yml
Labels: backport-skip

#4354 deps(github-actions): bump updatecli version
  .ci/bump-golang.yml
  .github/dependabot.yml
  .github/workflows/bump-elastic-stack-snapshot.yml
  .github/workflows/bump-golang.yml
Labels: backport-8.x

#4402 Use chi/middleware.Throttle instead of custom conn limiter
  changelog/fragments/1738613859-Return-HTTP-429-when-conn-limit-is-reached.yaml
  fleet-server.reference.yml
  internal/pkg/api/router.go
  internal/pkg/api/server.go
  internal/pkg/limit/listener.go
Labels: bug, Team:Elastic-Agent-Control-Plane

#4433 ci: enable 9.* branches
  catalog-info.yaml
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#4475 Remove Team:Fleet from dependabot.yml
  .github/dependabot.yml
Labels: cleanup, backport-active-all

#4469 [CI] Update Buildkite configuration for tags in main pipeline
  catalog-info.yaml
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#4472 Fix docker image build for FIPS variants
  .buildkite/pipeline.yml
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Dockerfile.fips
  Makefile
  dev-tools/e2e/Dockerfile
  dev-tools/e2e/build.sh
  testing/e2e/agent_container_test.go
  testing/e2e/agent_install_test.go
  testing/e2e/fips_test.go
  testing/e2e/stand_alone_api_test.go
  testing/e2e/stand_alone_container_test.go
  testing/e2e/stand_alone_test.go
  testing/e2e/statusProxy.go
Labels: Team:Elastic-Agent-Control-Plane, tech debt, backport-active-9, backport-active-8

#4514 Add unit test for fips metadata attribute in enroll/checkin
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/handleEnroll_test.go
  internal/pkg/checkin/bulk_test.go
Labels: Team:Elastic-Agent-Control-Plane, tech debt, backport-8.18, backport-9.0
