Repository elastic/fleet-server, pull requests merged in 2025-04, with the labels that each got.

#4762 Clear upgrade_attempts on handleAck
  internal/pkg/api/handleAck.go
  internal/pkg/api/handleAck_test.go
Labels: enhancement, backport-skip, Team:Elastic-Agent-Control-Plane

#4765 Fix diagnostic requests when scheme is not included in host
  changelog/fragments/1743692296-fix-url-parsing-es-output-diagnostics.yaml
  internal/pkg/config/output.go
  internal/pkg/config/output_test.go
Labels: Team:Elastic-Agent-Control-Plane, backport-active-9, backport-active-8

#4775 Redact output log lines during bootstrap config
  changelog/fragments/1744046917-Redact-output-in-bootstrap-config-logs.yaml
  internal/pkg/config/config.go
  internal/pkg/server/agent.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-active-all

#4797 mergify: new way of backporting to active branches
  .github/workflows/backport-active.yml
  .mergify.yml
Labels: enhancement, backport-skip, Team:Elastic-Agent-Control-Plane, backport-active-9

#4819 Rename buildkite test step to avoid confusion
  .buildkite/pipeline.yml
Labels: Team:Elastic-Agent-Control-Plane, tech debt, backport-8.x

#4840 Fix linter config
  .golangci.yml
Labels: Team:Elastic-Agent-Control-Plane, tech debt

#4820 Add version metadata to version command
  changelog/fragments/1744831791-Add-version-metadata-to-version-command-output.yaml
  cmd/fleet/main.go
  internal/pkg/build/build.go
  internal/pkg/build/fips.go
  internal/pkg/build/nofips.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.19

#4839 Add rollback attribute to upgrade actions
  changelog/fragments/1745450998-Add-rollback-attribute-to-Upgrade-actions.yaml
  internal/pkg/api/openapi.gen.go
  model/openapi.yml
  pkg/api/types.gen.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#4847 Update testing dependencies and fix issues with toxiproxy
  testing/e2e/scaffold/scaffold.go
  testing/e2e/stand_alone_container_test.go
  testing/e2e/stand_alone_test.go
  testing/go.mod
  testing/go.sum
Labels: backport-skip, Team:Elastic-Agent-Control-Plane, tech debt
