Repository elastic/fleet-server, pull requests merged in 2025-05, with the labels that each got.

#4786 Added new `MIGRATE` action type
  changelog/fragments/1744623226-migrate-action.yaml
  internal/pkg/api/handleAck_test.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/openapi.gen.go
  model/openapi.yml
  pkg/api/types.gen.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-active-9

#4836 catalog-info: run 7.17 DRA weekly
  catalog-info.yaml
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#4875 Remove context.background and variable copy from test case
  internal/pkg/action/dispatcher_test.go
  internal/pkg/api/error_test.go
  internal/pkg/api/handleAudit_test.go
  internal/pkg/api/handlePGPRequest_test.go
  internal/pkg/api/metrics_integration_test.go
  internal/pkg/api/openapi_spec_test.go
  internal/pkg/apikey/apikey_integration_test.go
  internal/pkg/apikey/auth_test.go
  internal/pkg/bulk/bulk_integration_test.go
  internal/pkg/bulk/bulk_remote_output_test.go
  internal/pkg/bulk/bulk_test.go
  internal/pkg/bulk/opMulti_integration_test.go
  internal/pkg/bulk/opMulti_test.go
  internal/pkg/checkin/bulk_test.go
  internal/pkg/dl/action_results_integration_test.go
  internal/pkg/dl/actions_integration_test.go
  internal/pkg/dl/agent_integration_test.go
  internal/pkg/dl/enrollment_api_key_integration_test.go
  internal/pkg/dl/migration_integration_test.go
  internal/pkg/dl/policies_integration_test.go
  internal/pkg/es/client_test.go
  internal/pkg/file/delivery/delivery_test.go
  internal/pkg/file/es_test.go
  internal/pkg/file/uploader/upload_test.go
  internal/pkg/gc/actions_integration_test.go
  internal/pkg/logger/http_test.go
  internal/pkg/logger/logger_test.go
  internal/pkg/monitor/monitor_integration_test.go
  internal/pkg/monitor/subscription_monitor_integration_test.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/policy/policy_output_integration_test.go
  internal/pkg/profile/profile_test.go
  internal/pkg/server/agent_test.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/server/fleet_secrets_integration_test.go
  internal/pkg/server/fleet_test.go
  internal/pkg/server/namespaces_integration_test.go
  internal/pkg/server/remote_es_output_integration_test.go
  internal/pkg/ver/check_test.go
Labels: Team:Elastic-Agent-Control-Plane

#4892 Revert "Remove context.background and variable copy from test case"
  internal/pkg/action/dispatcher_test.go
  internal/pkg/api/error_test.go
  internal/pkg/api/handleAudit_test.go
  internal/pkg/api/handlePGPRequest_test.go
  internal/pkg/api/metrics_integration_test.go
  internal/pkg/api/openapi_spec_test.go
  internal/pkg/apikey/apikey_integration_test.go
  internal/pkg/apikey/auth_test.go
  internal/pkg/bulk/bulk_integration_test.go
  internal/pkg/bulk/bulk_remote_output_test.go
  internal/pkg/bulk/bulk_test.go
  internal/pkg/bulk/opMulti_integration_test.go
  internal/pkg/bulk/opMulti_test.go
  internal/pkg/checkin/bulk_test.go
  internal/pkg/dl/action_results_integration_test.go
  internal/pkg/dl/actions_integration_test.go
  internal/pkg/dl/agent_integration_test.go
  internal/pkg/dl/enrollment_api_key_integration_test.go
  internal/pkg/dl/migration_integration_test.go
  internal/pkg/dl/policies_integration_test.go
  internal/pkg/es/client_test.go
  internal/pkg/file/delivery/delivery_test.go
  internal/pkg/file/es_test.go
  internal/pkg/file/uploader/upload_test.go
  internal/pkg/gc/actions_integration_test.go
  internal/pkg/logger/http_test.go
  internal/pkg/logger/logger_test.go
  internal/pkg/monitor/monitor_integration_test.go
  internal/pkg/monitor/subscription_monitor_integration_test.go
  internal/pkg/policy/monitor_integration_test.go
  internal/pkg/policy/policy_output_integration_test.go
  internal/pkg/profile/profile_test.go
  internal/pkg/server/agent_test.go
  internal/pkg/server/fleet_integration_test.go
  internal/pkg/server/fleet_secrets_integration_test.go
  internal/pkg/server/fleet_test.go
  internal/pkg/server/namespaces_integration_test.go
  internal/pkg/server/remote_es_output_integration_test.go
  internal/pkg/ver/check_test.go
Labels: backport-skip, Team:Elastic-Agent-Control-Plane

#4894 ci: bump golangci-lint.yml
  .github/workflows/golangci-lint.yml
Labels: backport-skip, Team:Elastic-Agent-Control-Plane, skip-changelog

#4896 catalog-info: grant manage access to the CI robots team
  catalog-info.yaml
Labels: backport-skip

#4889 Add ms_tls13kdf tag when requirefips is passed
  Makefile
  docs/fips.md
  testing/e2e/fips_test.go
Labels: Team:Elastic-Agent-Control-Plane, tech debt, backport-8.19

#4984 Reenable benchmark steps
  .buildkite/pipeline.yml
Labels: Team:Elastic-Agent-Control-Plane, tech debt, backport-8.19

#4985 Ensure directory is made within zip artifacts
  magefile.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-8.19
