Repository elastic/fleet-server, pull requests merged in 2025-10, with the labels that each got.

#5565 [docs] Refine Markdown release notes structure
  docs/release-notes/_snippets/9.0.0/breaking-changes.md
  docs/release-notes/_snippets/9.0.1/breaking-changes.md
  docs/release-notes/_snippets/9.0.2/breaking-changes.md
  docs/release-notes/_snippets/9.0.3/breaking-changes.md
  docs/release-notes/_snippets/9.0.4/breaking-changes.md
  docs/release-notes/_snippets/9.0.5/breaking-changes.md
  docs/release-notes/_snippets/9.0.6/breaking-changes.md
  docs/release-notes/_snippets/9.0.7/breaking-changes.md
  docs/release-notes/_snippets/9.1.0/breaking-changes.md
  docs/release-notes/_snippets/9.1.1/breaking-changes.md
  docs/release-notes/_snippets/9.1.2/breaking-changes.md
  docs/release-notes/_snippets/9.1.3/breaking-changes.md
  docs/release-notes/_snippets/9.1.4/breaking-changes.md
  docs/release-notes/_snippets/breaking-changes.md
  docs/release-notes/_snippets/breaking-changes/9.0.md
  docs/release-notes/_snippets/breaking-changes/9.1.md
  docs/release-notes/_snippets/deprecations.md
  docs/release-notes/_snippets/deprecations/9.0.md
  docs/release-notes/_snippets/deprecations/9.1.md
  docs/release-notes/_snippets/index.md
  docs/release-notes/_snippets/index/9.0.md
  docs/release-notes/_snippets/index/9.1.md
Labels: documentation, docs, Team:Docs, backport-active-9, skip-changelog

#5625 Changelog for 9.1.5
  changelog/9.1.5.yaml
  changelog/fragments/1758819869-bump-golang-1.25.1.yaml
  docs/release-notes/_snippets/9.1.5/breaking.md
  docs/release-notes/_snippets/9.1.5/deprecations.md
  docs/release-notes/_snippets/9.1.5/index.md
Labels: forwardport-main

#5626 Changelog for 9.0.8
  changelog/9.0.8.yaml
  changelog/fragments/1758819869-bump-golang-1.25.1.yaml
  docs/release-notes/_snippets/9.0.8/breaking.md
  docs/release-notes/_snippets/9.0.8/deprecations.md
  docs/release-notes/_snippets/9.0.8/index.md
Labels: forwardport-main, backport-9.1
