Repository elastic/fleet-server, pull requests merged in 2025-07, with the labels that each got.

#5069 Include base error for json decode error responses
  changelog/fragments/1750971846-Include-error-on-json-decode-error-responses.yaml
  internal/pkg/api/error.go
  internal/pkg/api/handleAck_test.go
  internal/pkg/api/handleAudit_test.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/handleEnroll_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-active-all

#5129 Add `backport-active-all` label to Golang bump PRs
  .ci/bump-golang.yml
Labels: backport-skip, Team:Elastic-Agent-Control-Plane, skip-changelog

#5123 bk: use ubuntu 22.04
  .buildkite/pipeline.package.mbp.yml
Labels: backport-8.18, backport-8.19, backport-9.1

#5111 Add cancelations to policy monitor dispatches
  changelog/fragments/1751913009-Cancel-policy-dispatches-when-a-new-revision-arrives.yaml
  internal/pkg/policy/monitor.go
  internal/pkg/policy/monitor_test.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#5154 Handle new PrivilegeLevelChangeAction
  changelog/fragments/1752481082-Privileged-level-change-action-added.yaml
  internal/pkg/api/handleAck_test.go
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/openapi.gen.go
  model/openapi.yml
  pkg/api/types.gen.go
Labels: enhancement, backport-skip, Team:Elastic-Agent-Control-Plane

#5163 Fix changed files check in the post-dependabot GHA job
  .github/workflows/post-dependabot.yml
Labels: backport-skip, Team:Elastic-Agent-Control-Plane, ci, skip-changelog

#5158 Update oapi-codegen
  NOTICE-fips.txt
  NOTICE.txt
  changelog/fragments/1752600133-Update-oapi-codegen-and-runtime.yaml
  dev-tools/go.mod
  dev-tools/go.sum
  go.mod
  go.sum
  internal/pkg/api/openapi.gen.go
  model/openapi.yml
  pkg/api/client.gen.go
  pkg/api/go.mod
  pkg/api/go.sum
  pkg/api/types.gen.go
  testing/go.mod
  testing/go.sum
Labels: backport-skip, Team:Elastic-Agent-Control-Plane, tech debt

#5145 bk: use latest FIPS VM images and stop using catalog-info step but GH actions validation
  .buildkite/pipeline.yml
Labels: Team:Elastic-Agent-Control-Plane, backport-9.0, backport-8.19, backport-9.1

#5168 mergify: simplify and honour the defaults
  .mergify.yml
Labels: backport-skip, skip-changelog

#5176 Fix download_rate as string on checkin handling
  changelog/fragments/1753372819-Fix-download_rate-as-string-handling.yaml
  dev-tools/integration/docker-compose.yml
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/api/metadata_test.go
  testing/e2e/api_version/client_api_current.go
  testing/e2e/scaffold/scaffold.go
  testing/e2e/stand_alone_api_test.go
Labels: bug, Team:Elastic-Agent-Control-Plane, backport-active-all
