Repository elastic/fleet-server, pull requests merged in 2025-01, with the labels that each got.

#4288 Remove deprecated policy_throttle config
  changelog/fragments/1736277781-Remove-deprecated-policy_throttle.yaml
  fleet-server.reference.yml
  internal/pkg/config/limits.go
  internal/pkg/policy/monitor.go
  internal/pkg/policy/monitor_test.go
Labels: backport-skip, Team:Elastic-Agent-Control-Plane, tech debt

#4326 Cleanup various code smells withing Makefile ands supporting scripts
  .buildkite/scripts/release-manager.sh
  .buildkite/scripts/test-release.sh
  Makefile
  dev-tools/common.bash
Labels: Team:Elastic-Agent-Control-Plane, tech debt, backport-8.x

#4328 Allow use of version qualifier for staging artifacts
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/pipeline.package.mbp.yml
  .buildkite/scripts/dra_release.sh
  .buildkite/scripts/package.sh
Labels: Team:Elastic-Agent, cleanup, Team:Elastic-Agent-Control-Plane, backport-8.x

#4338 Allow staging build on main with version qualifier
  .buildkite/pipeline.package.mbp.yml
  .buildkite/scripts/package.sh
Labels: backport-8.x, backport-8.16, backport-8.17

#4318 FIPS compliant builds
  .buildkite/scripts/test-release.sh
  Dockerfile.fips
  Makefile
  dev-tools/multipass-cloud-init.yml.envsubst
  docs/fips.md
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x

#4344 github-actions(pre-commit): detect merge conflicts and shebangs
  .buildkite/hooks/post-checkout
  .buildkite/scripts/local_build.sh
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  gobenchdata-checks.yml
Labels: backport-8.x, backport-8.17

#4348 Update catalog-info.yaml to comply with SRE recommendation
  catalog-info.yaml
Labels: backport-8.x

#4351 ci(buildkite): exclude files/folders that are not tested in Buildkite
  .buildkite/pull-requests.json
Labels: backport-8.x

#4367 Bump ristretto to v0.2.0
  NOTICE.txt
  go.mod
  go.sum
  testing/go.mod
  testing/go.sum
Labels: dependency, backport-7.17, backport-8.x, backport-8.16, backport-8.17

#4393 Use centralized version qualifier
  .buildkite/pipeline.package.mbp.yml
  .buildkite/scripts/version_qualifier.sh
Labels: ci

#4361 Change CA generation in tests to avoid using SHA1
  internal/pkg/testing/certs/certs.go
Labels: Team:Elastic-Agent-Control-Plane, tech debt, backport-8.x

#4398 mergify: remove backport-8.x enforcement
  .mergify.yml
Labels: backport-skip
