Repository elastic/fleet-server, pull requests merged in 2025-03, with the labels that each got.

#4536 use golang-crossbuild native to ARM64
  Makefile
Labels: backport-active-9, backport-active-8

#4544 Add BUILDKITE_ANALYTICS_TOKEN in fips-e2e-test step
  .buildkite/hooks/pre-command
Labels: Team:Elastic-Agent-Control-Plane, ci

#4542 pbkdf2 settings validation is FIPS compliant
  changelog/fragments/1741108238-pbkdf2-settings-is-FIPS-compliant.yaml
  internal/pkg/config/pbkdf2.go
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.18, backport-9.0

#4543 Update to go v1.24.0
  .buildkite/pipeline.yml
  .buildkite/scripts/local_build.sh
  .go-version
  .golangci.yml
  NOTICE.txt
  changelog/fragments/1741109055-Update-to-go-v1.24.0.yaml
  go.mod
  internal/pkg/api/handleEnroll.go
  testing/go.mod
Labels: enhancement, Team:Elastic-Agent-Control-Plane, backport-8.x, backport-8.18, backport-9.0

#4555 Update pipeline.package.mbp.yml
  .buildkite/pipeline.package.mbp.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
Labels: backport-active-all

#4528 Clear agent.upgrade_attempts on upgrade complete
  changelog/fragments/1740760469-Clear-agent-upgrade-attempts-when-upgrade-complete.yaml
  internal/pkg/api/handleCheckin.go
  internal/pkg/api/handleCheckin_test.go
  internal/pkg/dl/constants.go
  internal/pkg/model/schema.go
  model/schema.json
Labels: enhancement, backport-skip, Team:Elastic-Agent-Control-Plane

#4515 Adding more resilitent defaults to ES client
  NOTICE.txt
  go.mod
  go.sum
  internal/pkg/api/handleFileDelivery.go
  internal/pkg/api/handleFileDelivery_test.go
  internal/pkg/es/client.go
  internal/pkg/server/agent_integration_test.go
  testing/e2e/scaffold/scaffold.go
  testing/e2e/stand_alone_test.go
  testing/go.mod
  testing/go.sum
Labels: enhancement, Team:Elastic-Agent-Control-Plane

#4567 More relaxed retries in agent tests
  internal/pkg/server/agent_integration_test.go
Labels: flaky-test, Team:Elastic-Agent-Control-Plane, backport-active-9

#4600 Remove WithUsrPwd
  internal/pkg/bulk/setup_test.go
  internal/pkg/es/client.go
Labels: Team:Elastic-Agent-Control-Plane, backport-8.x, backport-9.0

#4581 Add go1.24 GODEBUG=fips140=only test
  .buildkite/pipeline.yml
  .buildkite/scripts/unit_test.sh
  Makefile
Labels: Team:Elastic-Agent-Control-Plane, tech debt, backport-8.x, backport-9.0

#4615 Update golangci-lint.yml
  .github/workflows/golangci-lint.yml
Labels: Team:Elastic-Agent-Control-Plane

#4625 chore(deps): update golang.org/x/net v0.37.0
  NOTICE.txt
  go.mod
  go.sum
  testing/go.mod
  testing/go.sum
Labels: backport-8.x, backport-8.16, backport-8.17, backport-8.18, backport-9.0

#4632 docs: fix Dockerfile.build name
  docs/docker-images.md
Labels: Team:Elastic-Agent-Control-Plane, backport-active-all

#4574 Add DRA FIPS artifacts to package pipeline
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/pipeline.package.mbp.yml
  .buildkite/scripts/common.sh
  .buildkite/scripts/local_build.sh
  .buildkite/scripts/package.sh
  .buildkite/scripts/test-release.sh
  Dockerfile.fips
  Makefile
  dev-tools/e2e/Dockerfile
  dev-tools/e2e/build.sh
  docs/fips.md
  testing/e2e/fips_test.go
Labels: Team:Elastic-Agent-Control-Plane, tech debt, backport-8.x

#4687 Cleanup debug logs
  cmd/fleet/main.go
  internal/pkg/action/token_resolver.go
Labels: Team:Elastic-Agent, Team:Elastic-Agent-Control-Plane

#4695 (fips): match pbkdf2 validation with requirements and error msg
  internal/pkg/config/pbkdf2.go
  internal/pkg/config/pbkdf2_test.go
Labels: Team:Elastic-Agent-Control-Plane

#4708 dependabot: add github composite actions
  .github/dependabot.yml
Labels: backport-skip

#4735 [mergify] Remove 8.16 as an active branch
  .mergify.yml
Labels: Team:Elastic-Agent-Control-Plane

#4694 Use dev-tools/go.mod for tool tracking
  Makefile
  dev-tools/go.mod
  dev-tools/go.sum
  main.go
Labels: Team:Elastic-Agent-Data-Plane, Team:Elastic-Agent-Control-Plane, tech debt

#4622 Custom user for Docker builder
  Dockerfile.build
  Dockerfile.fips
Labels: Team:Elastic-Agent-Control-Plane, backport-active-9

#4747 Removed quotes from changelog file
  changelog/fragments/1729782694-Fleet-Server-uses-ssl-verification_mode-certificate-by-default-for-incomming-client-connections.yaml
Labels: enhancement
